### ISSUE TITLE
UpdateStatusComplex doesnt set the status

### ISSUE THREAD

**Issue by M1K8** [bwmarrin/discordgo#1007]
When trying to set a custom status with the following code, nothing is displayed in the status field of my bot:

```
err := s.UpdateStatusComplex(discordgo.UpdateStatusData{
		Activities: []*discordgo.Activity{
			{
				Name: "name",
				Type: discordgo.ActivityTypeCustom,
			},
		},
		Status: "online",
	})
```

err is nil, so I am unsure as to why this doesnt work. If I change the type, it displays as expected.

**Comment by arHSM** [comment]
Quick note, bots cant have "custom" status. That custom there is the same as the custom status users set like "A busy gopher" but bots cant have custom statuses, they can have `"online"`, `"idle"` and `"dnd"` tho; and iirc they can also have `"invisible"`
You can also refer to the source for the `newUpdateStatusData` function (which i always have to copy whenever i have to work with bot statuses, idk why its not exported...)
> `discordgo.ActivityTypeCustom` is 
> `4 | Custom | {emoji} {name} | ":smiley: I am cool"`
> Which bots cannot use

```go
func newUpdateStatusData(idle int, activityType ActivityType, name, url string) *UpdateStatusData {
	usd := &UpdateStatusData{
		Status: "online",
	}

	if idle > 0 {
		usd.IdleSince = &idle
	}

	if name != "" {
		usd.Activities = []*Activity{{
			Name: name,
			Type: activityType,
			URL:  url,
		}}
	}

	return usd
}
```

Under the hood dgo uses `UpdateStatusComplex` for `UpdateGameStatus` etc. 
For example:
```go
func (s *Session) UpdateStreamingStatus(idle int, name string, url string) (err error) {
	gameType := ActivityTypeGame
	if url != "" {
		gameType = ActivityTypeStreaming
	}
	return s.UpdateStatusComplex(*newUpdateStatusData(idle, gameType, name, url))
}
```

**Comment by FedorLap2006** [comment]
Looks like the issue is resolved.
