### ISSUE TITLE
ApplicationCommand Doesn't Exist

### ISSUE THREAD

**Issue by ethsmith** [bwmarrin/discordgo#1018]
Your slash commands example doesn't work because ApplicationCommand doesn't exist anymore but it was added 4 days ago,

**Comment by FedorLap2006** [comment]
> Use `go get github.com/bwmarrin/discordgo@HEAD`. This gets the latest commit, as application commands are not stable at the moment.

This and https://github.com/bwmarrin/discordgo/wiki/FAQ#application-commands-release-notice.
