### ISSUE TITLE
How to check member permissions from messageCreate handler

### ISSUE THREAD

**Issue by thefakequake** [bwmarrin/discordgo#1019]
I used the following code:
```go
func messageCreate(s *discordgo.Session, m *discordgo.MessageCreate) {
	mem, _ := s.GuildMember(m.GuildID, m.Author.ID)
	fmt.Println(mem.Permissions)
}
```
but the `Permissions` field is always 0.

**Comment by quakecodes** [comment]
I have all intents enabled in both the dashboard and my code:
```go
dg.Identify.Intents = discordgo.IntentsAll
```
![image](https://user-images.githubusercontent.com/67868381/137965214-a0cc585b-4773-4851-b937-d811da1cc24b.png)
