### ISSUE TITLE
VoiceStates length is always 0

### ISSUE THREAD

**Issue by fishuke** [bwmarrin/discordgo#1021]
The lenght of guild.VoiceStates is 0.

```
voiceCount := len(guild.VoiceStates) // returns 0
fmt.Println(voiceCount)
```

Note: When i use disgord and arikawa the size of guild.voiceStates is not 0 but with discordgo its always 0.

**Comment by muratmirgun** [comment]
Any Updates?

**Comment by CarsonHoffman** [comment]
I'm not really sure what you're expecting an update on. The above code snippet shows the voice states being accessed before the gateway connection is formed. Voice states are only accessible via the gateway; if you check them before you've opened that connection, you're not going to see anything.

**Comment by fishuke** [comment]
Hello Carlson, above code snippet is not an example of accessing to voiceStates before gatway connection is established. There is a function for voiceStates and we call that function after bot is ready. Unfortunately it doesnt show expected voice states. Please provide an example if you can access voice states after ready event.

**Comment by CarsonHoffman** [comment]
You're aware that GitHub stores and displays edits, right? I responded to the code you posted; I can't respond to what you're going to edit the code to in the future.

![image](https://user-images.githubusercontent.com/19721219/143878976-7ee93643-9c87-46cd-8dd8-03e55b074bb7.png)

Guild information is not available immediately after the ready event. It's streamed in for each guild asynchronously via guild create events.

**Comment by fishuke** [comment]
I am aware of that it was my mistake that i sent a code snippet here that calls that function in main function. I edited the file because the code snippet is not describing my issue. Even after ready that it is still the same.

**Comment by fishuke** [comment]
> Guild information is not available immediately after the ready event. It's streamed in for each guild asynchronously via guild create events.

With discord.js all the guilds are stored in cache.

**Comment by CarsonHoffman** [comment]
Sure; it's stored in the state (the cache) in DiscordGo, too. That information is not _immediately_ available, however. It will be inserted into the state once the guild create event is received for that guild.

**Comment by FedorLap2006** [comment]
Looks like issue is resolved. I'm going to close this.
