### ISSUE TITLE
Finding out if a user is an admin

### ISSUE THREAD

**Issue by BruceJi7** [bwmarrin/discordgo#1024]
Hi,

I'm looking for a way to find out if a user is an admin or not.
I have a discord.py bot that I'm trying to rewrite in Go.
Many of the commands in that bot are only for admins to use - erasing messages, for example.

I've checked in the user and members types, and also the role types, but none of these have an admin property available.
The closest I can see is the permissions property on Role, but it returns integer values.
There doesn't seem to be any guidance for what permission values mean what permissions.

Can you advise me on if there is such a function or property as 'isAdmin' that already exists? Or if not, can you let me know how to find out what permissions mean what?

Thanks!

**Comment by lamados** [comment]
i think you should be using `(*Session).State.UserChannelPermissions` in something like this (someone else correct me if i'm wrong)

```go
perms, err := session.State.UserChannelPermissions(userID, channelID)
if err != nil {
  // handle err...
}
if perms&discordgo.PermissionAdministrator == 0 {
  // user is not an administrator.
} else {
  // user is an administrator.
}
```

this basically checks to see if the user with ID `userID` has administrator permissions in the channel with ID `channelID`. you can also replace `discordgo.PermissionAdministrator` with something like `discordgo.PermissionManageMessages` to check if the user has Manage Message permissions in that channel, or whatever else you replace it with. check [this part of the docs](https://pkg.go.dev/github.com/bwmarrin/discordgo#pkg-constants) for a list of all the permissions.

**Comment by odiferousmint** [comment]
> i think you should be using `(*Session).State.UserChannelPermissions` in something like this (someone else correct me if i'm wrong)
> 
> ```go
> perms, err := session.State.UserChannelPermissions(userID, channelID)
> if err != nil {
>     // handle err...
> }
> 
> if perms&discordgo.PermissionAdministrator == 0 {
>     // user is not an administrator.
> } else {
>     // user is an administrator.
> }
> ```
> 
> this basically checks to see if the user with ID `userID` has administrator permissions in the channel with ID `channelID`. you can also replace `discordgo.PermissionAdministrator` with something like `discordgo.PermissionManageMessages` to check if the user has Manage Message permissions in that channel, or whatever else you replace it with. check [this part of the docs](https://pkg.go.dev/github.com/bwmarrin/discordgo#pkg-constants) for a list of all the permissions.

`err` is not nil, it is `state cache not found`, but it correctly knows that I am an administrator. I currently cannot try it on a different server (or with a different account) to check if it also correctly knows when I am not an administrator.

That said, I have no clue why I get `state cache not found`. Any ideas?

**Comment by TannerKvarfordt** [comment]
While searching for answers myself, I noticed that #876 attempts to answer a similar question, so I figured I'd drop a link to it here. 

I actually ended up not using any `State` methods, and instead retrieved the user permissions from `(*InteractionCreate).Member.Permissions`, though that will only be useful if you're making use of [Slash Commands](https://support.discord.com/hc/en-us/articles/1500000368501-Slash-Commands-FAQ).
