### ISSUE TITLE
error closing resp body

### ISSUE THREAD

**Issue by exsocial** [bwmarrin/discordgo#1028]
Recently started getting this error logged into the standard output, it started appearing 1 day ago. 
It is logged on this line in **restapi.go**
https://github.com/bwmarrin/discordgo/blob/007bf767904825eb3d881daa136698771d3ee0cb/restapi.go#L112

It seems the response body can't be closed properly. The underlying error _err2_ has value _context canceled_
Bot seems to keep working fine, but I'm concerned it may be causing memory leaks.
![issue](https://user-images.githubusercontent.com/54414306/141128909-f9e5da8c-c115-43cd-930f-78e74fa556f0.png)

**Comment by CarsonHoffman** [comment]
This is a [bug in Go 1.17.3](https://github.com/golang/go/issues/49366). Downgrade to 1.17.2 or wait for 1.17.4, where the patch will presumably be applied.
