### ISSUE TITLE
Connecting, disconnecting and then reconnecting to VoiceChannel results in panic writing to closed channel

### ISSUE THREAD

**Issue by alex-broad** [bwmarrin/discordgo#1035]
Hi,

I've mostly cribbed the example code for your [voice-receive](https://github.com/bwmarrin/discordgo/blob/master/examples/voice_receive/main.go) example and embedded it in [a bot](https://github.com/azekeil/grec) to allow me to control it.. but despite following the example where you `close(*discordgo.VoiceConnection.OpusRecv)` and then `*discordgo.VoiceConnection.Close()` (and I then `s.ChannelVoiceJoinManual(r.Guild.ID, "", true, false)` to make the bot leave the voice channel... there isn't an explicit `ChannelVoiceLeave()` it seems?)

On starting speaking, it panics:
```
panic: send on closed channel

goroutine 70 [running]:
github.com/bwmarrin/discordgo.(*VoiceConnection).opusReceiver(0xc0000de420, 0xc000366088, 0xc0000a3b00, 0xc0004ea480)
        /home/azekeil/go/pkg/mod/github.com/bwmarrin/discordgo@v0.23.2/voice.go:840 +0x2d8
created by github.com/bwmarrin/discordgo.(*VoiceConnection).onEvent
        /home/azekeil/go/pkg/mod/github.com/bwmarrin/discordgo@v0.23.2/voice.go:441 +0x6d8
exit status 2
```

Have I done something wrong?

Thanks in advance, appreciate your library!

**Comment by la4zen** [comment]
I have same problem too.
