### ISSUE TITLE
Passing data from a message context menu command to a dropdown it creates.

### ISSUE THREAD

**Issue by vidhanio** [bwmarrin/discordgo#1040]
I want to send the message content of a message component to a dropdown so that it can process it when the user selects the option from the dropdown. Is this possible in discordgo?

**Comment by FedorLap2006** [comment]
I think it is.

**Comment by vidhanio** [comment]
How would I go about doing so?

**Comment by FedorLap2006** [comment]
> How would I go about doing so?

Not sure if it's still actual, but you can use `discordgo.SelectMenu` to create a dropdown. Additionally, to identify it, you need to assign `customID`.
To handle option selection you can register an interaction handler (`*discordgo.InteractionCreate`). Check for interaction type (it should be `discordgo.InteractionMessageComponent`), use `customID` to identify which select menu was used (if you have multiple) and use `interaction.MessageComponentData().Values` to retrieve selected options.

**Comment by FedorLap2006** [comment]
Since this issue is stale, I think would be better to close it.
