### ISSUE TITLE
Documentation for getting all the tests to pass

### ISSUE THREAD

**Issue by danbrakeley** [bwmarrin/discordgo#1041]
I didn't see any documentation on what it takes to get the tests to run without error, and I'm curious if that exists somewhere already, or if someone who understands all that could write something up.

I'm also new to Discord apps/bots in general, so today I spent a couple hours just understanding what a User Token was and how to get one, and while I believe I have a dummy oauth2 flow setup properly (I got to the point where I was able to exchange a code for an access_token), I'm still getting "HTTP 401 Unauthorized" from a bunch of the restapi tests so I clearly haven't figured it all out yet, and just having a single source of truth for how to get all the tests running from nothing would be really nice.

**Comment by FedorLap2006** [comment]
Some of the tests needed to be removed and some didn't have a proper check for the token. Everything should be fine now.
