### ISSUE TITLE
Application command adds globally when specified `ChannelTypeDM`

### ISSUE THREAD

**Issue by dn-l** [bwmarrin/discordgo#1048]
```golang
{Name: "test", Description: "Test desc", Options: []*discordgo.ApplicationCommandOption{
	{
		Type:         discordgo.ApplicationCommandOptionString,
		Name:         "param",
		Description:  "param desc",
		ChannelTypes: []discordgo.ChannelType{discordgo.ChannelTypeDM},
		Required:     true,
	},
}},
```

I iterate through the commands and add all the commands globally:
```golang
dg.ApplicationCommandBulkOverwrite(dg.State.User.ID, "", commands)
``` 

Is there any way to create the specified command only for DM and not for a guild channel? `ChannelTypeDM` doesn't change anything

**Comment by FedorLap2006** [comment]
Sorry for a late response.
It's not currently possible, however you can set `default_member_permissions` to `0` and `dm_permission` to `true`, to achieve a similar behaviour (note that you might need to use `@master` version instead of tagged ones).
