### ISSUE TITLE
Problem with the MessageCreate event

### ISSUE THREAD

**Issue by Yakabuff** [bwmarrin/discordgo#1066]
Hello, I noticed something odd when using the MessageCreate event.  When someone posts a message with an embed (eg. any tweet with an image or a youtube link), the event does not detect any embeds.  Other fields like channelID, messageID and content are detected except for the embeds field which remains empty.  However, if I enter the exact same message again, it detects the correct number of embeds.  

```
2022/01/01 15:13:05 DETECTED NEW MESSAGE !! Inserting message 123123123 from 234234234
2022/01/01 15:13:05 []
2022/01/01 15:13:05 https://www.youtube.com/watch?v=asdfsadf
2022/01/01 15:13:21 DETECTED NEW MESSAGE !! Inserting message 123123123 from 234234234
2022/01/01 15:13:21 [0xc0000b4be0]
2022/01/01 15:13:21 https://www.youtube.com/watch?v=asdfasdf
```

```
func messageListen(dg *discordgo.Session, m *discordgo.MessageCreate) {
	log.Println("DETECTED NEW MESSAGE !! Inserting message " + m.ID + " from" + m.ChannelID)
	log.Println(m.Embeds)
	log.Println(m.Content)
}
```
Anyone know why?

**Comment by CarsonHoffman** [comment]
Embeds generated by links aren't necessarily immediately available—they are asynchronously inserted into messages later via a message update. (Notice how the embeds take a second to load after the message is posted—that's two separate events). Perhaps Discord has the embed cached the second time around to be able to insert it immediately.
