### ISSUE TITLE
Is possible to detect member's rule screening checks with discordgo?

### ISSUE THREAD

**Issue by vico93** [bwmarrin/discordgo#1069]
I was searching for a bot (or code to run one) that allows users that accept [rule screening](https://support.discord.com/hc/pt-br/articles/1500000466882-Rules-Screening-FAQ) to have automatically a role after, since in my server we use a basic role for new members.

[Searching](https://www.reddit.com/r/discordapp/comments/khtyop/a_discord_bot_to_add_roles_after_rule_screening/) on [Reddit](https://www.reddit.com/r/discordapp/comments/ki7iq7/give_roles_to_users_at_joining_with_rule/), i found there is an [API verification](https://discord.com/developers/docs/resources/guild#guild-member-object) that is already implemented on [discord.py](https://discordpy.readthedocs.io/en/latest/api.html?highlight=keep%20alive#discord.Member.pending) and seems to be possible to achieive in [discordia](https://github.com/SinisterRectus/Discordia/issues/329) (i asked the same question there).

Is this already possible with discordgo?

**Comment by 42Atomys** [comment]
Hi, it's possible to detect it with `Pending` field on `Member` object like following

```go
	user, err := s.GuildMember(guildID, userID)
	if (err != nil) {
		panic(err)
	}
	fmt.Println(user.Pending)
```

In your case you can do that simply with discordgo

```go
const roleToAdd = "yourRoleIdHere"

func main() {
	s, _ := discordgo.New("Bot TOKEN")
	err := s.Open()
	if err != nil {
		log.Fatalf("Cannot open the session: %v", err)
	}
	defer s.Close()

	s.AddHandler(handleMemberUpdate)

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt)
	<-stop
	log.Println("Graceful shutdown")
}

func handleMemberUpdate(s *discordgo.Session, m *discordgo.GuildMemberUpdate) {
	if !m.Pending {
		s.GuildMemberRoleAdd(m.GuildID, m.User.ID, roleToAdd)
	}
}
```

@FedorLap2006 I think no feature is to add here

**Comment by FedorLap2006** [comment]
I'll look through the docs

**Comment by 42Atomys** [comment]
Can be usefull for gain time : https://discord.com/developers/docs/resources/guild#membership-screening-object
