### ISSUE TITLE
The func InviteAccept doesn't work in V8 api

### ISSUE THREAD

**Issue by qcozof** [bwmarrin/discordgo#1078]
discordgo vision: v0.23.1 v0.23.2

call InviteAccept( inviteID ) , return 404 not found

https://discord.com/api/v8/invite/{inviteID}
HTTP 404 Not Found, {"message": "404: Not Found", "code": 0}

switch to v9 api
https://discord.com/api/v9/invite/{inviteID}
v9 work fine.

**Comment by FedorLap2006** [comment]
#1058 should solve the issue, it upgrades the API to v9.
