### ISSUE TITLE
WebSocket connection stopped working

### ISSUE THREAD

**Issue by CssHammer** [bwmarrin/discordgo#1079]
Was able to connect to websocket an hour ago but now i'm getting this with any token
`error opening connection, websocket: close 1000 (normal)`

**Comment by vidhanio** [comment]
Probably something to do with this.
Discord API is wonky rn, just gotta wait a bit for them to fix it on their end.

![image](https://user-images.githubusercontent.com/41439633/151248100-68f81c6a-6b01-4cbc-a426-006003f63526.png)

**Comment by FedorLap2006** [comment]
Looks like the issue is solved.
