### ISSUE TITLE
There is no function to get a role struct by name or ID

### ISSUE THREAD

**Issue by uvulpos** [bwmarrin/discordgo#1080]
I need to find roles by name or ID, but I couldn't find any solution due to this problem. It seems like I have to receive all roles as an array and search it by myself. Is it possible to add such a search method?

Thanks 🙂

**Comment by FedorLap2006** [comment]
I don't think so, DiscordGo is low level wrapper for Discord API, we try to provide only necessary utility functions. Other than this we try to do 1:1 of Discord API. If it doesn't have this feature, then the only method is yes, doing it by hand.
