### ISSUE TITLE
Websocket authentication failed 

### ISSUE THREAD

**Issue by cdoern** [bwmarrin/discordgo#1081]
getting `websocket: close 4004: Authentication failed`. after a fresh build on all of my dev environments. I can log in to a bot account but when I go to start a message listening session this error persistently pops up. Has been happening for two days.

@bwmarrin Please take a look.

**Comment by CarsonHoffman** [comment]
What does "log in to a bot account" mean? Call `New` without error? If so, this doesn't actually check your credentials; only opening the session or attempting to make an HTTP call will. Please provide more details on what works and what doesn't, especially with regards to you successfully making a call with the same session that is giving you this error. Without that, we can only assume it's human error.

**Comment by cdoern** [comment]
This is what fails:

```
// login to the discord account given
	dg, err := utils.LoginDiscord(Token)
	if err != nil {
		return err
	}
	// create writer for the message table
	rows = make(chan []string)

	// add discord event listeners
	dg.AddHandler(list)
	dg.Identify.Intents = discordgo.IntentsGuildMessages

	err = dg.Open()
	if err != nil {
		return err
	}
```

`utils.LoginDiscord` is as follows:

```
func LoginDiscord(token string) (*discordgo.Session, error) {
	fmt.Print(
		"    __ __\n" +
			"   / //_/___  ________ _________ \n" +
			"  / ,< / __ \\/___/ _ \\/ ___/ __ \\\n" +
			" / /| / /_/ / / /  __/ /  / /_/ /\n" +
			"/_/ |_\\____/_/  \\___/_/   \\____/\n\n")
	if len(token) > 0 {
		if err := os.Setenv("KORERO_DISCORD_TOKEN", token); err != nil {
			return nil, err
		}
	} else {
		token = os.Getenv("KORERO_DISCORD_TOKEN")
	}
	if len(token) == 0 {
		return nil, errors.New("token length is zero, to use a default token please set $KORERO_DISCORD_TOKEN")
	}
	return discordgo.New("Bot " + token)
}
```

**Comment by cdoern** [comment]
This worked for weeks on end as coded @CarsonHoffman the above code has not been changed and the binary file I am making has not been updated since the code successfully worked so I would not describe this as user error, nothing has changed on my end

**Comment by CarsonHoffman** [comment]
You're depending on the environment, though. A 4004 means that your token is incorrect, full stop. This comes straight from Discord; it isn't an error that the library emits.

**Comment by cdoern** [comment]
hm, let me try messing around with my bot and seeing if that fixes anything

**Comment by cdoern** [comment]
fixed, I recreated my bot account and authentication worked. I must've messed up something with the configuration on discord
