### ISSUE TITLE
Use Discord API version 9

### ISSUE THREAD

**Issue by lucianonooijen** [bwmarrin/discordgo#1082]
It looks like the package is using Discord API version 8. 

For some features (including the creation of threads in channels) the Discord API version 9 is required.

**Comment by jameswritescode** [comment]
v10 is coming and v8 is being deprecated: https://github.com/discord/discord-api-docs/discussions/4510

**Comment by lucianonooijen** [comment]
I see! There is a MR open for adding threads (https://github.com/bwmarrin/discordgo/pull/1058/files) but indeed upgrading to version 10 might be required soon as well to keep this package up to date (preferably before the April 30th deprecation date for v9).

**Comment by FedorLap2006** [comment]
Thank you for the issue! Upgrade to `v10 ` will follow after the threads PR merge, which will happen soon. So, no worries about the older API version.
