### ISSUE TITLE
Examples aren't up to date, plus up to date example suggestion

### ISSUE THREAD

**Issue by hayunofek** [bwmarrin/discordgo#1085]
Hey, as I was exposed to this module recently, one of the first things I had in mind was to check out the examples. Turns out, the examples are outdated and aren't up to date with the recent versions of the code, and aren't compatible with it.

Firstly, I think that they should be removed or tagged as deprecated, because they can be quite confusing to new people, who are exposed to non-compatible examples.

Secondly, I believe that my own recent implementation of a discord bot, written using this module could be a good example to show case, as an example of usage for newcomers to this repository.
A link to my repository which I believe could be of good use:  https://github.com/hayunofek/discord-bot

**Comment by CarsonHoffman** [comment]
Which examples are outdated? I believe that all should still work.

**Comment by hayunofek** [comment]
> Which examples are outdated? I believe that all should still work.
Hmm. The [slash_commands](https://github.com/bwmarrin/discordgo/blob/master/examples/slash_commands/main.go). Now that I went over the rest of the examples, it seems like the rest of the works (haven't went over all of them), so that makes me wonder perhaps only the examples utilizing the `discordgo.ApplicationCommand` struct aren't working anymore.

**Comment by CarsonHoffman** [comment]
These are actually new examples, not outdated—you aren't using the library at the `master` branch, but likely an older tag. If you're looking at examples on the `master` branch, you also need to use the library there.

**Comment by hayunofek** [comment]
> These are actually new examples, not outdated—you aren't using the library at the `master` branch, but likely an older tag. If you're looking at examples on the `master` branch, you also need to use the library there.

I am looking at the [package go reference](https://pkg.go.dev/github.com/bwmarrin/discordgo#section-readme) and it doesn't seem to have that struct. Also, I used the module at v0.23.2, which by looking at the master branch seems like the latest tag to me. Am I missing something?

**Comment by CarsonHoffman** [comment]
v0.23.2 is the latest tag, yes, but it isn't the latest commit. `master` is ahead of it. You can view its documentation with https://pkg.go.dev/github.com/bwmarrin/discordgo@master.

**Comment by hayunofek** [comment]
> v0.23.2 is the latest tag, yes, but it isn't the latest commit. `master` is ahead of it. You can view its documentation with https://pkg.go.dev/github.com/bwmarrin/discordgo@master.

Oh I see. I confused Feb 5th 2021 with 2022 in my head. Apologies for the misinformation, you can close this issue.
