### ISSUE TITLE
Unable to delete previous ephemeral interaction response

### ISSUE THREAD

**Issue by devmedoo** [bwmarrin/discordgo#1086]
After successfully sending a ephemeral interaction response, I am unable to delete it.

`s.InteractionResponseDelete(appID, i.Interaction)`
returns 
`{"message": "Unknown Webhook", "code": 10015}`

**Comment by CarsonHoffman** [comment]
This is not possible in the API. The library cannot do anything about it.

**Comment by Klace** [comment]
Is this possible now? Supposedly Discord added support back in Oct 2022

**Comment by Roolps** [comment]
You can delete it if you somehow store the interaction when it's created then delete it later, interaction tokens last for 15 minutes, attached the example here - I saved the interaction response to the 'new ticket' button, aka the creation of the form with the menu selects, and then deleted it once the user got to the next step.
<img width="485" alt="Scherm­afbeelding 2023-04-25 om 07 29 44" src="https://user-images.githubusercontent.com/87721861/234193340-2fb4dd9c-a27a-450b-b89e-d2a6075f5b3c.png">
<img width="616" alt="Scherm­afbeelding 2023-04-25 om 07 29 57" src="https://user-images.githubusercontent.com/87721861/234193346-e5dba6bc-0e12-4aac-ae24-d93aea9aac63.png">
<img width="426" alt="Scherm­afbeelding 2023-04-25 om 07 30 03" src="https://user-images.githubusercontent.com/87721861/234193349-bebf6735-db69-42cf-9dc4-97ca636c63f8.png">

https://user-images.githubusercontent.com/87721861/234193566-fc829213-c4cd-410f-8d04-74dfec3cf310.mov
