### ISSUE TITLE
Missing MessageFlags values

### ISSUE THREAD

**Issue by constantoine** [bwmarrin/discordgo#1090]
HAS_THREAD, EPHEMERAL, LOADING and FAILED_TO_MENTION_SOME_ROLES_IN_THREAD are not present in the MessageFlags const

**Comment by constantoine** [comment]
Resolved with https://github.com/bwmarrin/discordgo/pull/1089

**Comment by FedorLap2006** [comment]
It should be merged now — https://github.com/bwmarrin/discordgo/commit/d3554153f1636abbdc7e61df15efe68acbcf396b
