### ISSUE TITLE
Adding User Banners?

### ISSUE THREAD

**Issue by lxi1400** [bwmarrin/discordgo#1093]
Hey there. Banners have been out for a while but it seems that discordgo still has 0 support for them. Is there any ETA to when this will be added?

**Comment by sentinelb51** [comment]
Think it could be implemented if they add the following:

in endpoints.go:
```
EndpointUserBanner = func(uID, hash string) string { return EndpointCDNBanners + uID + "/" + hash + ".png" }
EndpointUserBannerAnimated = func(uID, hash string) string { return EndpointCDNBanners + uID + "/" + hash + ".gif" }
```

in user.go:

```
// The hash of the user's banner asset
Banner string `json:"banner,omitempty"`
```

```
// BannerURL returns a URL to the user's banner.
//    size:    The size of the user's banner as a power of two
//             if size is an empty string, no size parameter will
//             be added to the URL.
func (u *User) BannerURL(size string) string {
	var URL string

	if strings.HasPrefix(u.Banner, "a_") {
		URL = EndpointUserBannerAnimated(u.ID, u.Banner)
	} else {
		URL = EndpointUserBanner(u.ID, u.Banner)
	}

	if size != "" {
		return URL + "?size=" + size
	}
	return URL
}
```

Tested in production and seems to work fine

**Comment by lxi1400** [comment]
> Think it could be implemented if they add the following:
> 
> in endpoints.go:
> 
> ```
> EndpointUserBanner = func(uID, hash string) string { return EndpointCDNBanners + uID + "/" + hash + ".png" }
> EndpointUserBannerAnimated = func(uID, hash string) string { return EndpointCDNBanners + uID + "/" + hash + ".gif" }
> ```
> 
> in user.go:
> 
> ```
> // The hash of the user's banner asset
> Banner string `json:"banner,omitempty"`
> ```
> 
>  ```
> // BannerURL returns a URL to the user's banner.
> //    size:    The size of the user's banner as a power of two
> //             if size is an empty string, no size parameter will
> //             be added to the URL.
> func (u *User) BannerURL(size string) string {
> 	var URL string
> 
> 	if strings.HasPrefix(u.Banner, "a_") {
> 		URL = EndpointUserBannerAnimated(u.ID, u.Banner)
> 	} else {
> 		URL = EndpointUserBanner(u.ID, u.Banner)
> 	}
> 
> 	if size != "" {
> 		return URL + "?size=" + size
> 	}
> 	return URL
> }
> ```
> 
> Tested in production and seems to work fine

Only issue is that this doesn't return the accent color if a user has no banner set.
