### ISSUE TITLE
Bot.AvatarURL

### ISSUE THREAD

**Issue by Sigmw** [bwmarrin/discordgo#1118]
How can i get the bot avatar URL?

**Comment by FedorLap2006** [comment]
You need to retrieve user with id being `@me` or use `s.State.User`.
After that you use `user.AvatarURL("")` to get the url (`""` - means no size constraint is set).

**Comment by Sigmw** [comment]
> You need to get bot user. You can either fetch it - `s.User("@me")` or get it from the `Ready` payload (it's stored in the `State`), so `s.State.User`
> After that you use `user.AvatarURL("")` to get the url (`""` here indicates that there no size constraint).
> 

Yup! got it here. Thank you very much
