### ISSUE TITLE
How to get child channels from category

### ISSUE THREAD

**Issue by Nullpoir** [bwmarrin/discordgo#1121]
Hi,

I want to get child channels from category.
Could you help me?

I've tried below code but it does not seem to work as I expected.

```go
ParentChannel, err := s.Channel(Channel.ParentID)
// I get ParentChannel seems to be category but it does not have child channels attibutes...
``` 

I use `github.com/bwmarrin/discordgo v0.23.2`.

 Does this version have funtions to get child channels from category?

I write down python code as I want to do.
```python
message.channel.category.channels
# it can get child channels from category :)
```

Thank you for your reading.

**Comment by FedorLap2006** [comment]
API currently doesn't provide a way to get the child channels of the category. However, you can cycle through all guild channels which have matching `ParentID`.

**Comment by Nullpoir** [comment]
@FedorLap2006 
Thanks!
I will try way which you said :)
