### ISSUE TITLE
Input After Slash Command

### ISSUE THREAD

**Issue by switchupcb** [bwmarrin/discordgo#1124]
This "issue" is likely a limitation of the Discord API. Discord allows the user to submit input after the slash command but the interaction that Discord shows only recognizes the command used. This may be confusing for the end user when `options` are provided for this command. 

**Example**
![image](https://user-images.githubusercontent.com/81384235/156904739-e0b41e10-a9d0-4aaa-8d82-eca60b909f33.png)
_*Uses handler for `/help`._

**Is there a way to retrieve this text from Discordgo?** A decent solution is to use **autocomplete** which controls the UX enough to limit this _(but not prevent it outright)_.

**Comment by FedorLap2006** [comment]
There is no way to do that currently unfortunately. You can provide either multiple options for commands / subcommands, or use one option with autocomplete.
