### ISSUE TITLE
MessageEmbed cannot send Content

### ISSUE THREAD

**Issue by switchupcb** [bwmarrin/discordgo#1127]
**Solution:** Add content field to MessageEmbed. In the current API, the user must create a MessageEdit (or equivalent) to store regular messages with embeds. However, these cannot be sent together _(nor by using [`ChannelMessageSendEmbed`](https://github.com/bwmarrin/discordgo/blob/v0.24.0/restapi.go#L1564))_.

_What is content?_ 
Content is essentially the text you see in a regular message. See [Discohook](https://discohook.org/).

**Comment by TopiSenpai** [comment]
Use [MessageSendComplex](https://github.com/bwmarrin/discordgo/blob/45e625d5af0a09956c791db6a2947a22c55d9049/restapi.go#L1503)
