### ISSUE TITLE
Full support for modal (text input) message components

### ISSUE THREAD

**Issue by hassieswift621** [bwmarrin/discordgo#1140]
Using the library today, I noticed it does not fully support creating modals using message components. Currently the library only contains TextInput struct for the text input options. However, to fully support modals, an outer object is required to set the title and ID of the modal.

From Discord API:
```json
{
  "title": "My Cool Modal",
  "custom_id": "cool_modal",
  "components": [{
    "type": 1,
    "components": [{
      "type": 4,
      "custom_id": "name",
      "label": "Name",
      "style": 1,
      "min_length": 1,
      "max_length": 4000,
      "placeholder": "John",
      "required": true
    }]
  }]
}
```

**Comment by FedorLap2006** [comment]
DiscordGo already supports that — `InteractionResponse` has `Title` and `CustomID`

**Comment by hassieswift621** [comment]
> DiscordGo already supports that: `InteractionResponse` has `Title` and `CustomID` fields

Oh sweet, thanks for clarifying that 😃
