### ISSUE TITLE
unknown field "NameLocalizations"

### ISSUE THREAD

**Issue by parasit** [bwmarrin/discordgo#1157]
Hi,
When I try run your example from: /examples/slash_commands/main.go and got errors:
```
./main.go:52:4: unknown field 'NameLocalizations' in struct literal of type discordgo.ApplicationCommand
./main.go:55:4: unknown field 'DescriptionLocalizations' in struct literal of type discordgo.ApplicationCommand
./main.go:62:6: unknown field 'NameLocalizations' in struct literal of type discordgo.ApplicationCommandOption
./main.go:65:6: unknown field 'DescriptionLocalizations' in struct literal of type discordgo.ApplicationCommandOption
./main.go:72:8: unknown field 'NameLocalizations' in struct literal of type discordgo.ApplicationCommandOptionChoice
./main.go:79:8: unknown field 'NameLocalizations' in struct literal of type discordgo.ApplicationCommandOptionChoice
```

Looks like in latest release 0.24.0 these field are not included:

```golang
type ApplicationCommand struct {
    ID                string                 `json:"id,omitempty"`
    ApplicationID     string                 `json:"application_id,omitempty"`
    Version           string                 `json:"version,omitempty"`
    Type              ApplicationCommandType `json:"type,omitempty"`
    Name              string                 `json:"name"`
    DefaultPermission *bool                  `json:"default_permission,omitempty"`

    Description string                      `json:"description,omitempty"`
    Options     []*ApplicationCommandOption `json:"options"`
}
```

**Comment by parasit** [comment]
Small update... 
In my working dir `~/go/pkg/mod/github.com/bwmarrin/discordgo@v0.24.0/interactions.go` is "old" version, in new one just cloned from github (also 0.24.0) everything is ok... strange.

P.S. I have MacOS 12.3.1 on M1 Max (Arm64)

**Comment by FedorLap2006** [comment]
To use localization fields you gotta use `@master` version: `go get -u github.com/bwmarrin/discordgo@master`

**Comment by parasit** [comment]
> To use localization fields you need use `@master` version: `go get -u github.com/bwmarrin/discordgo@master`

I know, but... released version (installed locally by `go install ....@latest`) isn't from master branch?

**Comment by FedorLap2006** [comment]
> > To use localization fields you need use `@master` version: `go get -u github.com/bwmarrin/discordgo@master`
> 
> I know, but... released version (installed locally by `go install ....@latest`) isn't from master branch?

No, `latest` refers to latest tagged version (which is v0.24.0). You need to specifically install branch-version

**Comment by parasit** [comment]
Ok, got it. Thanks for answer.
