### ISSUE TITLE
Channel.MemberCount returns 0

### ISSUE THREAD

**Issue by 0xberkay** [bwmarrin/discordgo#1159]
I've tried to get channel's member count but member count return 0
```go

	dg.AddHandler(func(s *discordgo.Session, m *discordgo.GuildCreate) {

		fmt.Println("Guild Created:", m.Name)
		fmt.Println(m.MemberCount)

		channels := m.Channels

		for _, v := range channels {
			if v.Type == discordgo.ChannelTypeGuildVoice {
				fmt.Println(v.Name, v.MemberCount)
			}

		}

	})
        dg.Identify.Intents = discordgo.MakeIntent(discordgo.IntentsGuildMessages | discordgo.IntentsGuilds | 
        discordgo.IntentsGuildMembers | discordgo.IntentsGuildVoiceStates)
```

by the way, this function worked in discord js
```js
     client.on("guildCreate", (guild) => {
    
    guild.channels.cache.forEach(channel => {
        if (channel.type == "GUILD_VOICE") {
            console.log(channel.name, channel.members.filter(member => !member.user.bot).size);
        }
    });
});
```

**Comment by 0xberkay** [comment]
bu ist work in discord.js

Go
![Screenshot_2022-04-13-04-02-00_3840x1080](https://user-images.githubusercontent.com/70816926/163186180-b10ae643-a332-45e3-89da-87a45e6ce177.png)

Node.js
![Screenshot_2022-04-13-04-03-11_3840x1080](https://user-images.githubusercontent.com/70816926/163186275-1b6a9cf4-b4de-4828-867f-c6cfdfa81de6.png)

**Comment by TopiSenpai** [comment]
discordgo isn't discord.js

**Comment by 0xberkay** [comment]
how can ı get member count of channel in discordgo ?

**Comment by TopiSenpai** [comment]
Access the guild via the state and loop over all voice states
Then you can count the voice states which have the same channel Ids as your channel

Next time open a discussion instead
