### ISSUE TITLE
ApplicationCommand missing fields

### ISSUE THREAD

**Issue by JABirchall** [bwmarrin/discordgo#1202]
DiscordGo v0.25 is missing fields for ApplicationCommands documented here: https://discord.com/developers/docs/interactions/application-commands#application-command-object

- `default_member_permissions` - Implemented on `master`
- `dm_permission` - Implemented on `master`
- `guild_id`

`default_permissions` will soon be removed infavor of `default_member_permissions`.
Registering commands via the guilds endpoint will soon be depricated infavor of restricting a command to a guild on the ApplicationCommand object

**Comment by SiirRandall** [comment]
Having the same issues with the examples. 
ApplicationCommandPermissionTypeChannel not declared by package discordgocompiler[UndeclaredImportedName](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#UndeclaredImportedName)

**Comment by FedorLap2006** [comment]
> Having the same issues with the examples. `ApplicationCommandPermissionTypeChannel` not declared by package `discordgo` compiler [UndeclaredImportedName](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#UndeclaredImportedName)

Permissions aren't released yet. To use them you can use the `master` branch however:
```
go get github.com/bwmarrin/discordgo@master
```

**Comment by FedorLap2006** [comment]
> DiscordGo v0.25 is missing fields for ApplicationCommands documented here: https://discord.com/developers/docs/interactions/application-commands#application-command-object
> 
> * `default_member_permissions` - Implemented on `master`
> * `dm_permission` - Implemented on `master`
> * `guild_id`
> 
> `default_permissions` will soon be removed infavor of `default_member_permissions`. Registering commands via the guilds endpoint will soon be depricated infavor of restricting a command to a guild on the ApplicationCommand object

Sorry for a late response, can you link the documentation/changelog on where the "registering commands via ..." behaviour is described. Can't seem to find it anywhere.

**Comment by JABirchall** [comment]
It has yet to be announced. Its been discussed to remove duplicate endpoints.
