### ISSUE TITLE
Utility function for extracting a slice of mentions in a message

### ISSUE THREAD

**Issue by Neo-Desktop** [bwmarrin/discordgo#1209]
I'm looking for a utility function that allows the programmer to easily parse a slice of mentions in a message.

My use-case is for a bot to act on multiple users, roles, and channels in a single command; therefore not having to parse out the snowflakes myself would be wonderful.

I'm imagining a Mentionable interface that can be satisfied by a User, Role, or Channel and a function that returns []Mentionable

The end-user implementation could use a type assertion to determine what type of mention was acquired.

Here's a minimal working sample: https://goplay.tools/snippet/NJxd-x5_Znw

Thanks!

**Comment by JABirchall** [comment]
Multiple things with this, 
1. discordgo is designed to a 1-2-1 interface with the discord API and websocket. helper functions like these would fall onto the developer, or a wrapper to impliment.
2. Slash commands solve this problem you can define a command which accepts a mentionable paramter, and in the interaction you will receive will have the object of that type. https://github.com/bwmarrin/discordgo/blob/master/interactions.go#L57-L69

**Comment by Neo-Desktop** [comment]
Ah okay - I misunderstood the scope of DiscordGo 

No worries, thanks for the heads up!
