### ISSUE TITLE
Components example does not run As-Is

### ISSUE THREAD

**Issue by ChristianPerez34** [bwmarrin/discordgo#1218]
Noticed that the [components example](https://github.com/bwmarrin/discordgo/blob/master/examples/components/main.go) does not run as is. 

All references of 
```go 
Flags:   discordgo.MessageFlagsEphemeral
```
 needs to be cast to uint64
```go 
Flags:   uint64(discordgo.MessageFlagsEphemeral)
```

Error message: `Cannot use 'discordgo.MessageFlagsEphemeral' (type MessageFlags) as the type uint64`

Go Version: **go1.19 windows/amd64**

**Comment by FedorLap2006** [comment]
Examples use master branch as the version (`@master`). `Flags` were made `discordgo.MessageFlags` only there, and were not tagged yet. This works as intended.
