### ISSUE TITLE
examples/{airhorn, pingpong, dm_pingpong}: `os.Kill` cannot be trapped

### ISSUE THREAD

**Issue by DanielRamp** [bwmarrin/discordgo#1219]
I got the warning/error`os.Kill cannot be trapped (did you mean syscall.SIGTERM?) (SA1016)` from `go-staticcheck` and then I found #706 which solves the "problem".
But it isn't merged as it's not based on the `develop` branch.

Somehow I can't find a develop branch, so maybe [this pr](#706) can be looked again.
Or how should a contribution be made?
_I read [`README.md#Contributing`](https://github.com/bwmarrin/discordgo/blob/c0803d021f34d62843a51c17984bac72bf1e9182/README.md#contributing) but can't find out what he should have been done better._

_of course feel free to mark this as closed if it's a too issue or move it to discussions_

**Comment by FedorLap2006** [comment]
Sorry for such a late response. Just simply create a pull request with those changes.
