### ISSUE TITLE
Creating commands with options doesn't work

### ISSUE THREAD

**Issue by phyce** [bwmarrin/discordgo#1224]
When using the following example from the Wiki:
https://github.com/bwmarrin/discordgo/wiki/FAQ#options
Nothing happens. No command gets created, no error gets thrown. Is this now outdated?
Same problem happens with the subcommands example:
https://github.com/bwmarrin/discordgo/wiki/FAQ#subcommands section
Creating a command without options works fine.

**Comment by FedorLap2006** [comment]
Have you checked the error `ApplicationCommandCreate` or `ApplicationCommandBulkOverwrite` returned?
If so, what does it say?

**Comment by FedorLap2006** [comment]
As for the example, yes, it doesn't work as `rick astley` isn't a valid option name.
Should be fixed now

**Comment by FedorLap2006** [comment]
Also, sorry for closing the issue, thought the problem was only in the "options" example.

**Comment by phyce** [comment]
I don't know what the hell I was doing last night, but I definitely wasn't checking for errors.
The subcommands example is working fine now. I think I might have hit the daily 200 command creation limit yesterday.
I am however getting the following error returned from ApplicationCommandCreate when running the options example:
`HTTP 400 Bad Request, 
{
	"code": 50035, 
	"errors": {
		"options": {
			"0": {
				"description": {
					"_errors": [
						{"code": "BASE_TYPE_REQUIRED", "message": "This field is required"}
					]
				}
			}
		}
	},
	"message": "Invalid Form Body"
}`
The option description field is required. I have updated the wiki example to avoid this error.
Many thanks for the quick reply!
