### ISSUE TITLE
import cycle not allowed

### ISSUE THREAD

**Issue by fgsoftware1** [bwmarrin/discordgo#1229]
[Error - 23:32:27] 2022/08/17 23:32:27 command error: err: exit status 1: stderr: package github.com/bwmarrin/discordgo
	imports github.com/bwmarrin/discordgo: import cycle not allowed

**Comment by FedorLap2006** [comment]
What version of DiscordGo you're using.
And can you show your `go.mod` file?

**Comment by fgsoftware1** [comment]
> What version of DiscordGo you're using. And can you show your `go.mod` file?

fixed!
dicordgo was on modules instead of required
