### ISSUE TITLE
it's possible to auto assign a memmber role?

### ISSUE THREAD

**Issue by fgsoftware1** [bwmarrin/discordgo#1231]
it's possible to assign a role when member join?

**Comment by Nv7-GitHub** [comment]
Create a handler for the `GuildMemberAdd` event and in that handler, give the user joined a role using the `GuildMemberRoleAdd` function.

**Comment by fgsoftware1** [comment]
> Create a handler for the `GuildMemberAdd` event and in that handler, give the user joined a role using the `GuildMemberRoleAdd` function.

how i get/set roles on roles array?

**Comment by Nv7-GitHub** [comment]
the `Session` object you are provided in a handler has a `GuildMemberRoleAdd` method, in which you provide the guild ID and member ID (which you can get from the event) and the ID of the role (which can be inputted by the user or created by the bot). 

To give the user a role, call this method.
