### ISSUE TITLE
Unable to Unmarshal Modal Submit Data

### ISSUE THREAD

**Issue by ankurpalmia** [bwmarrin/discordgo#1232]
When submitting a modal, we receive an InteractionCreate event with [following data](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-modal-submit-data-structure):
```
"custom_id": String,
"components": Array of message components
```

This data is unmarshalled using the following struct present in `interactions.go`
```
// ModalSubmitInteractionData contains the data of modal submit interaction.
type ModalSubmitInteractionData struct {
	CustomID   string             `json:"custom_id"`
	Components []MessageComponent `json:"-"`
}
```

Here, the json for `Components` is `-`, due to which the Components array becomes empty after unmarshalling.

This needs to be updated by changing `"-"` to `"components"`.

**Comment by FedorLap2006** [comment]
This is intentional. Since `MessageComponent` is an interface, and `encoding/json` does not unmarshal into interfaces,
`ModalSubmitInteractionData` has a custom `UnmarshalJSON` function, which unmarshals the `Components` properly.
