### ISSUE TITLE
Update Go version

### ISSUE THREAD

**Issue by wperron** [bwmarrin/discordgo#1242]
The current Go version is 1.13, it would be interesting to target a newer version (>=1.18) to be able to make use of new features and improvements to the language.

**Comment by fsandov** [comment]
+1

**Comment by VILJkid** [comment]
Yes. There might be some breaking changes with this update, however, with latest Go, there's a high chance code's performance will improve.

**Comment by FedorLap2006** [comment]
After a lot of consideration, we'll probably stick to 1.13, for compatibility and because generics will just make more mess out of our code style and introduce a lot of breaking changes.

We might be bumping the versions to 1.17+ in the near future, however, that's not certain.
