### ISSUE TITLE
Allow any protocol in the URL for button components

### ISSUE THREAD

**Issue by vikpe** [bwmarrin/discordgo#1248]
Using non http protocol in the Button URL results in error (`The application did not respond`).

**Example**
```go
discordgo.Button{
  Label: "FTP link",
  Style: discordgo.LinkButton,
  URL:   "ftp://foo.bar:21",
},
```

**Comment by TopiSenpai** [comment]
This is a discord limitation. Check the returned error for an error message

**Comment by vikpe** [comment]
Roger. thanks
