### ISSUE TITLE
Message Content on Create is empty.

### ISSUE THREAD

**Issue by DiamondRoPlayz** [bwmarrin/discordgo#1265]
When i send a message in my server and the bot receives it, the Content of Message is empty/black
![image](https://user-images.githubusercontent.com/61511674/197695359-20176efc-65c5-4a70-98ce-244e77e53e4a.png)
![image](https://user-images.githubusercontent.com/61511674/197695416-3b305218-17d4-4bf3-975a-279b4793ebab.png)

**Comment by FedorLap2006** [comment]
> Make sure to enable the message intent in the developer dashboard

You're not wrong, however, in the future, we'll require adding `discordgo.IntentMessageContent` to the intent list, as we'll be eventually migrating to v10.

**Comment by DiamondRoPlayz** [comment]
> Make sure to enable the message intent in the developer dashboard

Yeah that was the problem.
