### ISSUE TITLE
Regexp for matching Emoji supports only IDs of length 18

### ISSUE THREAD

**Issue by unkn0wncode** [bwmarrin/discordgo#1267]
Current regexp in the https://github.com/bwmarrin/discordgo/blob/afab84009be89bd6e793dafea88a6acd89f34df9/structs.go#L511
matches only IDs of len 18 while they are longer nowadays, as result of that regexp doesn't detect some emojis as valid.
I suggest to change current regex to `<(a|):[A-z0-9_~]+:\d{18,}>` to prepare it for further changes with IDs aswell as keeping the compatibility with the current code.

**Comment by FedorLap2006** [comment]
After thinking more about this, I don't think making it {18,}` would make much sense, as the absolute maximum to the `uint64` is 20 symbols long (if I'm not mistaken). Therefore the ideal expression, which would accept all snowflake ids would be:
```go
EmojiRegex = regexp.MustCompile(`<(a|):[A-z0-9_~]+:[0-9]{18,20}>`) 
```
