### ISSUE TITLE
InviteCreate event not work

### ISSUE THREAD

**Issue by jianglijie** [bwmarrin/discordgo#1279]
···
s.Identify.Intents = discordgo.IntentsAll
func invite(s *discordgo.Session, g *discordgo.InviteCreate) {
	fmt.Println("invite", g)
}
s.AddHandler(invite)
···
I want to know who invite new user into guild  and add code for the example.  It not work , how can I do it?

**Comment by pixelrazor** [comment]
Please include more information; are you not getting the event at all? Have you tried to enable the debug logging?

**Comment by Nv7-GitHub** [comment]
Do you have the intent

**Comment by pixelrazor** [comment]
> Do you have the intent

They have IntentsAll which should include the invite intent

**Comment by jianglijie** [comment]
> Please include more information; are you not getting the event at all? Have you tried to enable the debug logging?

I think I may have found the reason.   InviteCreate event trigger when new invite code create.  Instead of clicking the invitation page every time.   

But I want to know who invite new user into guild or channel.  Can I do it?   I cant find the inviter info with guildmemberadd 
  enent . For example : user A  invite user B into guild or channel.  How can I get inviter (user A) when user B join guild

**Comment by pixelrazor** [comment]
> > Please include more information; are you not getting the event at all? Have you tried to enable the debug logging?
> 
> I think I may have found the reason.   InviteCreate event trigger when new invite code create.  Instead of clicking the invitation page every time.   
> 
> But I want to know who invite new user into guild or channel.  Can I do it?   I cant find the inviter info with guildmemberadd 
>   enent . For example : user A  invite user B into guild or channel.  How can I get inviter (user A) when user B join guild

Yes, it's only when the invite code is created. The guild member join event contains no information about the invite used either. You could keep track of the invites a guild has, then when a member joins you can compare the current invites with the previous state. If the usage of an invite has increased, or an invite code is gone, that's reasonable enough to determine. I have a bot that does that without using the invite create/delete events, and I'm in progress of migrating to using these events to hopefully be more accurate. I'll drop links here when I'm at my computer tomorrow, and if I do it soon, when I update to use the events.

**Comment by FedorLap2006** [comment]
It seems original issue was resolved, I'm going to close this now.
