### ISSUE TITLE
"state cache not found" when using UserChannelPermissions

### ISSUE THREAD

**Issue by hasevraqyl** [bwmarrin/discordgo#1284]
technically an exact duplicate of [this](https://github.com/bwmarrin/discordgo/issues/876) issue, as both the code and the problem are the same. however, the solution suggested (switching to using a different function that engages with the message instead of the user) is unsuitable in my case. i see [yet another issue](https://github.com/bwmarrin/discordgo/issues/981) also referring to that one, but it's a bit unclear and there's been no response.

my problem is that the following code
```
state := discordgo.NewState()
state.TrackChannels, state.TrackMembers = true, true
permissions, err := state.UserChannelPermissions(k, m.ChannelID)
```
and variations on it involving different sets of booleans all result in a "state cache not found" error. for the record, I do have the correct Intents set and do have the boxes for priveleged intents checked in the app itself. so what might be the problem and what do i do?

edit: "k" is UserID

**Comment by Nv7-GitHub** [comment]
Have you received the `Ready` event before doing this?

**Comment by hasevraqyl** [comment]
well, as far as I know, `session.Open` only releases when `Ready` is received. so, uh, yeah, i have to be, unless I am wrong

**Comment by Nv7-GitHub** [comment]
Oh wait, you're making a new state. I thought you use `Sesion.State.<method>`?

**Comment by hasevraqyl** [comment]
what for? I assumed NewState creates the (empty) state. I don't think I quite understand what you mean, could you perhaps point me to the function you are talking about in the documentation?

**Comment by FedorLap2006** [comment]
`Session` has it's own `State`, that is initialized when you call `discordgo.New`.
You're, by the looks of it, creating a separate state, which isn't used by the session. Therefore, you either have to manually add stuff there. Only `Session.State` would be automatically populated
