### ISSUE TITLE
Role event is not coming 

### ISSUE THREAD

**Issue by Sandeep-Narahari** [bwmarrin/discordgo#1288]
```go
func RoleEvent(s *discordgo.Session, e *discordgo.GuildRoleCreate) {	
	fmt.Println(e.Role.ID)
}
```

I am trying to listen when the new role is created from the discord server app  please help me
Thank you

**Comment by FedorLap2006** [comment]
To listen for created roles, you have to register the handler you have included. You can do that by calling `s.AddHandler`, before `Open`ing the session.

**Comment by Sandeep-Narahari** [comment]
yes I have registed the handler 
bot.RoleEvent(mybot)

**Comment by Sandeep-Narahari** [comment]
Got solved by enabling intent |= thank you Community
