### ISSUE TITLE
error opening connection, websocket: close 4004: Authentication failed.

### ISSUE THREAD

**Issue by fgsoftware1** [bwmarrin/discordgo#1300]

**Comment by FedorLap2006** [comment]
Can you provide more information and how you are providing the token?
Quite possibly, you could have also forgotten to add `Bot ` before the token.

**Comment by fgsoftware1** [comment]
> Can you provide more information and how you are providing the token? Quite possibly, you could have also forgotten to add `Bot ` prefix.

this worked, ty.

**Comment by aswralm** [comment]
Error opening connection:  websocket: close 4004: Authentication failed

**Comment by fgsoftware1** [comment]
> Error opening connection: websocket: close 4004: Authentication failed

as @FedorLap2006 mentioned above, you need to put Bot prefix on your token
