### ISSUE TITLE
Can't access voice states

### ISSUE THREAD

**Issue by User9684** [bwmarrin/discordgo#1358]
Hi, I'm trying to make a bot that tracks voice states, but I can't seem to get them.

This is the following code used to create my client:
```go
	// Create bot client
	session, err := discordgo.New(os.Getenv("TOKEN"))
	if err != nil {
		fmt.Println("error creating Discord session,", err)
		return
	}
	// Register intents
	session.Identify.Intents |= discordgo.IntentGuilds
	session.Identify.Intents |= discordgo.IntentGuildPresences
	session.Identify.Intents |= discordgo.IntentGuildMembers
	session.Identify.Intents |= discordgo.IntentGuildVoiceStates

	// Setup state
	session.StateEnabled = true
	session.State.TrackChannels = true
	session.State.TrackMembers = true
	session.State.TrackVoice = true
	session.State.TrackPresences = true

	s = session
```
And this is the code I am trying to run:
```go
guildID := fmt.Sprintf("%v", optionMap["guild"])
		userID := fmt.Sprintf("%v", optionMap["user"])

		memberState, err := s.State.VoiceState(guildID, userID)
		if err != nil {
			cmdError(i, err)
			return
		}

		fmt.Println(memberState)
```
yet for some reason, I always get the error `state cache not found`

Any reason why? I tried looking at other issues that had the same error, but I couldn't find anything.

**Comment by User9684** [comment]
Yknow, it helps to read my own code before posting an issue. I forgot to add `.Value`.

**Comment by kreimben** [comment]
Would you mind let me know where did you add `.Value`?

**Comment by User9684** [comment]
This code came from a slash command, I added `.Value` to `optionMap["guild"]` and `optionMap["user"]`

**Comment by kreimben** [comment]
aha, Thanks
