### ISSUE TITLE
`ApplicationCommandInteractionData.Type()` always return 2 even it's not user command

### ISSUE THREAD

**Issue by buratud** [bwmarrin/discordgo#1359]
Per [interaction structure document](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-structure), the `data.type` suggests that the field is for "the type of the invoked command" which is an application command type and can be refers [here](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-types). This is different from top level `type` which is refered to [interaction type](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-type).

An example of message command can be found [here](https://discord.com/developers/docs/interactions/application-commands#message-commands-example-interaction), notice that `type` is 2 but `data.type` is 3 (`MESSAGE`).
Another example of [slash command](https://discord.com/developers/docs/interactions/application-commands#slash-commands-example-interaction) which the `data.type` is 1 (`CHAT_INPUT`).

However, when I handle interaction command (using `*discordgo.InteractionCreate`) and call `Interaction.Type` and `ApplicationCommandInteractionData.Type()`, both always return 2 which is correct for `Interaction.Type` but incorrect for `ApplicationCommandInteractionData.Type()` which is supposed to return 1 for `CHAT_INPUT` and 3 for `MESSAGE`.

I made a brief [example repository](https://github.com/buratud/discordgo-issue-1359), it will return  `Interaction.Type` and `ApplicationCommandInteractionData.Type()` when it receives application command.

Video demostration of the bot above:
https://user-images.githubusercontent.com/62024314/230704444-3353a21e-35ba-48d4-8d70-fb8c90e59dcf.mp4

**Comment by tckthecreator** [comment]
Yes, because it is returning the type of the Interaction. It needs to get the field type of https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-data
