### ISSUE TITLE
discord bot connect to discord 1000 times within a short time

### ISSUE THREAD

**Issue by dianbanjiu** [bwmarrin/discordgo#1360]
I created a slash command like the [slash command example](https://github.com/bwmarrin/discordgo/tree/master/examples/slash_commands), but i got `discord bot connect to discord 1000 times within a short time` everyday. And then discord will force reset the bot token.

Is there have any way to solve it, or can do some limit?

**Comment by AleDema** [comment]
How did you manage to solve the issue? Was it something in your code or in the library's?

**Comment by dianbanjiu** [comment]
@AleDema I have some problems with the project design. My project contains a cli program using cron, because this cli program will also reconnect to discord when it starts.😅

**Comment by AleDema** [comment]
@dianbanjiu Does the cron job run more than 1k times a day?

**Comment by dianbanjiu** [comment]
Yes, this scheduled task will run every few minutes, and the connection will be reinitialized every time it is run.
