### ISSUE TITLE
message.Content always empty?

### ISSUE THREAD

**Issue by xKaOz** [bwmarrin/discordgo#1369]
after trying some stuff with my bot i noticed in my message handler it wasnt functioning i was confused to why, i remove my code and print message.Content and its always empty?

**Comment by Roolps** [comment]
Are you using func(s *discordgo.Session, m *discordgo.MessageCreate) as your handler?
If so make sure you have enabled message content intent in your discord developer portal. If you click on your app, then click on bot, it should be the last option before the permission calculator. 
<img width="1279" alt="Scherm­afbeelding 2023-04-23 om 08 28 09" src="https://user-images.githubusercontent.com/87721861/233826119-72fdb664-e569-4819-a4b4-82b1e9ace19b.png">

**Comment by xKaOz** [comment]
thank you, the func was right, but message intents was off, I’m really sorry 😅

**Comment by Roolps** [comment]
No problem :) glad I could help!
