### ISSUE TITLE
Type Member.Roles returns a string array

### ISSUE THREAD

**Issue by Rivalo** [bwmarrin/discordgo#137]
Currently the struct Member has a field 'Roles' that returns type `[]string`
I think the return of type `[]Role` would be better here, or is there an API limitation that prevents this?

**Comment by iopred** [comment]
This is what the API returns. It's a list of role ID's you need to actually grab the roles from

s.State.Guild(guildID).Roles

**Comment by Rivalo** [comment]
Thank you!

//offtopic
But that means that the official client has to check for every message the roles in its state. That's looks not very efficient, or it is some ReactJS state magic :-)

**Comment by iopred** [comment]
They probably put the roles in the equivalent of a `map[string]*Role`, very efficient to grab a role that way.
