### ISSUE TITLE
Wait until voice channel is ready

### ISSUE THREAD

**Issue by noisypixy** [bwmarrin/discordgo#138]
I was reading [bwmarrin/dca](https://github.com/bwmarrin/dca)'s example, when I notice [this](https://github.com/bwmarrin/dca/blob/68e1de349408e058e991478c07d264b1920ab9aa/example/main.go#L54-L58):

```go
// Hacky loop to prevent sending on a nil channel.
// TODO: Find a better way.
for discord.Voice.Ready == false {
	runtime.Gosched()
}
```

If some changes are made to the `Voice` struct, users wouldn't have to worry about that part. For example:

```go
type Voice struct {
	// ...

	ready         chan bool   // This should be re-initialized (or set to nil) every time Ready changes from true to false.
	readyMutex    *sync.Mutex // Make sure to initialize this.
	watchingReady bool        // true when a goroutine is watching the value of ready.
}

// Wait blocks until voice channel is ready.
func (v *Voice) Wait() {
	v.readyMutex.Lock()

	if v.ready == nil {
		v.ready = make(chan bool)
	}

	// Only spawn one watcher goroutine.
	if !v.watchingReady {
		v.watchingReady = true

		go func() {
			for v.Ready == false {
				runtime.Gosched()
			}

			v.readyMutex.Lock()
			defer v.readyMutex.Unlock()

			v.Ready = true
			v.watchingReady = false
			close(v.ready)
		}()
	}

	v.readyMutex.Unlock()

	<-v.ready
}
```

Now users can just call `discord.Voice.Wait()`. If the voice channel is ready, it should return immediately; otherwise, it should block until it's ready.

Moving the "hacky loop" to the library simplifies end-user code and, if a better way is found, internals can be changed without affecting the public interface.

---

NOTE: I haven't tested that code, and I'm not familiarized enough with the library to know if that's the right way to do it.

---

EDIT: I think I should have posted this in #129.

**Comment by bwmarrin** [comment]
Oh man I totally forgot about this issue otherwise I would have made some comments.  Last 20 days have been kind of crazy for me :(.  Anyhow, I'm guessing you closed this because you noticed that now the ChannelVoiceJoin func embeds the wait inside of itself.

**Comment by noisypixy** [comment]
No problem, this was a minor issue anyway. And looking at the accepted solution, I feel like an idiot for posting that over-complicated snippet xD.
