### ISSUE TITLE
Missing global_name on User struct

### ISSUE THREAD

**Issue by emir** [bwmarrin/discordgo#1398]
Hello👋 

First of all, I would like to express my gratitude to everyone who contributed to discordgo and maintained the project.

In a project I've developed, I needed to get the full name of the user. I saw that it returns as [global_name in Discord's documentation](https://discord.com/developers/docs/resources/user#user-object), but it wasn't in discordgo's User struct. I looked through the Issues, Discussions sections and searched under the discordgo channel on the Discord Go server but I couldn't see any result related to this.

I opened a PR for this #1397 and kindly ask you to review it.

Thanks!

**Comment by Aldiwildan77** [comment]
This is already mentioned in this issue https://github.com/bwmarrin/discordgo/issues/1386

**Comment by emir** [comment]
> This is already mentioned in this issue #1386

Oh sorry, I didn't see that issue contained this. I guess it's resolved and waiting for merge? I'm closing this.
