### ISSUE TITLE
Adding button to Session.ChannelMessageSend 

### ISSUE THREAD

**Issue by ikuruzum** [bwmarrin/discordgo#1436]
how can i do that , is it only for slash command responses?

Seeing that other people's discussion has not been answered for a long time, I felt the need to write here as well.

**Comment by FedorLap2006** [comment]
It is not reserved only for slash commands. You can use the `Components` field in `InteractionResponseData`/`MessageEdit`/`MessageSend` to add them.

```go
session.ChannelMessageSendComplex(channelID, &discordgo.MessageSend {
  Components: []discordgo.MessageComponent{
    discordgo.ActionsRow {
      Components: []discordgo.MessageComponent{
        discordgo.Button {...},
      },
    }
  },
})
```
