### ISSUE TITLE
guild members

### ISSUE THREAD

**Issue by kehiy** [bwmarrin/discordgo#1450]
I'm trying to get `guild.Members` but I get this:

```
2023/09/17 22:36:53 error get discord users: HTTP 403 Forbidden, {"message": "Missing Access", "code": 50001}
exit status 1
```

code:
```go
	members, err := disBot.GuildMembers(GUILD_ID, "", 1000)
	if err != nil {
		log.Fatalf("error get discord users: %v", err)
	}
```

(I should mention that the bot is in the server and has admin permissions)

**Comment by FedorLap2006** [comment]
Are you sure `GUILD_ID` isn't empty and has the id of the server you've mentioned?

**Comment by kehiy** [comment]
@FedorLap2006 yes, this stuff is all correct!
