### ISSUE TITLE
Sending local file as a message response

### ISSUE THREAD

**Issue by bilegg** [bwmarrin/discordgo#1451]
As described in the title I'm wondering if there is a way to send local file as a response in the same way as it's possible to be done with discordjs's **AttachmentBuilder**.

I noticed there is a **MessageAttachment** type allowing for embedding files but from the docs**Interaction** does not have such a field?

Sorry if it's a duplicate but I could not find any post/issue talking about embedding local files in slash command response

**Comment by FedorLap2006** [comment]
You've probably confused the types. `Interaction` is used when receiving interaction, `InteractionResponse` when sending.
To send a local file, you simply need to assign an entry of `InteractionResponse.Data.Files` to its data.

```go
r, err := os.ReadFile("assets/discordgo.png")
if err != nil {
    panic(err)
}

err = s.InteractionRespond(i.Interaction, &discordgo.InteractionResponse {
    Files: []*discordgo.File {
       {Name: "discordgo.png", ContentType: "image/png", Reader: r},
    },
})

if err != nil {
    panic(err)
}
```
