### ISSUE TITLE
Discord server down and panic alert at `Session.Open()`

### ISSUE THREAD

**Issue by raccoon-pi** [bwmarrin/discordgo#1453]
I tested it around 8 p.m. on Friday, September 29th in Seoul time. I think a Discord server error has occurred.

An error that did not occur in` Session.Open()` occurs when accessing `Session.State.User.String().`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x693bce]
```

Is there a way to detect errors in `Session.Open()` in advance?

**Comment by FedorLap2006** [comment]
Are you accessing `Session.State.User` after the `Ready` event? If not, it's expected for the state to not be populated.

**Comment by raccoon-pi** [comment]
@FedorLap2006 
Thank you very much for your help.
I don't know exactly why, but the Discord text conversation had a brief error. There seems to have been a problem with the service in Korea.

All functions are working normally now.
Thanks once again.
