### ISSUE TITLE
[Question] InteractionDeadline giving me timeouts in my commands response

### ISSUE THREAD

**Issue by ViliNeto** [bwmarrin/discordgo#1459]
Hey,
I noted that my slash command for an integration that I have is taking more than 3s in general.
I'd like to know if I'm able to increase the timeout for this type of interaction, at least to 15 seconds.

I noted that the lib has InteractionDeadline config setup to 3s.

Is there a way to change this on my code? 

https://github.com/bwmarrin/discordgo/blob/1f0b57f110241f1edff78d639cdb36885aeb7e1d/interactions.go#L17

**Comment by avislash** [comment]
The 3 second response time enforced by Discord on the server side. You need to send an ack and then can post a follow up. 

Here is an example: https://github.com/avislash/nftstamper/blob/main/cartel/bot.go#L244

**Comment by ViliNeto** [comment]
Thank you for the promp response.
