### ISSUE TITLE
Error creating message components without emojis

### ISSUE THREAD

**Issue by TheGrandPackard** [bwmarrin/discordgo#1474]
Starting today (few hours ago), I was having issues with my bot creating embeds that did not have emjois defined on the components. It appears that Discord changed their API to require the emoji field to be omitted when it is not populated, instead of an empty struct with no fields.

Error message:
```HTTP 400 Bad Request, {"message": "Invalid Form Body", "code": 50035, "errors": {"components": {"0": {"components": {"0": {"emoji": {"name": {"_errors": [{"code": "BUTTON_COMPONENT_INVALID_EMOJI", "message": "Invalid emoji"}]}}}}}}}}```

I forked this and confirmed that this fixes my issue and will create a PR for consideration or reference to fix in a larger batch of fixes.

**Comment by caibirdme** [comment]
same issue, can we create a new tag for this fix?

**Comment by FedorLap2006** [comment]
I'm currently preparing a release, however it won't be out for at least a few days. So if you need it asap, you can use the `@master` revision. It shouldn't have any major breaking changes.
