### ISSUE TITLE
Update v0.27.1 -> v0.27.2

### ISSUE THREAD

**Issue by servusdei2018** [bwmarrin/discordgo#1480]
Hi, due to the recent releases of v0.24.2, v0.25.2 and v0.26.3, could v0.27.1 also be updated to v0.27.2 with the fixes for unomitted empty `Emoji` fields in `SelectMenuOption` and `Button` structs?

Thank you!

**Comment by FedorLap2006** [comment]
We've decided against that, as we're currently preparing v0.28.0, and the breaking changes for v0.27.0 to v0.28.0 transition would be minimal.

**Comment by servusdei2018** [comment]
Understood, thanks! I'm excited for v0.28.0 😄
