### ISSUE TITLE
Can't add SUPPRESS_EMBED flag to other user's message

### ISSUE THREAD

**Issue by SamusAranX** [bwmarrin/discordgo#1484]
I have a code snippet in my messageCreate handler like this:

```go
edit := discordgo.NewMessageEdit(messageCreate.ChannelID, messageCreate.ID)
edit.Flags = messageCreate.Flags | discordgo.MessageFlagsSuppressEmbeds
_, err := session.ChannelMessageEditComplex(edit)
if err != nil {
	return err
}
```

and while this should work according to [Discord's documentation](https://discord.com/developers/docs/resources/channel#edit-message), this keeps failing with the following error message:

> HTTP 403 Forbidden, {"message": "Cannot edit a message authored by another user", "code": 50005}

Did I miss anything? Is there another way to apply the embed suppression flag to someone else's message while not touching anything else?

**Comment by FedorLap2006** [comment]
You did not. `Components` and `Embeds` are the culprit here. When making request they're not omitted.
![image](https://github.com/bwmarrin/discordgo/assets/42876964/ed34dc1b-6ab3-44fc-93bf-2449299a8686)
