### ISSUE TITLE
How do I use `Interaction.Message` in a slash command?

### ISSUE THREAD

**Issue by XangelMusic** [bwmarrin/discordgo#1486]
I'm trying to create a slash command that gets the attachments of a message the interaction is used on.

`Interaction.Message` however says "this field is only filled when a button click triggered the interaction. Otherwise it will be nil." which seems to be the case whenever I use the command on a message.

How do I then get a message and all its data with a slash command?

**Comment by bshore** [comment]
Assuming you're following the example case here - https://github.com/bwmarrin/discordgo/blob/master/examples/slash_commands/main.go

I just encountered this with my Discord Bot and here's what I ended up having to do:

1. Set up the slash command to accept an option
```go
commands := []*discordgo.ApplicationCommand{
	{
		Name:        "respond",
		Description: "example command with a message option",
		Options: []*discordgo.ApplicationCommandOption{
			{
				Type:        discordgo.ApplicationCommandOptionString,
				Name:        "message",
				Description: "The message to respond with",
				Required:    true,
			},
		},
	},
}
```
2. Where you handle your interaction, the message is part of the interaction struct:
```go
commandHandlers = map[string]func(s *discordgo.Session, i *discordgo.InteractionCreate){
	"respond": func(s *discordgo.Session, i *discordgo.InteractionCreate) {
		// commandData has all the stuff captured by the command interaction
		commandData := i.ApplicationCommandData()

		// option '0' here is the 'message' option defined above
		message := commandData.Options[0].StringValue()

		 // do something with 'message' i.e. look up info, call other apis, etc.

		s.InteractionRespond(i.Interaction, &discordgo.InteractionResponse{
			Type: discordgo.InteractionResponseChannelMessageWithSource,
			Data: &discordgo.InteractionResponseData{
				Content: fmt.Sprintf("the bot handled the message: %s", message),
			},
		})
	},
}
```
3. Should get you a slash command something like this within Discord:
![image](https://github.com/bwmarrin/discordgo/assets/14914028/1debfa6a-b9cf-4646-b2f8-f1d2174b2e0c)

**Comment by XangelMusic** [comment]
This is what I was looking for, thank you. I was definitely looking in the wrong place, I was supposed to look at the Context Menus example. I confused myself thinking the Context Menu command was the same as a Slash Command.
