### ISSUE TITLE
When editing a message, does it support changing the message to be visible only to the current user?

### ISSUE THREAD

**Issue by houxul** [bwmarrin/discordgo#1490]
```
       msgEdit := &discordgo.MessageEdit{
		Channel: message.ChannelId,
		ID:      message.MessageId,
		Content: &content,
		Flags:   discordgo.MessageFlagsEphemeral,
	}
	_, err := s.sess.ChannelMessageEditComplex(msgEdit)
```
Call the above code and set Flags to discordgo.MessageFlagsEphemeral, when the message has not changed to be visible only to the current user.
The following is the definition of MessageFlagsEphemeral.
https://github.com/bwmarrin/discordgo/blob/master/message.go#L212-L213

**Comment by FedorLap2006** [comment]
`MessageFlagsEphemeral` cannot be set when editing a message. In addition to that it is only available when responding to an interaction.
