### ISSUE TITLE
Webhook functions return `Role` instead of `Webhook`

### ISSUE THREAD

**Issue by Cyb3r-Jak3** [bwmarrin/discordgo#1495]
The functions [WebhookEdit](https://github.com/bwmarrin/discordgo/blob/master/restapi.go#L2273), [WebhookEditWithToken](https://github.com/bwmarrin/discordgo/blob/master/restapi.go#L2296) both return the `Role` struct over the `Webhook` one.

Happy to make a PR for this but wanted to make it was intended for weird reasons beforehand.

**Comment by Earlopain** [comment]
This looks like a bug to me, webhook and roles are not structurally compatible. If you call this method and check the return value, you should see that the fields are default initialized. (I haven't tested this myself).

Docs:
https://discord.com/developers/docs/resources/webhook#modify-webhook
https://discord.com/developers/docs/resources/webhook#modify-webhook-with-token

There are also some missing fields on the webhook struct (last 3 from https://discord.com/developers/docs/resources/webhook#webhook-object) and a missing webhook type Application (3) if you want to do some updates for that in a separate PR.
