### ISSUE TITLE
Get messages/posts of a forum thread

### ISSUE THREAD

**Issue by mlaggner** [bwmarrin/discordgo#1538]
As I found out, we can read messages from a normal (text) channel and there is an endpoint for creating/managing a forum thread - but I miss the endpoint for reading all messages/posts from a forum thread. Is this not implemented or just not possible?

My use case is to dump all messages from a guild forum for an offline backup. My idea is to

- list all channels from the server (done)
- get all messages from _relevant_ channels and dump them to json (done except for forums, where I do not find anything usable in the response from the `discordgo.Session.ChannelMessages` or the channel object `discordgo.Channel` it self

Any help would be highly appreciated

**Comment by FedorLap2006** [comment]
To get a list of forum posts, you can go through [Active Guild Threads](<https://discord.com/developers/docs/resources/guild#list-active-guild-threads>) (keeping only the relevant channel) and [List Public Archived Threads](<https://discord.com/developers/docs/resources/channel#list-public-archived-threads>).

Although please note, as far as I'm aware, keeping data in this way (offline) - will violate Discord's developer ToS. As you need to provide a way for deletion of this data. (I'm not a lawyer though, so please consult folks at [DDevs](https://discord.gg/discord-developers) for this.

**Comment by mlaggner** [comment]
Many thanks.

As I am the main administrator of the discord server and this is a private bot, I do not think that there is any issue according to the ToS. Unfortunately discord itself is not able to offer some sort of disaster recovery (our server has been hacked and completely nuked and discord itself did not help in any way), we need to create our own backups to safe the tons of work we've spent in the content
