### ISSUE TITLE
REST API: support Application emojis

### ISSUE THREAD

**Issue by Big-Iron-Cheems** [bwmarrin/discordgo#1567]
As of now, discordgo's [restapi.go](https://github.com/bwmarrin/discordgo/blob/master/restapi.go#L1394-L1455) supports control of Guild based emojis, but not Application based ones.
The docs related to Guild and Application emojis are located here: https://discord.com/developers/docs/resources/emoji.
I am interested in supporting all the endpoints that begin with `/applications/`.

Screenshot below is from the `https://discord.com/developers/applications/APPLICATION_ID/emojis` page.
![image](https://github.com/user-attachments/assets/2136c25a-9c3f-49a2-b1b5-f0875ddf0b58)

Currently I have written this function in my personal project to GET a specific emoji by ID:
```go
// applicationEmoji fetches an emoji from the application
func applicationEmoji(s *discordgo.Session, applicationID string, emojiID string, options ...discordgo.RequestOption) (emoji *discordgo.Emoji, err error) {
	var body []byte
	body, err = s.RequestWithBucketID("GET", discordgo.EndpointApplication(applicationID)+"/emojis/"+emojiID, nil, discordgo.EndpointApplication(applicationID), options...)
	if err != nil {
		return
	}

	err = discordgo.Unmarshal(body, &emoji)
	return
}

// Example usage in my project
emoji, err = applicationEmoji(s, applicationID, emojiID)
```

I am working on an implementation that is close to the Guild emoji functions.
Progress tracked at [this](https://github.com/bwmarrin/discordgo/pull/1566) PR, suggestions appreciated.

**Comment by elliotwms** [comment]
Closed by https://github.com/bwmarrin/discordgo/pull/1566?

**Comment by Big-Iron-Cheems** [comment]
You're right, forgot to add the `closes` mention in the PR 👍
