### ISSUE TITLE
Add previous channel in VoiceStateUpdate

### ISSUE THREAD

**Issue by IMcPwn** [bwmarrin/discordgo#185]
I would like to be able to know the channel before and after the voice state update as you can in [discord.py](https://github.com/Rapptz/discord.py).

` discord.on_voice_state_update(before, after)`
http://discordpy.readthedocs.io/en/latest/api.html#discord.on_voice_state_update

The discordgo VoiceStateUpdate only contains the current channel
https://godoc.org/github.com/bwmarrin/discordgo#VoiceStateUpdate

**Comment by bwmarrin** [comment]
VoiceStateUpdate is an event fired by Discord.  discordgo only provides a low-level direct bindings for the HTTP API and Gateway API.  So we pass along all the exact data that Discord sends.  Discord doesn't send a "before" state/channel for the user so we can't pass that along.

To know the before channel you would need to monitor all the voice state update events and keep a small cache of that data. Then you would know the "before" channel just by looking at your cache.  Something like a 
```go
var VoiceStateCache map[string]*discordgo.VoiceState
```
Then you could build a map of UserID -> VoiceState

**Comment by IMcPwn** [comment]
I'll check that out. Thanks for the clarification!
