### ISSUE TITLE
Role order causing issues.

### ISSUE THREAD

**Issue by proxikal** [bwmarrin/discordgo#197]
After discord has updated the roles to the new system i am getting constant problems with Echo not having permissions to edit roles (even when he has the required permissions) and even with the Administrator permission. I have to tell people to drag Echo's role to the top of their list. this fixes the issue 100% of the time. I was hoping there was a fix for this.

**Comment by iopred** [comment]
Discord updated their privilege system, there is nothing we can do.

**Comment by proxikal** [comment]
Ah alright, ty!
