### ISSUE TITLE
Parse timestamps

### ISSUE THREAD

**Issue by jonas747** [bwmarrin/discordgo#204]
Right now discordgo does not parse timestamps, and IMO it really should, my proposal is a timestamp struct: 

```go
type Timestamp struct {
	Raw    string
	Parsed time.Time
}

func (t *Timestamp) UnmarshalJSON(data []byte) (err error) {
	if len(data) < 1 { // Not always a timestamp returned
		return
	}
	err = json.Unmarshal(data, &t.Raw)
	if err != nil {
		return
	}

	t.Parsed, err = time.Parse("2006-01-02T15:04:05-07:00", t.Raw)
	return
}
```

Not sure if the raw, unparsed string is needed to be available but yeah
This would break everything using timestamps currently though, but fixes are simple

**Comment by bwmarrin** [comment]
@jonas747 what do you think about the PR from @uppfinnarn  for this? This will allow you to easily get a parse time but also will not cause as much impact on users that do not need/use the timestamp.

**Comment by jonas747** [comment]
Yeah i think it looks good

**Comment by robbix1206** [comment]
It's do some time ago already but I corrected the PR of uppfinnarn.
The timestamp is based on RFC3339 so i change change the custom pattern of uppfinnarn to the RFC3339 pattern.
I tried on "2016-08-15T00:53:06+00:00" and "2006-01-02T15:04:05-07:00" and look that it's work.
Seeing that this is that last milestone of v0.14.0 can we have a new discordgo release please ?
