### ISSUE TITLE
Message.ContentWithMentionsReplaced() replace role and channel mentions.

### ISSUE THREAD

**Issue by VagantemNumen** [bwmarrin/discordgo#208]
Currently `Message.ContentWithMentionsReplaced()` only replaces the User mentions, but not Channel and/or Role mentions.
It maybe nice to have them replaced too.

**Comment by ToadKing** [comment]
`Message.ContentWithMentionsReplaced()` also does not replace user names with their proper guild nickname

**Comment by legolord208** [comment]
Made a pull request for this :stuck_out_tongue:

**Comment by bwmarrin** [comment]
Fixed with https://github.com/bwmarrin/discordgo/pull/375
