### ISSUE TITLE
ChannelFileSend

### ISSUE THREAD

**Issue by VuuI** [bwmarrin/discordgo#209]
How do I use this to make the bot send an image to the channel? I can't for the life of me figure it out

**Comment by iopred** [comment]
session.ChannelFileSend(channel, filename, bufio.NewReader(filename))

**Comment by robbix1206** [comment]
I think we can close this issue.

**Comment by bwmarrin** [comment]
I think you're right!

**Comment by LetsOne** [comment]
ChannelFileSend(channelID, name string, r io.Reader)

Example in case someone needs it. 
```

	            file, err := os.Open("picture.png")
	            if err != nil {
    				log.Fatal(err)
    			}
	            s.ChannelFileSend(channel.ID ,picture.png, file)
	            file.Close()
```
