### ISSUE TITLE
Documentation does not say how to mention a user.

### ISSUE THREAD

**Issue by johncave** [bwmarrin/discordgo#210]
I'm trying to mention the user that triggered my bot's action. Following the syntax auto-generated by the Discord app like @user.Username#user.ID but this is just echoed back exactly by end clients. It's not documented how to mention a user, so I assume it's something really obvious, but I can't for the life of me figure it out.

**Comment by VagantemNumen** [comment]
``<@Message.Author.ID>```

**Comment by uppfinnarn** [comment]
See the Discord API docs: https://discordapp.com/developers/docs/resources/channel#mentions
