### ISSUE TITLE
Live tracking and updating of the LastMessageID toggle option 

### ISSUE THREAD

**Issue by LordFatBastard** [bwmarrin/discordgo#229]
Adding a toggle for the LastMessageID to update to contain the message of the last message that has been posted in real time when a new message is posted.

**Comment by bwmarrin** [comment]
Just to clarify for the future :)  The idea here is to have the State track the last message ID received.  Since this would be a pretty consuming task for many bots it would default to off and be configurable with a bool similar to the other State options.

**Comment by iopred** [comment]
This can be done by setting State.MaxMessageCount to 1, and then checking the id of the only message in State.Channel().Messages.

**Comment by robbix1206** [comment]
@iopred Yes and no i try to code that and the problem is that actually State.Channel().Messages can be nil even if there is message in the channel (when all Message in State.Channel().Messages have been deleted)

**Comment by robbix1206** [comment]
So it does a while but do I need to load messages in the channel to keep tracking LastMessageID in all cases (will be nil if there is no message in the channel)

**Comment by bwmarrin** [comment]
I feel @iopred answer above solves the initial issue request here.  For the secondary one raised here, I'll quote myself from it's PR.
```
I don't feel that this is a good fit for the goals of this library as a minimal wrapper over the Discord API.  Which, I guess is evident by how long it's sat here unmerged. So, I'm going to close it out.  However if anyoen finds this and has a specific need for it feel free to comment on why it's needed.
```
