### ISSUE TITLE
Support getting Bot account / owner

### ISSUE THREAD

**Issue by bwmarrin** [bwmarrin/discordgo#231]
10:32 PM] ⎛⎝xX_jake_Xx⎠⎞: /oauth/applications/@me

For bot users, when calling this endpoint, it will now return the owner of the application in the "owner" key as a user object: {"id": "1234", "username": "bot guy", "discriminator": "1234", "avatar": null}.(edited)

**Comment by robbix1206** [comment]
Issue can be closed PR #231 has been merged.

**Comment by bwmarrin** [comment]
:heart:
