### ISSUE TITLE
Add support for events GUILD_BAN_ADD and GUILD_BAN_REMOVE

### ISSUE THREAD

**Issue by bwmarrin** [bwmarrin/discordgo#24]

**Comment by bwmarrin** [comment]
{"t":"GUILD_BAN_ADD","s":133,"op":0,"d":{"user":{"username":"SomeCoolBot","id":"123487981234723","discriminator":"1234","avatar":null},"guild_id":"81273912873"}}

**Comment by bwmarrin** [comment]
{"t":"GUILD_BAN_REMOVE","s":177,"op":0,"d":{"user":{"username":"SomeCoolBot","id":"123487981234723","discriminator":"8292","avatar":null},"guild_id":"81273912873"}}

**Comment by iopred** [comment]
I was going to take this, but it looks like it's done.

**Comment by bwmarrin** [comment]
It's not done :)  These are the websocket events that get fired when someone is banned/unbanned.  The code that does the actual ban/unban is in restapi.go but this is for an addition to the wsapi.go file in the event func.   So just a new similar block of code as the rest and then creating a struct for both events in structs.go, then adding a user callback func variable to the structs.go Session struct.     

Also, btw - Thanks a lot for all the help.  I owe you a few beers at this point.
