### ISSUE TITLE
Correctly Process Partial Guild Updates

### ISSUE THREAD

**Issue by blackhole12** [bwmarrin/discordgo#242]
When updating a guild, Discord sometimes sends guild updates that are missing members, channels, or roles. To replicate this bug, start a bot that is monitoring the GuildUpdate event, and then change the verification level for a server **twice**. The first change should give you a complete, valid guild update object. The *second* change will result in an update with no members, roles, channels, presences, or voice channels.

Upon calling `fmt.Println(m.Guild)` where m is the GuildUpdate structure, you will get:

    {
    105443346608095232
    Black Sphere Studios
    52441493711153d49459246187db8b6e
    us-west  
    95585199324143616
    300
    2
    false
    false
    0
    [0xc04200be00 0xc04240e400 0xc04240e580]
    []
    []
    []
    []
    []
    <nil>
    }

Calling `fmt.Println(s.Guild(m.Guild.ID))` where s is the discordgo session object yields the exact same result, meaning the internal guild state object has simply set itself to the result of this GuildUpdate, obliterating all of the state.

I attempted to do my own workaround by using `if len(m.Guild.Members) == 0 || len(m.Guild.Channels) == 0`, but while this works for most cases, **it doesn't always work!** There appear to be some edge cases that I cannot replicate that still break the internal state. This means that discord must have sent a guild update packet with a full or partial member list and channel list, but an incomplete or empty role list. I might be able to fix this by appending `len(m.Guild.Roles) == 0` to my check, but while Members and Channels cannot ever be zero in any functional server, it is entirely possible to have zero roles in a valid server, so this check would have false positives. In addition, I have no idea if discord ever sends partial member, channel, or role lists. Further experimentation would have to be done.

My personal recommendation is to treat the guild update as a **union** - if it exists in the guild update, append it or replace it in the old guild state, but _do not delete anything_ from the old guild state. This would fix both this problem and any future problems in case Discord starts sending partial member lists in guild updates.

**Comment by bwmarrin** [comment]
Good catch, and thanks for reporting it.   I agree that we should try to find a way to prevent the State from wiping out data due to Discord sending us a partial object.  I'll try to test this and work on it when I can.

Also, @iopred  :)

**Comment by iopred** [comment]
Heurm, this is what we used to do I believe, I think it got changed when the partial ready change happened, looking into it.

**Comment by iopred** [comment]
@blackhole12 give https://github.com/bwmarrin/discordgo/pull/249 a try, looks good over here.

**Comment by blackhole12** [comment]
@iopred It looks like it should work but i'm not in a position to test it right now.
