### ISSUE TITLE
"Bot" Token Type is Required

### ISSUE THREAD

**Issue by robbix1206** [bwmarrin/discordgo#247]
See https://github.com/hammerandchisel/discord-api-docs/issues/119 for more informations
This change will happen tomorrow.

**Comment by robbix1206** [comment]
We need to precise to users to add `Bot ` suffix before the bot token.

**Comment by bwmarrin** [comment]
Ah.. For some reason I thought that was happening on the 20th.

**Comment by bwmarrin** [comment]
For reference, without any changes you can solve this issue by just passing the token type, as explained here. 

https://github.com/bwmarrin/discordgo/pull/248#issuecomment-244598442

**Comment by dmportella** [comment]
yeah this is an issue now but it is cool i will send a PR soon with a check to add if not present

**Comment by austin1237** [comment]
We might be able to close this now that the docs have been updated?

**Comment by iopred** [comment]
I have also updated all the examples to use "Bot " by default. I'm going to call this one closed.
