### ISSUE TITLE
wsapi.go occasinally shows error

### ISSUE THREAD

**Issue by Ahtram** [bwmarrin/discordgo#269]
I host the pingpong example and these messages just shows sometimes. Don't know if it's a big deal thou.

![2016-10-06 13_14_27-cmder](https://cloud.githubusercontent.com/assets/1751201/19141404/b9f9429c-8bc7-11e6-87f3-0f00951425d8.png)

**Comment by Ahtram** [comment]
btw thanks for making discordgo. Love it.

**Comment by Izacht13** [comment]
Same issue here, not sure why the pipe is breaking...

**Comment by bwmarrin** [comment]
I'm curious, are either of you still having this issue? Many updates have been made over the last few months.  Also make sure you're testing on the develop branch to be sure :)
