### ISSUE TITLE
ChannelVoiceJoin causes bot to reconnect when attempting to join a channel that has users that were connected to the channel prior to the bot starting

### ISSUE THREAD

**Issue by rytone** [bwmarrin/discordgo#286]
[Example program to reproduce](https://gitlab.com/rytone/dgovoicebug)

**Comment by robbix1206** [comment]
I can't reproduce it with the current main commit.
It may had been fixed.

**Comment by bwmarrin** [comment]
@rytone are you still having this problem with the current dev branch?
