### ISSUE TITLE
Make the endpoints for guild icons, splashes, group icons and user avatars use .png

### ISSUE THREAD

**Issue by acdenisSK** [bwmarrin/discordgo#308]

**Comment by acdenisSK** [comment]
Okay seems like the group icon endpoint isn't added.
Gonna add that into the pr for this once i'm done eating dinner.

**Comment by iopred** [comment]
This should be optional, go supports decoding of PNG so webp is less useful.

**Comment by acdenisSK** [comment]
True, even if this is for the higher resolution change anyway.
Although i found that .webp doesn't really work for gif avatars sadly.
*But* we can still add the endpoints for them and for group icons instead too.
