### ISSUE TITLE
Session.WebhookDelete() doesn't delete webhook

### ISSUE THREAD

**Issue by Krognol** [bwmarrin/discordgo#310]
Hook is created after a message is sent
```go
if m.Author.ID != CLIENT_ID {
		hook, err := s.WebhookCreate(m.ChannelID, "go-nano", img)
        ...
```
and then deleted when it's done it's thing
```go
s.WebhookExecute(hook.ID, hook.Token, true, createWebhookParameter(append(embeds, embed)))
_, err = s.WebhookDelete(hook.ID)
```

Error says `json unmarshal`/`unexpected end of JSON input`.
The `uint8` array in the WebhookDelete() function is always empty
![image](https://cloud.githubusercontent.com/assets/10560012/21916224/61733964-d93f-11e6-98e6-e54d340414dc.png)
Does not answer the question why it doesn't delete the webhook though.

**Comment by iopred** [comment]
Use WebhookDeleteWithToken, WebhookDelete requires authentication.

https://github.com/hammerandchisel/discord-api-docs/blob/master/docs/resources/Webhook.md

**Comment by Krognol** [comment]
WebHookDeleteWithToken does not work either, `_, err = s.WebhookDeleteWithToken(hook.ID, hook.Token)`

**Comment by iopred** [comment]
What does the error say? I verified this works yesterday, so either your
hook ID or Token is missing or something else is up.

**Comment by Krognol** [comment]
ID and token both exist, the error is the same as the previous one: `unexpected end of JSON input`

**Comment by iopred** [comment]
Hmmm, it could be that we have the return value for WebhookDeleteWithToken
wrong, is the Webhook not being deleted?

**Comment by Krognol** [comment]
Like I said, the webhook is still present in the channel after WebhookDeleteWithToken.
![image](https://cloud.githubusercontent.com/assets/10560012/21940737/f7bb2a9a-d9c5-11e6-9930-5c95801ff052.png)
![image](https://cloud.githubusercontent.com/assets/10560012/21940749/06e19f9a-d9c6-11e6-9dd3-2a0e6f72ca8b.png)

**Comment by iopred** [comment]
It could be a discord issue, you are deleting it very soon after creating
it?

**Comment by Krognol** [comment]
There's a ~10-15 second delay between creation and deletion.

**Comment by Krognol** [comment]
Doing 
```go
hook, _ := s.WebHookCreate(...)
defer s.WebhookDeleteWithToken(hook.ID, hook.Token)
```
fixes it
