### ISSUE TITLE
Airhorn example has DCA0 code

### ISSUE THREAD

**Issue by sebsebmc** [bwmarrin/discordgo#312]
I was trying to follow the airhorn example but I kept getting panics with `opuslen` when using my own audio files that I had converted using [dca](https://github.com/jonas747/dca/tree/master/cmd/dca). Turns out that the converter outputs DCA1 files and so using the airhorn example code the magic bytes at the beginning mess everything up.

Only after going through the DCA1 spec and the converter's examples was I able to play my own audio files.

I think the examples would be more helpful to beginners if it specified it only worked for DCA0 encoded files or used a DCA1 file and had DCA1 compatible reading.

**Comment by iopred** [comment]
The README specifies to use --raw which creates DCA0 files.

Perhaps we can be even more specific, or you could do a PR with DCA1 code? :)

**Comment by jonas747** [comment]
The example could use my dca package (https://godoc.org/github.com/jonas747/dca#Decoder), which will auto detect version when decoding, but then the example would depend on an outside package, which I'm not sure how you guys feel about.

**Comment by bwmarrin** [comment]
I'd prefer to keep all of the examples as absolutely simple as possible to the point that they're only demonstrating one easy concept for the end user.  In the case of the Airhorn example the goal is to show how to connect to a voice channel and send some audio to Discord.  With all of that said, I think I'd rather keep it as is.  Adding dependencies or even a PR for DCA1 support would add complications to the example that I don't think really benefit the main goal of it.
