### ISSUE TITLE
Session.WebHookCreate() doesn't assign webhook avatar.

### ISSUE THREAD

**Issue by Krognol** [bwmarrin/discordgo#313]
```go
hook, err := s.WebhookCreate(m.ChannelID, "go-nano", "http://i.imgur.com/RQF6Yoz.jpg")
```
Hook is created without an avatar.
![image](https://cloud.githubusercontent.com/assets/10560012/22042156/41a0169c-dd0a-11e6-8f5b-964e97ad0b5d.png)

**Comment by iopred** [comment]
Avatar is not a URL but a base64 encoded string:

https://discordapp.com/developers/docs/resources/webhook#create-webhook

eg:
https://github.com/iopred/bruxism/blob/master/wormholeplugin/wormholeplugin.go#L164
