### ISSUE TITLE
Can't easily change own nickname

### ISSUE THREAD

**Issue by notdisliked** [bwmarrin/discordgo#318]
I'm writing a bot using DiscordGo.  Attempting to have it change its nickname proved harder than expected, due to GuildMemberNickname throwing a 403 Permission error when I provided the bot's own ID as a target.  This is due to, as already referenced in #189, editing the current user's nickname needing an additional "/nick" in the API call, making it "/guild/{guild.id}/user/@me/nick" instead of "/guild/{guild.id}/user/{user.id}"
Maybe an enhancement can be made here?  Either adding a check for "@me" or the current user's user ID in GuildMemberNickname which would set the ID to be @me and add the "/nick" to the API call.  Or alternatively, making a different unique function altogether for editing the current user's nickname.
Thoughts?

**Comment by iopred** [comment]
Checking for "@me" and appending /nick sounds good, that will be backwards
compatible with people sending "@me/nick" also.

**Comment by VagantemNumen** [comment]
Would not adding a unique function for that be much nicer?
Like ``ClientGuildNickname`` or similar.

**Comment by notdisliked** [comment]
Implementing a ClientGuildNickname function would be more inline with the API, but the check in GuildMemberNickname would be more friendly to use.  Either way isn't too far off the API either, IMO Discord should get rid of the "/nick" endpoint themselves and just roll it into "@me".

**Comment by Deanveloper** [comment]
Would the current workaround be to do `s.Request("PATCH", discordgo.EndpointGuildMembers(ev.ID) + "/@me/nick", Nick{"nickname"})`?

**Comment by notdisliked** [comment]
`data := struct {
	Nick string `json:"nick"`
}{"Me Too"}
s.RequestWithBucketID("PATCH", discordgo.EndpointGuildMember(guild.ID, "@me")+"/nick", data, discordgo.EndpointGuildMember(guild.ID, ""))` is the exact workaround I used, where "Me Too" being the nickname.  Might not be the best but it worked.

Also, the fix should be live on the "develop" branch of the code, so you can switch to that and use it now if that's an option.

**Comment by legolord208** [comment]
It seems like this is fixed already. Why isn't this issue closed?
