### ISSUE TITLE
Mention channels

### ISSUE THREAD

**Issue by toby3d** [bwmarrin/discordgo#321]
I did not find in the documentation referred to the mechanism of a list of channels. How can I get this information?

**Comment by bwmarrin** [comment]
@toby3d sorry this went unnoticed for so long :(.  Do you want a list of channels for a specific guild? If so, the function Session.GuildChannels() will pull that information from the REST API.   For future reference, for quick questions it might be best to join us on the Discord Gophers server https://discord.gg/0f1SbxBZjYoCtNPP and we'll try to answer any other questions you have.
