### ISSUE TITLE
Error installing in macOS

### ISSUE THREAD

**Issue by eefret** [bwmarrin/discordgo#324]
after a go get I get the following error:

```
┗ go get github.com/bwmarrin/discordgo

# github.com/gorilla/websocket
Workspace/go/src/github.com/gorilla/websocket/client_clone.go:15: cfg.Clone undefined (type *tls.Config has no field or method Clone)
```

**Comment by acdenisSK** [comment]
This doesn't seem like a discordgo issue, but by the looks of it you need to update to [1.8](https://golang.org/doc/install?download=go1.8.darwin-amd64.pkg) (if you look at this [commit](https://github.com/gorilla/websocket/commit/3f3e394da2b801fbe732a935ef40724762a67a07)'s name you'll get the reason why you need to).

**Comment by eefret** [comment]
Yeah I solved it, sorry

**Comment by bwmarrin** [comment]
Just for reference, it looks like the commit linked by @acdenisSK does have a fall back for Go < 1.8
https://github.com/gorilla/websocket/commit/3f3e394da2b801fbe732a935ef40724762a67a07#diff-69be9698f4130a53b95e0d7c7a3745c1R5

So DiscordGo should still officially work with 1.6 though 1.8.

@eefret what did you do to the fix the problem, in case somebody else has the same issue?
