### ISSUE TITLE
Expose "DM Channel" for private messaging

### ISSUE THREAD

**Issue by Southclaws** [bwmarrin/discordgo#325]
Hi, I recently wrote a bot for a community that required private messaging to verify that Discord users were the owner of accounts on the community forum. I wanted to allow users to do their validation process via private message but as far as I could find there was no private message type in this API (["DM Channel" according to the docs](https://discordapp.com/developers/docs/resources/channel#dm-channel-object))

I don't know my way around this codebase so I couldn't confidently create a pull request but I've implemented the bare essentials that I needed to complete the project:

- struct: https://github.com/Southclaws/jeff/blob/master/bot_discord.go#L14-L20
- endpoint: https://github.com/Southclaws/jeff/blob/master/bot_discord.go#L66-L87

Someone more familiar with the codebase could probably do a much better job but maybe this will help.

I could probably still implement it myself with a point in the right direction if you're strapped for time :)

**Comment by acdenisSK** [comment]
Discordgo doesn't really need to, why you may ask? Because the method for creating a dm channel with a recipient already [exists](https://github.com/bwmarrin/discordgo/blob/master/restapi.go#L357).

**Comment by Southclaws** [comment]
It's not named the same as the API docs, that was throwing me off.

**Comment by acdenisSK** [comment]
Yes because discord has guild, dm and group channels all squashed in one object, which is what discordgo is following with the `Channel` type. The reason they put "DM Channel" there is to be nice to you if you were to split the object into the three channel types and wanted to know which specific properties does only a dm channel have, and etc., but i may be wrong.

**Comment by bwmarrin** [comment]
Thanks for helping our @acdenisSK  :)  @Southclaws I hope this covers all of your questions.  If not, join us on the Discord Gophers server https://discord.gg/0SBTUU1wZTWT6sqd and we'll help answer any other questions you have!
