### ISSUE TITLE
Make the error logged in the `event.go` file be more informative

### ISSUE THREAD

**Issue by acdenisSK** [bwmarrin/discordgo#326]
Currently stuff like `error dispatching internal event, member not found` doesn't really give us enough info for debugging the culprit of the error.

**Comment by iopred** [comment]
I think this error should just be reduced in severity. It's harmless.

**Comment by acdenisSK** [comment]
Yeah that's true, maybe we should log it as a warning instead?

**Comment by iopred** [comment]
Sounds good to me

**Comment by tsdtsdtsd** [comment]
This issue can be closed. Log level was changed in https://github.com/bwmarrin/discordgo/commit/c34affbc570dee6050ae15e42b08d9c061a0a3aa

**Comment by bwmarrin** [comment]
Thanks @tsdtsdtsd  :)
