### ISSUE TITLE
Discussion: What should we do about this issue?

### ISSUE THREAD

**Issue by LEGOlord208** [bwmarrin/discordgo#351]
Since my pull request #349, which adds ChannelMessageSendComplex and ChannelMessageEditComplex... it also raises a new... interesting problem.

ChannelMessageEditEmbed was apparently slightly changed.  
It now clears the previous message's contents.

Why does it do this?  
Well, I assume it's because the content is sent, even if it's empty.

**Which finally raises the question**:
We can obviously fix this with omitempty.  
_But do we want to?_  

I bet most people want ChannelMessageEditEmbed to clear the previous message,
but it also raises an impossibility to change it without querying the previous message.

If it's omitempty, I assume we can just leave a space, and Discord might even trim that to empty.  
Which works fine.

Any ideas?

**Comment by iopred** [comment]
Change the message field to a *string and then we can omit on `nil` only.

**Comment by LEGOlord208** [comment]
Good idea actually. Except... will the JSON library catch up on that?

**Comment by iopred** [comment]
Yeah, sadly the way to use it is gross though, you have to have a reference to a string, and can't set it in a single expression:

https://play.golang.org/p/yNmBv6NqS8

Still kinda seems right.

**Comment by iopred** [comment]
(we can probably have a 'SetMessage' function on the MessageEdit struct, would simplify the code:

e := discordgo.MessageEdit{}
e.SetContent("sup")
e.SetEmbed(&discordgo.MessageEmbed{})

**Comment by LEGOlord208** [comment]
Good idea as well! Would kinda break a pattern though...

**Comment by iopred** [comment]
Yeah, but this is the 'complex' version. :)

Luckily all of the existing wrapped callsites don't need to change, they should work fine.

**Comment by LEGOlord208** [comment]
I'll do it later!
