### ISSUE TITLE
OpusRecv does not receive data from web clients.

### ISSUE THREAD

**Issue by kylecarbs** [bwmarrin/discordgo#360]
No data is sent from web clients to OpusRecv in a VoiceConnection. The data is sent when using the mobile, or desktop application. I've tried to debug this further and cannot seem to find the root of the problem. Please help.

**Comment by bwmarrin** [comment]
I'll try to test this when I can.  It seems rather odd though.  As far as I know Discord only sends audio one way.  Anyhow, if anyone else can help confirm/test the issue I'd appreciate it.

**Comment by kylecarbs** [comment]
I seem to have found the issue, when opening the voice connection, a list of encryption modes are sent to the client.

Here is an example payload for voiceOP2:
```
{
    "ssrc": 1,
    "port": 1234,
    "modes": ["plain", "xsalsa20_poly1305"],
    "heartbeat_interval": 1
}
```

The issue is that the client is opening a connection with "xsalsa20_poly1305" encryption mode for voice. This mode is fine for mobile, and desktop versions, as this is the type of voice encryption they use. The web client uses the "plain" mode.

**Comment by ammario** [comment]
I can verify the described issue exists.

It should be noted that discord has deprecated `plain` mode

**Comment by bwmarrin** [comment]
Hmn, I'm not really sure how we would fix this.  If the web interface is sending in "plain" mode, then Discord needs to fix the web interface, or encrypt it on the fly when it sends it out to clients using encryption.  I don't think reverting DiscordGo back to the unsupported unencrypted mode would make sense.
