### ISSUE TITLE
Use uint64s instead of strings for IDs

### ISSUE THREAD

**Issue by ducc** [bwmarrin/discordgo#380]

**Comment by bwmarrin** [comment]
I think this change would be dependant on switching to ETF https://github.com/bwmarrin/discordgo/issues/96

**Comment by NatoBoram** [comment]
For more context : https://discordapp.com/developers/docs/reference#snowflakes

> Discord utilizes Twitter's snowflake format for uniquely identifiable descriptors (IDs). These IDs are guaranteed to be unique across all of Discord, except in some unique scenarios in which child objects share their parent's ID. Because Snowflake IDs are up to 64 bits in size (e.g. a **uint64**), they are always returned as **strings** in the HTTP API to prevent integer overflows in some languages. See Gateway ETF/JSON for more information regarding Gateway encoding.

**Comment by jonas747** [comment]
i opened a pr for this a while ago (#433), but the branch is a bit out of date now, I'm using a variation of it in production for my own bots.

**Comment by robbix1206** [comment]
A problem for me is that we cannot check when we have a possible null value like in [this structure](https://discordapp.com/developers/docs/resources/channel#channel-object-channel-structure)
 in the parent id for example.
How to manage them ? Use 0 or negative value and check the validity of snowflakes values based on that criterion ?

**Comment by jonas747** [comment]
That's what i've been doing, have had no problems so far, dont think there is any 0 snowflake, unless they sent a message at the exact time the discord epoch started, or something like that.

**Comment by CarsonHoffman** [comment]
The library is quite reliant on strings at this point, and given that the API only deals with strings and there hasn't been much movement on this front, I'm going to go ahead and close this.
