### ISSUE TITLE
Reactions use raw emoji character

### ISSUE THREAD

**Issue by Deanveloper** [bwmarrin/discordgo#382]
I feel like this isn't intended. Shouldn't name be something like `+1`?

(This is the ev.Emoji struct for :+1: reactions, along with different skin tones)

![image](https://cloud.githubusercontent.com/assets/3196327/25925461/59d8220c-35ae-11e7-9172-f5fafb899597.png)

**Comment by robbix1206** [comment]
Actually DiscordGo only display the according character on your terminal which doesn't support this UTF-8 characters. I think that the best way is too convert it by yourself.

**Comment by robbix1206** [comment]
I think that DiscordGo only display the according character on your terminal which doesn't support this UTF-8 characters. I think that the best way is too convert it by yourself.

**Comment by Deanveloper** [comment]
@robbix1206 I feel like calling it "Name" is a bit confusing then, especially when Discord's [emoji object](https://discordapp.com/developers/docs/resources/channel#emoji-structure) uses the name of the emoji

**Comment by Deanveloper** [comment]
Unsure if that's what the discord API returns as there is no documentation for a ReactionAdd event from what I can find

**Comment by bwmarrin** [comment]
DiscordGo just passes along what Discord sends.  We don't fiddle with much because the goal is a low level direct binding of the Discord API and because I'm lazy :)  So, this is what Discord is sending for Name.

**Comment by Deanveloper** [comment]
Huh! Interesting. I'll send a support request to Discord I guess, although I guess the Reaction events are not yet documented so this makes sense.
