### ISSUE TITLE
State is empty if checked soon after logging in

### ISSUE THREAD

**Issue by redg3ar** [bwmarrin/discordgo#384]
```json
{
    "v": 0,
    "session_id": "",
    "user": null,
    "read_state": null,
    "private_channels": [],
    "guilds": [],
    "user_settings": null,
    "user_guild_settings": null,
    "relationships": null,
    "presences": null,
    "MaxMessageCount": 0,
    "TrackChannels": true,
    "TrackEmojis": true,
    "TrackMembers": true,
    "TrackRoles": true,
    "TrackVoice": true
}
```
Here is a link to code that outputs the state and replicates the issue
https://hastebin.com/cegenipeni.go
Adding a several second wait before checking the state solves the issue.

**Comment by iopred** [comment]
This is working as intended, you should wait for the READY event, as that is what populates State.

**Comment by bwmarrin** [comment]
Here's a quick change you can make to block for the ready event. 

Add the below just after the `dg.Open()` line.

```go
ready := make(chan int)
dg.AddHandler(func(s *discordgo.Session, r *discordgo.Ready) {
    ready <- 1
})
<-ready
```

**Comment by bwmarrin** [comment]
Due to lazy loading of guilds the above could contain "Unavailable" guilds.  The solution for that is adding an event that fires once all guilds are fully loaded.  See https://github.com/bwmarrin/discordgo/pull/278
