### ISSUE TITLE
Add Audit Log reason support

### ISSUE THREAD

**Issue by nullpixel** [bwmarrin/discordgo#386]
Via `X-Audit-Log-Reason` header

**Comment by bwmarrin** [comment]
Maybe you can add a bit more context here on what you want, how it improves the library, and maybe a bit more detail on how you're envisioning it being implemented?

**Comment by nullpixel** [comment]
Well, just add a reason parameter to every auditable action. It allows the end user to specify reasons and state who does things, which eliminates the need for a modlog.

**Comment by Seklfreak** [comment]
The implementation is described here: https://discordapp.com/developers/docs/resources/audit-log

And here an example how it looks in action: 
<img width="924" alt="screen shot 2017-07-26 at 04 08 09" src="https://user-images.githubusercontent.com/1156226/28601394-4519e760-71b8-11e7-9358-1a5eaf09ea04.png">

It's useful for Bots so they can attach who actually caused the, for example, kick. Without Audit Log Reason users can call bot commands and then remove their messages making it impossible to trace it back (without other mod logs as nullpixel mentioned).

**Comment by Seklfreak** [comment]
Ban and Kick already have a function for adding a Reason. Is there a list with all endpoints that support audit log reasons?

**Comment by bwmarrin** [comment]
That's a pretty good question and I'm not sure I know the answer even at this point.  I'll try to research it a bit though and see - or anyone else that already knows off the top of their head are free to jump in :)

**Comment by JurrijnP** [comment]
Here 356 days later, I tested this and this is what I have:
When adding **X-Audit-Log-Reason** in the request header and giving someone a role through a bot it also adds the reason in the audit log, it seems it also has no inpact on a endpoint like getting channel data.

I don't know though what would be a good way to implement this, I think we should avoid adding a ton of _WithReason_ functions unless there is no other way.

**Comment by J0eppp** [comment]
If I'm correct #785 implemented this, so maybe this issue can be closed?

**Comment by Cyb3r-Jak3** [comment]
I don't believe this has been fully addressed. While functions such as Kick and Ban have a separate WithReason, functions such ChannelMessagePin and GuildMemeberRoleAdd do not. Not sure if I should make it a separate issue.

**Comment by bwmarrin** [comment]
@Cyb3r-Jak3 If you can, lets just make a ticket specific to what you've found.
