### ISSUE TITLE
VoiceConnection.OpusSend channel prevents reuse of buffers

### ISSUE THREAD

**Issue by nhooyr** [bwmarrin/discordgo#400]
I think that we should provide a io.Writer like interface instead of a channel to write to the voice connection. This would allow one to reuse buffers instead of having to throw them away because there is no guarantee of when the goroutine receiving on OpusChannel channel is done with it.

It's nice that its async by default, but libraries shouldn't be async by default. They should let the user choose how they want to use the API and in Go, its really easy to make synchronous calls asynchronous but its impossible to go the other way.

**Comment by j4qfrost** [comment]
I'm building a Discord bot right now that I'm trying to use to stream audio to Google voice recognition. I think this would so my current problem with the streaming although I'm not completely sure what's happening on that end.

I wish I could help implement this, but I'm relatively new to Go. Is there any documentation I can read up on to implement something like this?

**Comment by robbix1206** [comment]
So I had to do a bot which can play music and pause it 
Yes I felt on this problem about synchronous operation as the Opus sender channel is buffered (so my music but was playing music for some more seconds)
I manage that problem by doing an other ticker with the same speed as the original one. (Not the best solution)
So yes it can cause problems with async however I think that you should not use synchronous io.Writer.
For me the only problem is that the channel is buffered (I think I need to open an issue about that to suggest a way to force it to be direct).

> there is no guarantee of when the goroutine receiving on OpusChannel channel is done with it

The solution that I explain above should fix that has sending to the channel will be blocking until the audio has been taken (to be process just after) without rewriting discordgo to support write.

> This would allow one to reuse buffers instead of having to throw them away

What do you mean by that ? I Don't understand what you mean. If you don't want you buffer any more throw it away, if you need it keep it with you.

@j4qfrost  Does the API support Opus ? If not you need to convert audio output with somthing like ffmpeg maybe https://github.com/layeh.com/gopus will help you.
Try to reverse https://github.com/bwmarrin/dca process to get raw file if that is the problem.
However I don't think that channels cause your problem

**Comment by nhooyr** [comment]
@robbix1206

> The solution that I explain above should fix that has sending to the channel will be blocking until the audio has been taken (to be process just after) without rewriting discordgo to support write.

No it wouldn't, removing the buffer on the channel would just mean the voice goroutine successfully received the byte buffer, not that it wrote it successfully.

> What do you mean by that ? I Don't understand what you mean. If you don't want you buffer any more throw it away, if you need it keep it with you.

I cannot keep it with me because that could cause a race condition as I don't know when the voice goroutine is done with it.

**Comment by robbix1206** [comment]
> No it wouldn't, removing the buffer on the channel would just mean the voice goroutine successfully received the byte buffer, not that it wrote it successfully.

Does it really cause race condition ?
`make(chan []byte, 2)`
Seems to be a channel of array and not a channel of pointer on array so is that not a copy of the original one ? If it is there is no problem about race condition.

**Comment by nhooyr** [comment]
Slices in Go are references, not values. See https://blog.golang.org/go-slices-usage-and-internals

**Comment by robbix1206** [comment]
Ok I understand better now.
So yes I think that it can be an real issue if you want to keep the same buffer :/
However most of them are part of the current playing sound. I don't know why do you want to keep them to modify them as when you throw them away they give you back memory when they are not referenced anymore. Is that because of a particular problem ? (Memory peak ? Performance issue ?)

**Comment by nhooyr** [comment]
To reduce GC pressure.

**Comment by robbix1206** [comment]
If you take take the airhorn example:
`InBuf := make([]byte, opuslen)` So the slice is allocated to a specific size modifying the size of a slice is not possible without creating a new buffer https://github.com/golang/go/blob/master/src/runtime/slice.go#L144
So I don't think that this will be a lot more optimal as in all cases you lost your Slice.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
