### ISSUE TITLE
Locks should not be public

### ISSUE THREAD

**Issue by nhooyr** [bwmarrin/discordgo#401]
e.g. on https://godoc.org/github.com/bwmarrin/discordgo#Session why is the lock public? Why would a user need to access it?

And if there is a lock, why are so many of the fields public? They should have getter methods that use the lock to prevent race conditions.

In many other structures in the library, this is repeated. I think we should make the locks private and use getter/setter methods to prevent race conditions.

**Comment by ammario** [comment]
Getter methods aren't sufficient when multiple operations need to be performed synchronously. Some operations (such as iterating VoiceConnections) isn't supported by any helper function.

**Comment by iopred** [comment]
There's no reason for the locks to be public.

**Comment by nhooyr** [comment]
I disagree, at least for this struct. I don't see any reason why multiple operations would need to be performed synchronously on the fields of a Session. Most of the public fields are configuration options and they should not be public in the first place. There should be a configuration struct or something else (see my link below) that is passed to New to configure the session. That would remove most of the fields on the struct.

As for iterating voice connections, we can just write a method to return a shallow copy of the map. The performance impact will be negligible but the API will be much more safe and clean.

The public lock also raises questions like if its safe to access the http client or state members without locking/unlocking because they are protected by their own lock. I don't see why the state member's lock is public either. Most of its fields are configuration too and they should be in a separate configuration struct or something else.

There is a post by Dave Cheney that goes over various options for configuration: https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis

**Comment by ammario** [comment]
If the lock is removed, functionality such as iterating `VoiceConnections` should be carefully considered or we risk deserting users relying on it (including me).

**Comment by bwmarrin** [comment]
Hmn, Why? Well probably just because that's how it happened at the start and nobody in the last year or so has ever said anything or objected to it.  But, the issue with making huge changes now is how will that effect the people using the API now and is the benefit worth the pain?  I'm definitely open to discussing this and see what the community as a whole thinks.

**Comment by nhooyr** [comment]
> Hmn, Why? Well probably just because that's how it happened at the start and nobody in the last year or so has ever said anything or objected to it.

Ah sorry, I didn't mean to ask literally "Why?" but rather, I wanted to propose changes. I'll retitle.

> But, the issue with making huge changes now is how will that effect the people using the API now and is the benefit worth the pain?

I think the safety is worth it.

And you have the disclaimer on the README so the community was warned already that this library may have major changes.

**Comment by nhooyr** [comment]
I thought about and I don't think the configuration fields should be private anymore. I think it would be overly verbose to use a config struct and I think its more idiomatic to have them public in the struct as this pattern is used throughout the standard library.

However, I still think we should make the locks private. Making the locks private will not cause the API to change as much as removing configuration fields.

**Comment by bwmarrin** [comment]
I don't think that would be a problem at all.  Honestly, no idea if there was any reason for it when it was done but, I don't think there's any reason anymore.

**Comment by blackhole12** [comment]
FYI, I do not use this session lock, but I do use the State lock, which is necessary whenever I want to iterate over something in the internal state, because a getter method cannot iterate over a variable - a read lock must be held for the duration of the iteration if you're iterating over, for example, channels, and then reading something inside the channels, unless you copy the entire channel struct to a completely new channel struct. I don't think there's any reason to expose the Session lock, though.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
