### ISSUE TITLE
No need for runtime.LockOSThread in opusSender

### ISSUE THREAD

**Issue by nhooyr** [bwmarrin/discordgo#402]
On this [line](https://github.com/bwmarrin/discordgo/blob/0993a94b4e1c3291bed2047f583f34792269355c/voice.go#L662 ) I think `runtime.LockOSThread()` might have been added for performance reasons but it doesn't actually help with the performance of that function.

`runtime.LockOSThread` is supposed to be for interfacing with libraries. See https://github.com/golang/go/wiki/LockOSThread

Shall I create a PR to remove it?

**Comment by iopred** [comment]
Seems reasonable to remove it.
