### ISSUE TITLE
reconnect() can be called while still connected

### ISSUE THREAD

**Issue by blackhole12** [bwmarrin/discordgo#406]
In certain extremely rare edge-cases, it's possible that a Close() can be requested after a Heartbeat fails to send, but the Close() fails to actually happen for quite some time due to an I/O timeout. This appears to open up some sort of race condition where two reconnect attempts happen at once.

    2017/07/18 16:45:26 [DG2] restapi.go:154:request() Rate Limiting https://discordapp.com/api/guilds/[censored]/members?limit=999, retry in 679
    2017/07/18 16:45:26 [DG2] restapi.go:154:request() Rate Limiting https://discordapp.com/api/guilds/[censored]/members?after=[censored]&limit=999, retry in 674
    2017/07/18 16:46:04 [DG2] wsapi.go:226:heartbeat() sending gateway websocket heartbeat seq 783
    2017/07/18 16:49:02 [DG0] wsapi.go:232:heartbeat() error sending heartbeat to gateway wss://gateway.discord.gg/?v=5&encoding=json, websocket: close sent
    2017/07/18 16:49:02 [DG2] wsapi.go:724:Close() called
    2017/07/18 16:49:02 [DG2] wsapi.go:728:Close() closing listening channel
    2017/07/18 16:49:02 [DG2] wsapi.go:738:Close() sending close frame
    2017/07/18 16:49:02 [DG2] wsapi.go:745:Close() error closing websocket, websocket: close sent
    2017/07/18 16:46:18 [DG1] wsapi.go:166:listen() error reading from gateway wss://gateway.discord.gg/?v=5&encoding=json websocket, websocket: close 1000 (normal)
    2017/07/18 16:49:02 [DG2] wsapi.go:724:Close() called
    ...
    ...
    2017/07/18 16:49:04 [DG2] wsapi.go:754:Close() error closing websocket, write tcp [censored]:
     i/o timeout
    ...
    ...
    2017/07/18 16:49:10 [DG2] wsapi.go:114:Open() sending resume packet to gateway
    2017/07/18 16:49:10 [DG2] wsapi.go:138:Open() emit connect event
    2017/07/18 16:49:10 [DG2] wsapi.go:141:Open() exiting
    2017/07/18 16:49:10 [DG2] wsapi.go:687:reconnect() successfully reconnected to gateway
    2017/07/18 16:49:10 [DG0] wsapi.go:709:reconnect() error reconnecting to gateway, web socket already opened

As a result of this, one reconnect loop will perpetually attempt to reconnect forever, or until another disconnection happens. I'm unsure what the race condition actually is, but if the "web socket already opened" error can be isolated, `reconnect()` could safely exit it's retry loop if it encounters that error. which would make the race condition harmless. If I can properly isolate and test the error I may submit a pull request for this later.

**Comment by robbix1206** [comment]
Solved ?

**Comment by blackhole12** [comment]
This was already merged
