### ISSUE TITLE
Support for gateway and api version 6

### ISSUE THREAD

**Issue by jonas747** [bwmarrin/discordgo#408]
https://discordapp.com/developers/docs/change-log

Older versions will be out of service Oct 16th.

**Comment by legolord208** [comment]
In addition to this, `EndpointAPI` should probably actually specify a version number. Otherwise it'll just break as soon as a breaking update comes along. Ouch.

**Comment by legolord208** [comment]
Added to the develop branch

**Comment by robbix1206** [comment]
New changes on Game Object
https://discordapp.com/developers/docs/change-log#august-16-2017-—-breaking-change
