### ISSUE TITLE
Get UserID from matching name?

### ISSUE THREAD

**Issue by FM1337** [bwmarrin/discordgo#412]
Let's say if I had the bot linked to an game server that allowed you to pass the chat to discord and vice versa and I wanted to ping a member on discord:

Let's say the user I want to ping is using the nick JohnDoe while their userID is something like JohnJDoe#1321.

How would I be able to ping them simply by doing @JohnDoe without knowing the userID?

**Comment by iopred** [comment]
Something like.
```
g, err := session.State.Guild(guildID)
if err == nil {
  for _, m in range := g.Members {
    if m.User.Name == "johndoe" {
      //"<@" + m.User.ID + ">"
    }
  }
}
```

**Comment by FM1337** [comment]
Thanks
