### ISSUE TITLE
messageCreate get guild

### ISSUE THREAD

**Issue by SaubereSacheLP** [bwmarrin/discordgo#413]
Hi,
I have a question, how can I get the guildid and name from the messageCreate event?
The struct is only holding this values :(
ID             
ChannelID      
Content        
Timestamp      
EditedTimestamp
MentionRoles   
Tts            
MentionEveryone
Author         
Attachments    
Embeds         
Mentions       
Reactions

**Comment by iopred** [comment]
c, err := session.State.Channel(messageCreate.ChannelID)
if err != nil {
  return err
}

g, err := session.State.Guild(c.GuildID)
if err != nil {
  return err
}

fmt.Println(g.Name)
