### ISSUE TITLE
InviteAccept is not working

### ISSUE THREAD

**Issue by SaubereSacheLP** [bwmarrin/discordgo#420]
Hi,
InviteAccept returns &{0xc042053600 0xc0420809a0 Opificium#8348 RUukPa8 0 0 0  false false} but the account is not joining the discord (its not a bot account)

(os.Args[2] = RUukPa8)
Code:
```
resp, err := dg.InviteAccept(os.Args[2])
	fmt.Println(resp)
	if err != nil {
		fmt.Println(err)
		return
	}
```

**Comment by Necroforger** [comment]
Is the account verified? I've only tried InviteAccept with unverified accounts and had no success.

**Comment by SaubereSacheLP** [comment]
The Account is verified but its not working

**Comment by Harmon758** [comment]
Selfbots/Userbots can no longer accept invites through that endpoint.
It's blacklisted now, and attempting to do so will likely unverify your account and potentially get it banned.

**Comment by SaubereSacheLP** [comment]
Why is it not fixed / disabled?

**Comment by bwmarrin** [comment]
Well, that's a good question.  If it's not usable at all except for the official discord client then I suppose it should be removed.  @Harmon758 can you link a reference to where it's discussed by any chance?

**Comment by Harmon758** [comment]
I don't think it's officially documented anywhere yet, but there's been substantial discussion about it in the Discord API server. A quick search for "accept invite" will bring up messages going back months regarding the issue.

**Comment by CarsonHoffman** [comment]
Given that the bot API has no support for relationships, I'm going to close this.
