### ISSUE TITLE
Webhook[Method]WithToken is the same as Webhook[Method]

### ISSUE THREAD

**Issue by Hinara** [bwmarrin/discordgo#431]
Currently this is about the same, the only difference is the Endpoint called.
This functions currently binds on session, however, as they don't need any authentication it would be great to put them as static functions, however, the problem is that without Session we cannot limit the number of calls by buckets.

**Comment by CarsonHoffman** [comment]
These are distinct endpoints with subtly different behavior; I don't think that it's an issue that it's a separate method. I agree that it initially seems odd to tie it to the session, but I think the rate-limiting is enough of an upside to keep it there, and would require a massive refactor to separate the rate limiting from the session.
