### ISSUE TITLE
RelationshipFriendRequestSend does not work

### ISSUE THREAD

**Issue by chriskolenko** [bwmarrin/discordgo#436]
When running RelationshipFriendRequestSend

You get no errors, but it doesn't not add the friend request

**Comment by robbix1206** [comment]
Are you using a bot account ?
If yes that's normal because : 

> Bots cannot have friends

**Comment by chriskolenko** [comment]
@robbix1206 

I was using a user account. Was already aware of the Bot friend thing 😄 

No error is produced by the endpoint. 
I've tried both master and develop branch. 

All I can see is the following:
1. Use code to add friend requests
2. No errors
3. No pending requests in Discord
4. Account needs to be re-verified via Email before being able to send friend requests. 

When using Fiddler to capture the request. 
Looks like there is no more body request in the PUT 
And the internet is saying you might have to fake the headers. 

Not sure if this is something else other people have came across and whether or not it should be in the GO library if it's considered "No approved behaviour for code". What I'm trying to say is; looks like Discord doesn't want people to abuse this part of the API and they have in their documentation that self-bots are an abuse of the API.  

Discord docs:
https://github.com/hammerandchisel/discord-api-docs/blob/4169c543c0133437433006e68aa68debc690f9fb/docs/topics/OAuth2.md#L7
`Automating normal user accounts (generally called "self-bots") outside of the OAuth2/bot API is forbidden, and can result in an account termination if found.`

**Comment by Necroforger** [comment]
The endpoint may have been blacklisted similar to https://github.com/bwmarrin/discordgo/issues/420.
I didn't get an error from that endpoint either.
