### ISSUE TITLE
[Typo] var "EndpointGuildInvites" in discordgo/endpoints.go

### ISSUE THREAD

**Issue by jcmdln** [bwmarrin/discordgo#440]
It appears that EndpointGuildInvites is declared twice, though there is a typo in the first declaration on line 74: 
```
...
	EndpointGuildInivtes         = func(gID string) string { return EndpointGuilds + gID + "/invites" }
```

Later on line 86:
```
...
	EndpointGuildInvites         = func(gID string) string { return EndpointGuilds + gID + "/invites" }
...
```

It appears that the only other mention of this variable is on line 910 of discordgo/restapi.go, but if I'm not mistaken this is in fact a typo and should be corrected?
```
	body, err := s.RequestWithBucketID("GET", EndpointGuildInvites(guildID), nil, EndpointGuildInivtes(guildID))
```

**Comment by iopred** [comment]
Definitely should be fixed.

**Comment by jcmdln** [comment]
It appears that this was fixed in a PR. I will close this issue for the time being.
