### ISSUE TITLE
Channel struct's JSON tag for Recipients is incorrect

### ISSUE THREAD

**Issue by darkgray1981** [bwmarrin/discordgo#443]
The _Channel_ struct has a JSON tag for the field _Recipients_ that currently says "recipient", while the present API uses a field named "recipient**s**", causing it to go unfilled by the unmarshaller.  
See https://discordapp.com/developers/docs/resources/channel

**Comment by bwmarrin** [comment]
Thanks for reporting the issue @darkgray1981 :)
