### ISSUE TITLE
Implement Channel parent IDs

### ISSUE THREAD

**Issue by Seklfreak** [bwmarrin/discordgo#447]
The Discord API added a new field to the Channel object to support the newly added Channel Categories called `parent_id`. The change is mentioned here: https://discordapp.com/developers/docs/change-log#september-20-2017.

**Comment by Seklfreak** [comment]
Pull request: #448

**Comment by robbix1206** [comment]
Need to implement the categories permissions too I suppose ^^

**Comment by Seklfreak** [comment]
Category Permissions should already be possible to change using `ChannelPermissionSet`, Categories are just Channels. Looking at the Diff for the Discord API Docs change, I think the only interesting addition would be to make it possible to set the `parent_id` using a func.
The commit in question: https://github.com/discordapp/discord-api-docs/commit/7f0b113a9fc075d704128286498195c9830c3d54#diff-99b76a48d014c043f2f8804f6653ed82R353

**Comment by Seklfreak** [comment]
I'm not sure if we should break all previous versions by adding a `parentID` parameter to `ChannelEdit` or add a new func.

**Comment by robbix1206** [comment]
I think it's better to create a ChannelEdit object like for message edit. But the problem still the same.
@bwmarrin ?
And we need to take care of the new field permission_overwrites as they work with Category Channels if I understand correctly.

**Comment by Seklfreak** [comment]
Just tested it and was able to change the overwrites using `ChannelPermissionSet` just as we used to do with Text and Voice channels. Internally there is no difference between Text, Voice and Category Channels.

**Comment by robbix1206** [comment]
A bit too late I edit my post just few seconds earlier x)
Yes I wasn't understanding because if I correctly remember at a time permissions wasnamed permissions

**Comment by Seklfreak** [comment]
This has been completed in #493 .
