### ISSUE TITLE
Develop branch is broken

### ISSUE THREAD

**Issue by proxikal** [bwmarrin/discordgo#449]
Can't build on develop. Missing the entire file `types.go` can't find type `Timestamp` and more..
Master branch is flooding event errors to the point of eating my memory from channel_update, channel_delete, channel_create & guild_create event errors.
![image](https://media.discordapp.net/attachments/155361364909621248/360787551193137153/unknown.png)

**Comment by iopred** [comment]
I just pulled master and develop and they build fine. Is your go out of date?

**Comment by proxikal** [comment]
yes, i believe my go is out of date, i suppose it's time to update.. And thanks for the quick push!
