### ISSUE TITLE
Presence returns users with incomplete data.

### ISSUE THREAD

**Issue by eljoth** [bwmarrin/discordgo#450]
When trying to get username, avatar or discriminator from a presence, it just returns an empty string. Getting the user from the session by id, requesting these attributes returns correct values.

Here a loggingoutput:

>2017/09/26 13:08:35 user = Presence.User:
2017/09/26 13:08:35 ID: 193789897855729665
2017/09/26 13:08:35 Email: 
2017/09/26 13:08:35 Username: 
2017/09/26 13:08:35 Avatar: 
2017/09/26 13:08:35 Discriminator: 
2017/09/26 13:08:35 Token: 
2017/09/26 13:08:35 Verified: false
2017/09/26 13:08:35 MFA: false
2017/09/26 13:08:35 Bot: false

>2017/09/26 13:08:35 user = Session.User(Presence.User.ID):
2017/09/26 13:08:35 ID: 193789897855729665
2017/09/26 13:08:35 Email: 
2017/09/26 13:08:35 Username: eljoтн
2017/09/26 13:08:35 Avatar: 442025c2e366de9269b559e08f06c177
2017/09/26 13:08:35 Discriminator: 7304
2017/09/26 13:08:35 Token: 
2017/09/26 13:08:35 Verified: false
2017/09/26 13:08:35 MFA: false
2017/09/26 13:08:35 Bot: false`

**Comment by Necroforger** [comment]
The only field in presence updates that is mandatory is the `id` field. User info may or may not be sent.

https://discordapp.com/developers/docs/topics/gateway#presence-update
> The user object within this event can be partial, the only field which must be sent is the id field, everything else is optional. Along with this limitation, no fields are required, and the types of the fields are not validated. Your client should expect any combination of fields and types within this event.
