### ISSUE TITLE
Heartbeat doesn't seem to function

### ISSUE THREAD

**Issue by jlmcmchl** [bwmarrin/discordgo#457]
Code here: [https://github.com/jlmcmchl/tbc-discord-bot/blob/master/main.go](https://github.com/jlmcmchl/tbc-discord-bot/blob/master/main.go)

The bot works just fine, it can read channels and write to them and all, but it only shows up as offline, which leads me to conclude that the heartbeat is broken.

**Comment by iopred** [comment]
Call Open() to connect to Discord.
