### ISSUE TITLE
.gitignore file is ignored or non existent

### ISSUE THREAD

**Issue by SilverCory** [bwmarrin/discordgo#461]
The of a .gitignore is a minor inconvenience when creating PR's and forks.

**Comment by sn0w** [comment]
Just put a global one somewhere (eg `~/.gitignore`) that's tailored to your OS/IDE and save it with 
`git config --global core.excludesfile <path>`

**Comment by bwmarrin** [comment]
@SilverCory I'm not sure I fully understand what you're asking for.  Could you provide some more details?

**Comment by SilverCory** [comment]
A .gitignore file in the root directory masking the temp/unnecessary files that are common in most environments a few examples:

- .idea (intellij)
- Thumbs.db
- .DS_Store
- ._*
- Session.vim
- vendor/
- pkg/

Yeah you can create global ones, but they get in the way of when you need the files/folders.

**Comment by sn0w** [comment]
@SilverCory 

They don't simply "get in the way". That's the whole point of the global file. You can simply add a rule that starts with an exclamation-mark to "un-ignore" a global.

Maybe take a look at https://git-scm.com/docs/gitignore

**Comment by SilverCory** [comment]
@sn0w well aware that you can add an exclude ignores but that's an unnecessary step. If I added all the folders I want to ignore on one project, I'd have several lines of un-ignoring them on the other. It just seems more logical to have the ignore on a per-project basis.

**Comment by bwmarrin** [comment]
Well, I'm open to hearing thoughts from our main contributors on what they think.  I've never had a problem not having a .gitignore file.  How would I know what items need to be in it, for all the people that might want to work on the lib?  How would we balance when some people want some items, and others do not want those items in the .gitignore? Sounds like a pain to me - but I'm open to it if there's a consensus among the existing contributors.

**Comment by SilverCory** [comment]
Personally I add all the common IDE's for the language as well as OS files. I opened this because a I nearly pushed the `.idea` folder.

**Comment by sn0w** [comment]
> [SilverCory]
> I add all the common IDE's for the language as well as OS files

How does that apply to your `they get in the way when you need the files/folders` problem?

> [bwmarrin]
> How would I know what items need to be in it, for all the people that might want to work on the lib?

Exactly.
There's a myriad amount of os/ide/toolchain combinations out there.
Do we really want this project to have a *huge* gitignore that targets *all* of them?
With a PR/Issue each time a new combination/tool pops up?

Other big projects like [docker](https://github.com/moby/moby/blob/master/.gitignore) also only use the file to ignore stuff that's *directly* related to the project and tell their contributors to use a global or nested ignore instead.

**Comment by NamedKitten** [comment]
No comment.

**Comment by robbix1206** [comment]
I would like to say well we can use the default golang gitignore from github but it just cover golang files,
So if you would like to ignore things like ```.idea```
I think that you should setup it globally or use your own gitignore which ignore itself.

**Comment by bwmarrin** [comment]
Based on my own thoughts and the feedback here.  We will not attempt to add a .gitignore file hoping to cover all possible desires of anyone who uses this project.  If we were to add DiscordGo specific files that needed to be ignored, we would create a .gitignore at that time to cover those files.
