### ISSUE TITLE
[Question] Is there a way to DM people?

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [bwmarrin/discordgo#481]
I've read the entire Godoc and cannot find a way to DM somone. Using their ID in ChannelMessageSend doesn't seem to do anything (Guessing that the function can't work outside the channel It's running in).

Sorry if I'm missing something obvious

**Comment by shawntoffel** [comment]
I've used `UserChannelCreate(userId)` to create a dm channel with that user. Then ChannelMessageSend to with id of the new channel created from UserChannelCreate.

**Comment by AlmightyFloppyFish** [comment]
Thanks!
