### ISSUE TITLE
DM users?

### ISSUE THREAD

**Issue by Viusing** [bwmarrin/discordgo#517]
I don't currently see a way to send a direct message to a user. In the API, you would specify the client, and the user would be the client for the .sendMessage function. But with discordgo, session.ChannelMessageSend has no means to send to a user as it only accepts channels.

Am I missing a function?

**Comment by iopred** [comment]
You have to create a channel (even if a DM channel exists, you should still
call this method):
https://godoc.org/github.com/bwmarrin/discordgo#Session.UserChannelCreate

**Comment by Viusing** [comment]
Gotcha! Fun stuff.
