### ISSUE TITLE
Add Member.Mention()

### ISSUE THREAD

**Issue by Altarrel** [bwmarrin/discordgo#518]
While I was working on a mention as a prefix for my bot, I came across the issue of member mentions being different depending on whether they have a nickname or not. Without a nickname, it's just the regular `<@ID>`, but with a nickname it becomes `<@!ID>`.

I think a nice addition would be a Member.Mention() method that returns the mention as the client will send it when users are trying to mention the bot. It's really simple to make, I already have the code, I'm just opening this issue to follow the contributing steps shown in the README.md.

```go
func (m *Member) Mention() string {
	if m.Nick != "" {
		return "<@" + m.User.ID + ">"
	}
	return "<@!" + m.User.ID + ">"
}
```

**Comment by iopred** [comment]
We have a User.Mention, a Member.Mention makes a lot of sense.
