### ISSUE TITLE
MessageReactionAdd bug

### ISSUE THREAD

**Issue by JasonKhew96** [bwmarrin/discordgo#519]
`HTTP 400 Bad Request, {"code": 10014, "message": "Unknown Emoji"}`
```
err = s.MessageReactionAdd(m.ChannelID, msg.ID, "1")
```
---
After doing some research, `Emoji.Name` return `"1"` / `"{49, 226, 131, 163}"`
```
one := []byte{49, 226, 131, 163}
err = s.MessageReactionAdd(m.ChannelID, msg.ID, string(one[:]))
```

**Comment by Necroforger** [comment]
You need to use the actual unicode values when adding emojis. So for `one` you would use "1️⃣".

**Comment by JasonKhew96** [comment]
i tried, 0️⃣ - 9️⃣ doesn't work

**Comment by Necroforger** [comment]
If you want to get the values discord uses you could type `\:emoji_name` into discord somewhere then copy what it outputs.

**Comment by Seklfreak** [comment]
emojipedia.org is useful for getting native emojis

**Comment by iopred** [comment]
MessageReactionAdd requires sending the actual unicode emoji, this is the Discord API spec.
