### ISSUE TITLE
Can't get channel messages

### ISSUE THREAD

**Issue by tomvanwoow** [bwmarrin/discordgo#524]
Say I want to list the contents of every message in a channel. The messages field of the channel struct returned is always empty, so I can't get any messages. Here is my code
```golang
ch, err := s.Channel(m.ChannelID)
if err != nil {
	fmt.Println(err)
    return
}
for _, v := range ch.Messages {
	fmt.Println(v.Content)
}
```
Also `s.State.Channel` doesn't work either.
I get no errors reported.

**Comment by Necroforger** [comment]
You should get messages with the `ChannelMessages` function, or use the State.
To use the state, you need to have set `State.MaxMessageCount ` to a value greater than zero, which will enable message caching. 
https://github.com/bwmarrin/discordgo/blob/master/state.go#L35

The [ChannelMessages](https://godoc.org/github.com/bwmarrin/discordgo#Session.ChannelMessages) function. function allows you to request messages in bulk.

For example, this would return the last 100 messages in a channel.
```go
messages, err := session.ChannelMessages(channelID, 100, "", "", "")
```
The maximum number of messages that can be returned per call is 100, so you need to make multiple requests with the `beforeID` parameter set to the ID of the last message recieved from the previous call.
