### ISSUE TITLE
dca-rs broken, FAQ outdated

### ISSUE THREAD

**Issue by santichu95** [bwmarrin/discordgo#534]
It seems like a few of the dependencies for dca-rs are no longer being maintained causing it to not build. Because of that the [FAQ](https://github.com/bwmarrin/discordgo/wiki/FAQ#playing-audio-over-a-voice-connection) on playing audio over a voice connection is now out of date.

**Comment by iopred** [comment]
Updated to point at https://github.com/jonas747/dca
