### ISSUE TITLE
Session.MessageReactionAdd returning 404 for emojis

### ISSUE THREAD

**Issue by primetoxinz** [bwmarrin/discordgo#543]
```go
    err := s.MessageReactionAdd(message.ChannelID,message.ID, ":thumbsup:") 
    err := s.MessageReactionAdd(message.ChannelID,message.ID, "thumbsup")
```
I am attempting to add a reaction to a message sent by my bot and no matter how I format the emoji it always responds `HTTP 400 Bad Request, {"code": 10014, "message": "Unknown Emoji"}`.
I have tried to find information on how the emoij should be but haven't found anything definitive.
Any ideas?

**Comment by iopred** [comment]
You need to use the actual Unicode emoji 👍, the endpoint doesn't take
shortcuts for Unicode emoji.

**Comment by primetoxinz** [comment]
I am actually trying to do it with a custom server emote too and getting the same result. For example `:thonk:`

**Comment by iopred** [comment]
In that case use emoji.ApiName() the expected format contains the emoji id.

**Comment by primetoxinz** [comment]
Ah, that works perfectly thank you!

**Comment by adamijak** [comment]
Will you consider please adding this information to documentation? I struggled a bit to find it out.

**Comment by hexcowboy** [comment]
I came here looking for information as well and found the format of `emoji:111111` to work, where as most online references were saying `<:emoji:11111>` or just `111111`.

Here's a sample of what worked for me: `eternal:871862746575142983`

```go
	reactions := []string{"1️⃣", "2️⃣", "3️⃣", "eternal:871862746575142983"}
	for _, reaction := range reactions {
		err = s.MessageReactionAdd(
			m.ChannelID,
			msg.ID,
			reaction,
		)
		if err != nil {
			return err
		}
	}
```
