### ISSUE TITLE
Sending messages doesn't seem to work

### ISSUE THREAD

**Issue by carroarmato0** [bwmarrin/discordgo#548]
go version go1.10.2 linux/amd64
Using commit 4a33b9bc7c56cfdb9bb244e33e83cb3941fe2bdc

I'm using the ping/pong example code to test things out:

```
func messageCreate(s *discordgo.Session, m *discordgo.MessageCreate) {
	// Ignore all messages created by the bot itself
	// This isn't required in this specific example but it's a good practice.
	if m.Author.ID == s.State.User.ID {
		return
	}
	// If the message is "ping" reply with "Pong!"
	if m.Content == "ping" {
		s.ChannelMessageSend(m.ChannelID, "Pong!")
	}
	// If the message is "pong" reply with "Ping!"
	if m.Content == "pong" {
		s.ChannelMessageSend(m.ChannelID, "Ping!")
	}
}
```

Using a debugger, I can see that  **s.ChannelMessageSend(m.ChannelID, "Pong!")** is being correctly called when someone writes "ping" in the channel.

The code does a POST request, and then returns, however, the reply of the bot is never displayed.

**Comment by iopred** [comment]
Check the error from ChannelMessageSend.

**Comment by carroarmato0** [comment]
That's the weird part, it doesn't show or get an error.

```
                                                                   "4466......."             "Pong!"
func (s *Session) ChannelMessageSend(channelID string, content string) (*Message, error) {
	return s.ChannelMessageSendComplex(channelID, &MessageSend{
		Content: content,
	})
}
```

**Comment by iopred** [comment]
Hmmm, are you getting a Message object back? What does it contain?

**Comment by carroarmato0** [comment]
In this function:

```
func (s *Session) ChannelMessageSend(channelID string, content string) (*Message, error) {
	return s.ChannelMessageSendComplex(channelID, &MessageSend{
 		Content: content,
 	})
}
```
(*Message, error)   seems to be empty.

~r2: nil <*discordbot/vendor/github.com/bwmarrin/discordgo.Message>
~r3: error (empty)

channelID and content do have the proper values.

**Comment by iopred** [comment]
Hmm, this is really strange, could you try using the `develop` branch?

**Comment by carroarmato0** [comment]
Switched to 82c8cf21b216a2507bfd815484b4a91183662d4c

Same issue. Not sure but I think the code has been tested against golang 1.9 while I'm running 1.10 ?

**Comment by iopred** [comment]
Nah, many people run bots on 1.10 including myself.

Have you ever opened the websocket? You need to do it once per accot before
messages send.

On May 18, 2018 11:08 AM, "Christophe Vanlancker" <notifications@github.com>
wrote:

Switched to 82c8cf2
<https://github.com/bwmarrin/discordgo/commit/82c8cf21b216a2507bfd815484b4a91183662d4c>

Same issue. Not sure but I think the code has been tested against golang
1.9 while I'm running 1.10 ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/bwmarrin/discordgo/issues/548#issuecomment-390287946>,
or mute the thread

**Comment by carroarmato0** [comment]
What do you mean by that?  I noticed while debugging that it was doing something websocket related, but I would think that just works?

**Comment by iopred** [comment]
Did you call session.Open()?

**Comment by carroarmato0** [comment]
Not explicitely.

As I said, I used the ping/pong code example as reference. (https://github.com/bwmarrin/discordgo/blob/master/examples/pingpong/main.go)

```
	// Open a websocket connection to Discord and begin listening.
	err = dg.Open()
	if err != nil {
		fmt.Println("error opening connection,", err)
		return
	}
```

**Comment by carroarmato0** [comment]
Oh wow, that's evil. But it actually works now.

Thanks!  How this is needed?  Discord's API work like that?

**Comment by iopred** [comment]
It's a discord API requirement.
