### ISSUE TITLE
Running bot on linux does not appear to react

### ISSUE THREAD

**Issue by d3v1l401** [bwmarrin/discordgo#563]
Hello,

So I'm working on a bot, the bot is initially developed on Windows trough Visual Studio Code, tested also on the same computer and it runs perfectly.

As soon as I uploaded the code on my Ubuntu server (and go getted discordgo), it appears the code runs until start without any error, but the bot is completely unresponsive and appears offline on the online users of the server.

Am I missing something or is it not working? 

2018/06/24 15:25:55 API REQUEST      GET :: https://discordapp.com/api/v6/gateway
2018/06/24 15:25:55 API REQUEST  PAYLOAD :: []
2018/06/24 15:25:55 API REQUEST   HEADER :: [Content-Type] = [application/json]
2018/06/24 15:25:55 API REQUEST   HEADER :: [User-Agent] = [DiscordBot (https://github.com/bwmarrin/discordgo, v0.18.0)]
2018/06/24 15:25:55 API REQUEST   HEADER :: [Authorization] = [Bot TOKEN_CENSORED]
2018/06/24 15:25:55 API RESPONSE  STATUS :: 200 OK
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Content-Type] = [application/json]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Strict-Transport-Security] = [max-age=31536000; includeSubDomains]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Alt-Svc] = [clear]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Cf-Cache-Status] = [HIT]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Vary] = [Accept-Encoding]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Cache-Control] = [public, max-age=1800]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Content-Length] = [35]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Expires] = [Sun, 24 Jun 2018 13:55:55 GMT]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Expect-Ct] = [max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Server] = [cloudflare]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Cf-Ray] = [42ff85eddd5272dd-AMS]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Date] = [Sun, 24 Jun 2018 13:25:55 GMT]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Set-Cookie] = [__cfduid=aaaasdasdasd; expires=Mon, 24-Jun-19 13:25:55 GMT; path=/; domain=.discordapp.com; HttpOnly]
2018/06/24 15:25:55 API RESPONSE  HEADER :: [Via] = [1.1 google]
2018/06/24 15:25:55 API RESPONSE    BODY :: [{"url": "wss://gateway.discord.gg"}]

Also, it appears that sometimes sending a message on the server will get the bot stuck on 
2018/06/24 15:34:11 API REQUEST     POST :: https://discordapp.com/api/v6/channels/*channelid*/messages

**Comment by iopred** [comment]
This usually happens when the token doesn't have the "Bot " prefix.

**Comment by d3v1l401** [comment]
The "Bot " prefix is there

if dg, err := discordgo.New("Bot " + _token); err == nil {

**Comment by iopred** [comment]
Is your bot on Hetzner? Discord banned that service.

**Comment by robbix1206** [comment]
What version of discordgo do you use under windows and under linux ?
If the code and the parameters are the same there shouldn't be any differences, excepting if your library versions are not the same

**Comment by d3v1l401** [comment]
@iopred 
No, it's hosted on OVH.

@robbix1206 
Latest version, on both platforms, no changes have been made, the same copy works on Windows but not Linux.

**Comment by NatoBoram** [comment]
Have you tried to run it inside Bash on Ubuntu on Windows?

**Comment by d3v1l401** [comment]
Just tried, same story.

**Comment by bwmarrin** [comment]
@d3v1l401 are you still having this issue?  It might be easier to solve this over on the Discord chat server (see the readme file for the link).  Feel free to ping me on there or just ask in the discordgo channel.

Or respond here if you've solved it or not.  Try it again with the latest develop code as there's been some changes and then see if it's still going on.

**Comment by d3v1l401** [comment]
Yes, I still have the problem, but I did not test with the latest code so I'm going to test it asap.

**Comment by bwmarrin** [comment]
Great, let me know how it goes.
