### ISSUE TITLE
Advice on mocking discordgo

### ISSUE THREAD

**Issue by GeekyDeaks** [bwmarrin/discordgo#564]
Hi,

I am a little new to go and was trying to write some tests for a discord bot which is using the discordgo package.   Unfortunately, I am at a loss of how to mock some of the structs so I can override the methods.  For example, I would like to call the handler defined in the bot with mocked parameters. 
 Looking at the docs I can see the following signature is expected for the MessageCreate event handler:

    Session.AddHandler(func(s *discordgo.Session, m *discordgo.MessageCreate) {})

However, both `discordgo.Session` and `discordgo.MessageCreate` appear to be defined as `struct` instead of `interface`, so I cannot just create a new type with the same signature.  I also appear to be unable to override the methods of a real instance of either as they are defined in a different package.

I'm thinking I need to abstract the discordgo package to achieve what I want, but I was wondering if I am simply doing something wrong and there is a simpler way to do this?

**Comment by robbix1206** [comment]
What do you want to test ?
If you want to test your handler functions, you can pretty easily create a discordgo.MessageCreate as it is a public struct type with simple data fields, no function around this type.
However discordgo.Session will be harder to recreate as it implement pretty all data around the current session (like messages in channels), and have his own functions.
This said, you can produce your own instance of discordgo.Session and discordgo.MessageCreate in your test file.

**Comment by GeekyDeaks** [comment]
Thanks for getting back to me @robbix1206 !

We would like to check that the bot responds correctly to a message event.  This might be something as trivial as ignoring the message and never calling `Session.SendMessage()`.  For slightly more complex tests, it would involve sending back specific responses for methods that interrogate the guild. For example we would want to return a `Channel` struct from `Session.Channel()` and confirm that the bot responded correctly depending on the name of the channel. e.g. if it the message started with `!lfg` and the channel name does not start with `lfg_` it should send an error message via `Session.SendMessage()`.

Unfortunately, I have not been able to work out how to override the methods to enable this.

I thought we would also have the same problem with `MessageCreate` as it appears to contain a pointer to `Message` and we would want to override the `ContentWithMoreMentionsReplaced` method, but I noticed that there is a test for this method in `https://github.com/bwmarrin/discordgo/blob/master/message_test.go` and I'm now investigating how that test works to see if that will help with `Session` too.

**Comment by iopred** [comment]
The test you mentioned is a better direction to go down.

Testing that events make their way through Discordgo doesn't help to verify
your own code, what you want to do is test your handlers, so I would
suggest something like:

To test
```
func onMessage(s *discordgo.Session, m *discordgo.MessageCreate) {
}
```
I would just do:
```
// Create instances and set up session state.
s := &discordgo.Session{StateEnabled: true, State: NewState()}
m := &discordgo.MessageCreate{
  Message: &discordgo.Message{
    ID:        "messageid",
    Content:   "!ping",
    ChannelID: "channelid",
    User:      &discordgo.User{
      ID:       "userid",
      Username: "Test User"
    },
  }
}
// Test message handler.
onMessage(s, m)
```

**Comment by GeekyDeaks** [comment]
Hi @iopred, thanks for advice - I'll try it out.

Just to be clear - I was not wishing to test if events made their way through discordgo, just that the bot attempted to make the correct calls to discordgo, with the correct parameters, based on the message input.

**Comment by iopred** [comment]
Ah, that might be harder to verify, you can set session.Client and use your
own http client to verify the correct requests were made, unfortunately it
won't be as clean as verifying method calls on session directly.

**Comment by GeekyDeaks** [comment]
That makes sense - I'll check it out and see what the effort is.  It could also ensure the call to discordgo is correct I guess, although I was not intending to go quite that far.  The only other thing I can think of is to create a really light abstraction layer to discordgo.  I was thinking of doing this anyway as I would like some helper methods on the structs. e.g. `Guild.GetChannel()` to get a ChannelStruct based on an ID or channel name just for a specific guild.

Cheers for the advice!

**Comment by bwmarrin** [comment]
@GeekyDeaks hey just checking in, how's your testing going? Do you have any more questions or is it safe to close out this issue?

**Comment by GeekyDeaks** [comment]
Hi @bwmarrin - sorry - only just seen this.  Yes, we ended up abstracting the library with a small layer that uses interfaces.  I'll close this one.  Thanks for your help!
