### ISSUE TITLE
How can I check if my bot has the permission to send message to a particular channel?

### ISSUE THREAD

**Issue by akritrime** [bwmarrin/discordgo#565]
I wrote this function but it doesn't seem like it works.

```
func checkPermission(s *discordgo.Session, userID string, channelID string) bool {
    p, err := s.State.UserChannelPermissions(userID, channelID)
    return (err == nil) && (p&dg.PermissionSendMessages == dg.PermissionSendMessages)
}
```
Edit: used the channelID properly

**Comment by iopred** [comment]
What is v? You're not using the channelID to check permissions.

**Comment by akritrime** [comment]
@iopred sorry, I actually stripped the code and forgot to change the `v` bit. v is actually an instance of type `Channel`.
