### ISSUE TITLE
Add support for message embeds

### ISSUE THREAD

**Issue by bwmarrin** [bwmarrin/discordgo#58]
Currently Message embeds are not kept.  Need to create the proper struct for them so they can be used.

**Comment by iopred** [comment]
I can't trigger a message with these anymore.

However, it seems like they are simply OEmbed objects, so the spec is pretty well known.

**Comment by iopred** [comment]
Ok, it seems they only happen on message edits.

I've rolled this into my attachments PR.

**Comment by bwmarrin** [comment]
Closed by SHA:9376774db8d4eb584e8ef9d34c23f57d5d6996ee
