### ISSUE TITLE
Finalize API

### ISSUE THREAD

**Issue by bwmarrin** [bwmarrin/discordgo#60]
The API is still in a bit of a flux and needs to be finalized at some point before we can issue a 1.0.0 release.  I am open to thoughts on this to help decide the best way to accomplish this goal.  See below :)
- Function names to closely match whatever Discord itself calls something as well as match the Discord endpoint used by the function. 
- Functions should be named in the format of CategoryAction so GuildAdd instead of AddGuild.
- Functions should be named without a trailing s when only one item is returned:  Guild(id) vs Guilds(id). however if it returns an array it should contain the trailing s: UserGuilds() vs UserGuild()

The way that our main Struct is laid out is the main point where I'm open to discussion.

Currently, pretty much everything is just thrown into the big Session{} struct.  On one hand that makes it so we don't have overly long names when accessing things.  On the other hand, we have one big messy struct with dozens of funcs, variables, etc.  Also it makes it harder to have consistent naming in some cases.

The other idea is that we split up the package into categories of concerns.  As I see it right now we could possibly have 3 separate categories:
- HTTP Endpoints (restapi.go)
- "Data" Websocket (wsapi.go)
- Voice (voice.go)  -- has both Voice.WS and Voice.UDP as sub-concerns.

The HTTP Endpoints and Data Websocket could possible be paired together in some fashion or make entirely separate.

The idea is that you would have commands, such as

Right now I've been working on the Voice struct since it's not used much and I feel better about changing it.  The direction I am going would create commands like.

```
Discord.Voice.WS.Open()
Discord.Voice.WS.Heartbeat()
Discord.Voice.WS.Ready   // bool
Discord.Voice.WS.Listen()

Discord.Voice.UDP.Open()
Discord.Voice.UDP.Heartbeat()
Discord.Voice.UDP.Ready  // bool
Discord.Voice.UDP.Listen()
```

And so on, this lets me use the same names for a lot of things but have them separated into their own structs.

**PLEASE** Comment with ideas.  This is my first API package so I might be looking at this all wrong.

**Comment by mammothbane** [comment]
Biggest thing that hits me, just from a code/docs readability standpoint, is the number of closures on `Session` that do almost the exact same thing but are handled differently and have different signatures. Also, there's currently no capability to register multiple handlers for one event. Ideally we'd look at something like this instead:

```go
type EventType string

const (
    EventMessageCreated EventType = "EVENT_MESSAGE_CREATED"
    EventMessageEdited            = "EVENT_MESSAGE_EDITED"
    /* . . . */
) 

type Event struct {
    Type EventType
    /* . . . */
}

type EventHandler func(*Session, interface{}) error

type Session struct {
    handlerMap map[EventType][]EventHandler // replaces OnEvent, OnReady, OnMessageCreated, etc.
    /* ... */
}

func (s *Session) RegisterEventHandler (f EventHandler, t EventType) {
    handlers := append(s.handlerMap[t], f)
    s.handlerMap[t] = handlers
}

var typeMap = map[EventType]reflect.Type {
    EventMessageCreated: reflect.TypeOf(Message{}),
    EventMessageEdited:  reflect.TypeOf(Message{}),
    /* ... */
}

func (s *Session) HandleEvent(e *Event) {
    switch e.Type {
        /* [handle state updates] */
    }

    r := reflect.New(typeMap[e.Type]).Interface()
    err := unmarshalEvent(e, r)
    v := reflect.Indirect(reflect.ValueOf(r))

    for _, f := range s.handlerMap[e.Type] {
        n := reflect.New(typeMap[e.Type]).Set(v)
        f(s, n.Interface())
    }
}
```

Sorry if that's a lot of code for a comment. Perhaps this belongs in a PR. Either way, I haven't tested the `reflect` magic, but I'm pretty sure that's at least close to working, and it'd clean up the `Session` struct a lot and also simplify switching logic for event handling.

**Comment by bwmarrin** [comment]
Thanks for the comment, I'll think about how this would effect things and come back here with my thoughts :)

**Comment by iopred** [comment]
@mammothbane I think handling the events better is a good idea, my proposal is similar, but it also boils down to a map, keyed on event type -> event handler.

Instead of registering all the different types of message events, we would be more explicit with our event types, eg:
type CreateMessageEvent struct{
  Message
}

This makes the API a little more explicit, and allows a very simple channel based API also which would look like:

e := <- session.MessageChan

switch (e.type) {

}

**Comment by mammothbane** [comment]
@iopred Somewhat torn on this. On one hand, it does simplify the API in certain ways. On the other, we already have an event loop that switches on message type, so having the user create their own seems redundant and likely to introduce complexity in the case of a client crash/disconnection. Also, creating a bunch of struct types does move bloat out of `Session` but doesn't actually reduce it appreciably.

**Comment by iopred** [comment]
Bloat is functionality for no reason, having types for each message adds value by being more explicit, but mainly it allows the ability to send events down a channel.
I don't think the crash/disconnection case is really a worry, events would/could be delivered down a channel in order, and could include the disconnect/connect messages also.

The downside of your proposed solution is that the handlers for each event need interface arguments. eg:

```
func onMessageCreate(s *discordgo.Session, i interface{}) {
  m, ok :=  i.(*discordgo.Message)
  // do something with m.
}
```

I do see the advantage of only needing to unmarshal in a single location, I think that would make a terrific PR, but if we're to maintain reasonable arguments to event handlers, it's hard to move away from a rather large switch statement.

**Comment by mammothbane** [comment]
Okay, I suppose I agree. `interface{}` doesn't seem like that much of a big deal to me, but that's probably just because it's how I might do something internal that I could document and fully control. Probably doesn't belong in a public-facing API. 

As to the channels, this will mean a paradigm shift on the user side&mdash;i.e. moving from registering handlers and calling `Open` to having the main body of the program be an event loop. I think this would be okay, it would just represent a significant change.

**Comment by mammothbane** [comment]
@bwmarrin Perhaps we could also look at having the voice API use a channel? It'd be great to be able to just send PCM that way rather than having to load from a file.

**Comment by bwmarrin** [comment]
Yeah, the voice definitely needs more flexibility.  I think having a channel option would be great.  I was trying to get a receive working but haven't been able to devote a lot of time on it lately.

**Comment by iopred** [comment]
@mammothbane I wouldn't want the channel to be the only way to get at the events, it would be optional.

**Comment by iopred** [comment]
@mammothbane, I have done a lot of thinking on this and have finally come to (what I think is) a quite elegant solution.

https://github.com/bwmarrin/discordgo/pull/109

It uses a map and reflection to call handlers as you suggested, but I have simplified the registration step and allowed the handler code to still be strongly typed.

**Comment by bwmarrin** [comment]
Also @mammothbane I did add channels to the voice side.  For OpusSend OpusRecv in the main package, PCM send/recv in the dgvoice package.  Works well.
