### ISSUE TITLE
Track member Count 

### ISSUE THREAD

**Issue by Biospheere** [bwmarrin/discordgo#601]
Track the number of members while session.StateEnabled is enabled.

**Comment by Soumil07** [comment]
I have attempted to fix this in [#602](https://github.com/bwmarrin/discordgo/pull/602)

**Comment by roberthmiller** [comment]
@iopred @bwmarrin I think this issue can be closed since the PR has been merged

**Comment by Biospheere** [comment]
But unfortunately the PR has not solved the problem... Now guild.MemberCount is always 0
