### ISSUE TITLE
Incorrect handling of WSAPI errors

### ISSUE THREAD

**Issue by iopred** [bwmarrin/discordgo#61]
et Listen Error read tcp 10.1.10.17:49656->45.79.158.60:443: wsarecv: A connection attempt failed because the con
nected party did not properly respond after a period of time, or established connection failed because connected host ha
s failed to respond.
panic: close of nil channel

goroutine 39 [running]:
github.com/iopred/discordgo.(*Session).Listen(0xc0821ea1e0, 0x0, 0x0)
        D:/Documents/Go/src/github.com/iopred/discordgo/wsapi.go:133 +0x3ed
created by github.com/iopred/discordgo.New
        D:/Documents/Go/src/github.com/iopred/discordgo/discord.go:115 +0x652

**Comment by iopred** [comment]
This may have been fixed with my channel cleanup, I haven't seen it in a while.

**Comment by bwmarrin** [comment]
Same here, I haven't had it either.
