### ISSUE TITLE
Support for sending files over webhooks?

### ISSUE THREAD

**Issue by jl91569** [bwmarrin/discordgo#617]
Is it possible to have some way to send files over webhooks?

This would help with running chat relays/bridges as there wouldn't be a need for an external file host. Sorry if this is already a feature, I asked in the support server and was told DiscordGo probably doesn't support it right now.

Thanks :)

**Comment by iopred** [comment]
https://godoc.org/github.com/bwmarrin/discordgo#Session.WebhookExecute specifically the File field.

**Comment by rumblefrog** [comment]
As per spec, it requires `multipart/form-data` instead of the normal `application/json` that `RequestWithBucketID` uses. In turns, this requires additional data to be sent with `payload_json`. `ChannelMessageSendComplex` implements this, however WebHookExecute does not.

**Comment by jl91569** [comment]
OK, thanks again :)

**Comment by aswinmprabhu** [comment]
@rumblefrog  I want to do the same thing (send an image over a webhook) and can't figure out how!
`WebhookParams` has a `File` field that takes a string. How can I use this? Is there no way to upload a file using `WebhookExecute`?

**Comment by rumblefrog** [comment]
@aswinmprabhu Just construct the payload yourself, set the proper header and use the optional `payload_json` if want to pass additional data.

Discord documentation: https://discordapp.com/developers/docs/resources/webhook#execute-webhook
