### ISSUE TITLE
Presences seem to be incorrect

### ISSUE THREAD

**Issue by Bios-Marcel** [bwmarrin/discordgo#623]
Hey,

When retrieving a guild via `*discordgo.Session.Guild` and adding it to the sessions state, the `Presences` field doesn't contain a `Presence` instance for every user. Is this correct? Because if so, I don't know how to retrieve all online users.

**Comment by Soumil07** [comment]
You can't retrieve all online users the bot can see/has cached. Instead, you should be filtering online users from (*discordgo.Guild).Members

**Comment by iopred** [comment]
Call Session.RequestGuildMembers to cause Discord to send you more Members
over the WebSocket.

**Comment by Bios-Marcel** [comment]
`discordgo.Member` doesnt have any relevant fields that indicate online status, I checked that already. 

https://github.com/bwmarrin/discordgo/blob/8325a6bf6dd6c91ed4040a1617b07287b8fb0eba/structs.go#L600

Getting those was no probably anyhow, I have been that far, but as far as I can see, only Presence hokd the onlinestate.

**Comment by Bios-Marcel** [comment]
Oh btw, I kinda forgot to post updates on this. I already use `session.RequestGuildMembers`, but some Presences are still not available, I don't quite get why.

**Comment by CarsonHoffman** [comment]
If Discord hasn't sent a presence for a certain user, there's nothing we can feasibly do. This seems like more of an issue with how the API acts than our library.
