### ISSUE TITLE
Error unmarshalling UserGuildSettings

### ISSUE THREAD

**Issue by Bios-Marcel** [bwmarrin/discordgo#624]
I get this during startup of my application. It only happens for me, it works fine for a mate of mine, we both have the same codebase.

```
2019/01/23 20:02:20 [DG0] wsapi.go:552:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field UserGuildSettings.guild_id of type string
```

This sadly keeps me from accessing the state, as it's empty :<

If you need any additional information, tell me.

**Comment by iopred** [comment]
In general we try not to support User Bot usecases anymore, a custom
implementation of UnmarshalJson for UserGuildSettings could fix
this problem though.

**Comment by Bios-Marcel** [comment]
Well, then I'll simply write a workaround ...

**Comment by henesy** [comment]
@Bios-Marcel what was your workaround, I am also running into this

**Comment by Bios-Marcel** [comment]
I made GuildID an `interface` and wrote a getter method that gives a string.

**Comment by CarsonHoffman** [comment]
Given that this is only relevant to the user API, I'm going to go ahead and close this.
