### ISSUE TITLE
wsapi error on connection

### ISSUE THREAD

**Issue by howdoicomputer** [bwmarrin/discordgo#627]
```
2019/02/01 12:42:47 [DG0] wsapi.go:304:heartbeat() error sending heartbeat to gateway wss://gateway.discord.gg/?v=6&encoding=json, websocket: close sent
```

I've been getting this error. I don't know what's causing it and it's not actually affecting my application but it is showing up.

**Comment by bwmarrin** [comment]
I'm not sure if you're still having this problem - if so please re-open this.  Otherwise, since it's been a year and so much has changed I'll guess this isn't even relevant anymore.

**Comment by kpfaulkner** [comment]
Only just starting to use discordgo and I'm also getting that message once the connection has been open a while (what "a while" is, have yet to be determined). Am wondering if I need to keep a goroutine running purely for heartbeat responses?
