### ISSUE TITLE
Can't Reorder.

### ISSUE THREAD

**Issue by ktrinanm** [bwmarrin/discordgo#630]
Hello, I am trying to reorder roles for my bot to be at the top so that it can add member roles, but when I call it, I get

> Failed to reorder roles {} HTTP 400 Bad Request, {"1": ["Only dictionaries may be used in a DictType"], "2": ["Only dictionaries may be used in a DictType"], "3": ["Only dictionaries may be used in a DictType"], "4": ["Only dictionaries may be used in a DictType"], "5": ["Only dictionaries may be used in a DictType"], "6": ["Only dictionaries may be used in a DictType"], "7": ["Only dictionaries may be used in a DictType"], "8": ["Only dictionaries may be used in a DictType"], "9": ["Only dictionaries may be used in a DictType"]}

The "Failed to reorder roles {}" is from me. I can see this error isn't coming from this library, but I would guess that it's coming from how the library is changing the role list...

The Code on my side is 

```
 40         for _, server := range servers {
 41                 roles, _ := discord.GuildRoles(server.ID)
 42 
 43                 if roles[0].Name == "YeetsMcGee" {
 44                     continue
 45                 }
 46 
 47                 var role *discordgo.Role
 48                 newRoles := make([]*discordgo.Role, len(roles))
 49                 for _, v := range roles {
 50                     if v.Name == "YeetsMcGee" {
 51                         role = v
 52                         continue
 53                     }
 54                     fmt.Println("Role {}", v)
 55                     newRoles = append(newRoles, v)
 56                 }
 57 
 58                 if role == nil {
 59                     return
 60                 }
 61 
 62                 _, err := discord.GuildRoleReorder(server.ID,
 63                     append([]*discordgo.Role{role}, newRoles...))
 64 
 65                 if err != nil {
 66                     fmt.Println("Failed to reorder roles {}", err.Error())
 67                 }
 68             }
```

If it's something in my implementation, please let me know. I haven't used Go in a few years, so I may have a stupid error that I'm not seeing.... Thanks!

**Comment by dannyroes** [comment]
Ran into this myself today. I've figured out that the Discord API returns this error if one of the roles in your slice is nil.

**Comment by CarsonHoffman** [comment]
With the follow-up this seems to be an issue with the usage of the library. If you're still running into this issue and have a more straightforward repro, feel free to re-open.
