### ISSUE TITLE
Get all guilds and channels the bot is connected to?

### ISSUE THREAD

**Issue by Bauke** [bwmarrin/discordgo#637]
I noticed in `state.go` there's a couple maps that have these but they're not exported:

https://github.com/bwmarrin/discordgo/blob/8325a6bf6dd6c91ed4040a1617b07287b8fb0eba/state.go#L44-L46

I looked around and from what I can figure out the only way to find any given channel/guild is if you have their ID.

**Comment by Hinara** [comment]
I may have stay like that because there was no common use case of having the full dictionnary of Guilds/Channels and Members.
Do you have a specific case where you need this kind of informations ?

**Comment by Necroforger** [comment]
The State struct anonymously embeds the [Ready](https://godoc.org/github.com/bwmarrin/discordgo#Ready) struct, which Is sent when you bot connects. the `Guilds` field should contain all the guilds your bot is in.

This field should be updated live in the state when a Guild is added or removed. If you want to read from it without the chance of a race condition you could use the methods `State.RLock` and `State.RUnlock` given by the embedded RWMutex.

**Comment by Bauke** [comment]
@Hinara some uses where this could come in handy:

- Displaying how many Guilds/Channels/Members the bot is serving.
- Being able to find a Guild/Channel/Member by their name, tag or something other than ID.

@Necroforger a day after I made the issue I found that, yeah. It would be nice to have Channels and Members also available like that though. For example, right now to find a particular channel by something other than ID you'd have to iterate over all the Guilds and then iterate over all the Channels. It's not too bad to do but having it available directly would be nice.

**Comment by Necroforger** [comment]
If you know the guild by ID you could also use the session.Guild function

**Comment by CarsonHoffman** [comment]
I think the library provides enough functionality in this respect; you can get all guild channels your bot sees by iterating over guilds (which makes sense semantically), and since Discord no longer sends private channels over the gateway that's all that is necessary.
