### ISSUE TITLE
[Question] How can I increase the verbosity of logging?

### ISSUE THREAD

**Issue by bkuhl** [bwmarrin/discordgo#638]
I'm new to Go and am tinkering with a Discord bot.  My bot is losing its connection sometimes and am not seeing anything in my logs.  How can I increase the verbosity of logging, I think in the [Session](https://godoc.org/github.com/iopred/discordgo#Session).

**Comment by shawntoffel** [comment]
Session.LogLevel is an int. You can set it to any of the constants defined here: https://godoc.org/github.com/iopred/discordgo#pkg-constants

Example:
`session.LogLevel = discordgo.LogInformational`
