### ISSUE TITLE
Feature Request: Use a different logger?

### ISSUE THREAD

**Issue by MostHated** [bwmarrin/discordgo#650]
Hello all,
  I do apologize if this is an easy answer, I am still learning Go. How can I go about making all logging output use a different logger than the standard one that Discordgo is using? I tried to use Logrus, but it only works for logs I explicitly create with it. I even tried to find a script that certainly looked like it should make all logs use Logrus (had hooks and writers, etc), but unfortunately it didn't. Is there a way to accomplish this?

Thanks,
-MH

**Comment by MostHated** [comment]
After searching for quite some time and trying lots of different things, I would like to put in a feature request to simply make it easier to swap out the discordgo.Logger entirely for another one. The work around I found to do this is *way* more complicated than it should be, and involves multiple steps now per individual log message if you want to also retain application wide alternative logging.

**Comment by Soumil07** [comment]
You have to override the function `discordgo.Logger(msgL, caller int, format string, a ...interface{})` to replace the standard logging.

**Comment by bwmarrin** [comment]
@MostHated,

You need only override the Logger variable here to use your own custom logger.

https://github.com/bwmarrin/discordgo/blob/master/logging.go#L37
