### ISSUE TITLE
Handle invalid credentials

### ISSUE THREAD

**Issue by nstafie** [bwmarrin/discordgo#66]
If the credentials passed are invalid and the API response does not include a token field, it fails to cast a nil interface to string and a panic occurs.

**Comment by bwmarrin** [comment]
Thanks @nstafie.  Will fix.  Need to modify it so it receives into a small struct instead of that evil map.

**Comment by bwmarrin** [comment]
SHA: 30252123a02ab76a8f6292491281daa782239bde does not fix this issue.
