### ISSUE TITLE
Project logo makes me cry

### ISSUE THREAD

**Issue by lexfrei** [bwmarrin/discordgo#664]
Hello! I'm using Dark Reader addon in my browser.
So, I can see this. This outer glow is painful to watch.

![image](https://user-images.githubusercontent.com/1366514/59779948-db791600-92c1-11e9-9939-ddc1018f6e1b.png)

JFY, feel free to resolve.

**Comment by MostHated** [comment]
Such is the plight of dark themes. You get used to it after a while.

**Comment by shaned24** [comment]
No qualms here

![image](https://user-images.githubusercontent.com/3876809/61572539-5f781680-aa97-11e9-822f-9d57e0c3d3ff.png)

**Comment by recapitalverb** [comment]
Please close this issue since it seems that it has been resolved.
