### ISSUE TITLE
Unable to specify guild_subscriptions in Identify

### ISSUE THREAD

**Issue by bkuhl** [bwmarrin/discordgo#678]
When identifying with the gateway, there's an option in the API to specify `guild_subscriptions` which disables receiving certain events.  It'd be fantastic if we had the ability to specify this in the `Identify` struct: https://github.com/bwmarrin/discordgo/blob/8d8906ce4b959dacabfefbad9bacf11b6ffd8035/wsapi.go#L735

**Comment by bwmarrin** [comment]
I think maybe we could export an Identify struct that exposes all of these settings as some of them are exposed in other fashions now, and yet some others might be nice to be configurable.  We could default the values on New(), but allow you to customize it before calling Open()

**Comment by bwmarrin** [comment]
@bkuhl I've created a proposed solution, please feel free to test it out and provide your feedback.

**Comment by bkuhl** [comment]
Sorry I meant to follow up with this.  Thanks so much for tackling it.
