### ISSUE TITLE
Member.GuildID is an empty string

### ISSUE THREAD

**Issue by Lukaesebrot** [bwmarrin/discordgo#692]
Hello. I created the following structure:
```go
func ExecuteCommand(session *discordgo.Session, event *discordgo.MessageCreate) {
    member, err := session.GuildMember(event.GuildID, event.Author.ID)
    if err != nil {
        panic(err)
    }
    fmt.Println("ID:", member.GuildID)
}
```

and it prints me `ID: ` in the console.
I can't explain why this happens and I think this is an actual bug, but I'm not sure. Does somebody else have this problem?

**Comment by JurrijnP** [comment]
It seems `guild_id` is not even present in the member object from Discord, so that explains why it remains empty.

The `GuildID` field should be removed from the `Member` struct.

**Comment by Lukaesebrot** [comment]
After I rewrote my code and used the `Session.State.Member()` function in every normal case and the `Session.GuildMember()` function only as fallback, the `GuildID` field works as expected. So I think this is an issue with the `Session.GuildMember()` function itself.

**Comment by JurrijnP** [comment]
It seems the `GuildID` only gets filled by the state, I think it would be a good idea to add a comment this does not get filled by the endpoint.
But that is something for a PR

**Comment by Lukaesebrot** [comment]
Or at least implement a wiki page that explains why this function does not fill the `GuildID` field and a code example that shows how to fetch the Guild ID in another way.

**Comment by Lukaesebrot** [comment]
I added a small FAQ entry about this topic and I hope it won't get deleted :D
