### ISSUE TITLE
func UserAvatar() should return a pointer

### ISSUE THREAD

**Issue by bwmarrin** [bwmarrin/discordgo#70]
To match other recent changes and keep consistency the restapi.go func UserAvatar() should return a pointer to a User{} struct.

https://github.com/bwmarrin/discordgo/blob/develop/restapi.go#L186

**Comment by bwmarrin** [comment]
Closed be SHA: 00cd5cb178d50980f68bd400bde37bd002b22b4d

**Comment by bwmarrin** [comment]
Hmn, I lied.  This still needs to be checked into @iopred  should that send a pointer to the img?  Not sure quite how that package works yet :)

**Comment by iopred** [comment]
UserAvatar returns an image.Image which is an interface, so it does not need a pointer.

**Comment by bwmarrin** [comment]
Well, then, that was quick.
