### ISSUE TITLE
ChannelVoiceJoin locks up forever

### ISSUE THREAD

**Issue by duncanleo** [bwmarrin/discordgo#701]
When I make a call to `ChannelVoiceJoin` in my Discord bot, the function call will be stuck forever and never return a `VoiceConnection` struct. I've tried implementing it the manual way (using `ChannelVoiceJoinManual` and manually looping through `Session.VoiceConnections` afterwards) but it doesn't work - the library seems to never receive/track any resulting `VoiceConnection`. I did notice though that there was a `VoiceStateUpdate` received by the library.

Using `LogLevelDebug` did not yield any relevant logs.

**Comment by duncanleo** [comment]
The function seems to work again once I had requested a new IP from my ISP. Does Discord do IP-based rate-limiting on the voice server?

**Comment by duncanleo** [comment]
After some time, the function has started to lock up again. After checking through the `discordgo` source, I found that it was stuck on the second loop in the `VoiceConnection.waitUntilConnected()` method - specifically, it was getting stuck at the call to `v.RLock()`.

**Comment by dhannyz** [comment]
I'm experiencing this same problem. It seems either discord is actively denying voice connections from bots written using this, or they have changed their connection flow slightly

**Comment by Crypto90** [comment]
Related to this issue?:
https://cdn.discordapp.com/attachments/454634627340959746/601167109031985189/Screenshot_20190717-174315_Discord.png

**Comment by Crypto90** [comment]
Should be related to this:
https://cdn.discordapp.com/attachments/454634627340959746/601167109031985189/Screenshot_20190717-174315_Discord.png

**Comment by dondish** [comment]
I found out that the call gets stuck [here](https://github.com/bwmarrin/discordgo/blob/e33a993fd7f8f3c64d40f7c9932d5bdf39a180ac/voice.go#L574).

**Comment by dondish** [comment]
I fixed the issue [here](https://github.com/bwmarrin/discordgo/pull/703) I hope it will get merged soon.
