### ISSUE TITLE
Error with wsHeartbeat: "close sent"

### ISSUE THREAD

**Issue by Vindexus** [bwmarrin/discordgo#702]
I'm seeing this error constantly since yesterday.

`voice.go:496:wsHeartbeat() error sending heartbeat to voice endpoint us-east247.discord.media:80, websocket: close sent`

Does anyone know if this is a Discord issue?

**Comment by dhannyz** [comment]
@Vindexus Same issue, it's due to the lockup in #701

**Comment by dondish** [comment]
I fixed the issue [here](https://github.com/bwmarrin/discordgo/pull/703) I hope it will get merged soon.
