### ISSUE TITLE
New Git Tag for v0.20.2

### ISSUE THREAD

**Issue by ewohltman** [bwmarrin/discordgo#719]
Hello again,

The master branch of discordgo was recently updated to include a patch for Discord's API returning a `400: Bad Request` when the `Content-Type` header is set but request body is empty.

Could a new git tag for v0.20.2 be created so that new Go projects using Go modules will get the latest patch when they `go get` the repository, as well as make it clear to existing projects that a new version is available to `go get`?

This would help to keep developer experience smooth by being able to do something like:

`go get -u github.com/bwmarrin/discordgo`

Instead of:

`go get -u github.com/bwmarrin/discordgo@master`

Thanks!

**Comment by CarsonHoffman** [comment]
Thank you for the suggestion; admittedly I'm fairly new to the project (and using modules on a published project) and I hadn't considered doing that. Sorry for giving you the run-around with this issue, but the tag is now up!
