### ISSUE TITLE
[Feature Request] Add Handler For Reactions On Change Or Get Updates

### ISSUE THREAD

**Issue by felixfong227** [bwmarrin/discordgo#736]
Disclaimer: I am quite new to the Go scene, so I have no idea what I am talking about, please bear with me 🙇

---
Is it possible that we will get a new handler for listening for the changes for a specify message's reactions?

For example, this is a [refence](https://discordjs.guide/popular-topics/reactions.html#awaiting-reactions) from DiscordJS library

Because I would love to make a bot with the ability to do some actions with a more friendly UI, hands down the help of the reaction system, I can make some sort of button-like system.

**Comment by bwmarrin** [comment]
There are reaction events for Add/Remove/RemoveAll

https://github.com/bwmarrin/discordgo/blob/master/events.go#L174-L188

So you can use AddHandler method to add a handler that would get sent these events.

**Comment by felixfong227** [comment]
Thank you very much, I managed to get what I needed and up and running 😄
