### ISSUE TITLE
is there any discordgo way to escape discord format strings/characters?

### ISSUE THREAD

**Issue by jxsl13** [bwmarrin/discordgo#740]
is there any discord way to escape discord format strings/characters?

like * or any other that cause discord to format stuff, if the input contains such characters.

**Comment by Harmon758** [comment]
You can use backslash, `\`, the fairly universal way to escape characters.
This isn't specific to DiscordGo.

**Comment by jxsl13** [comment]
Is there any list of all the characters that need escaping in discord messages, that might cause formatting to change?

**Comment by Harmon758** [comment]
[Discord uses Markdown](https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-).
Again, this isn't specific to DiscordGo.
