### ISSUE TITLE
Sudden slow response time to the Discord API

### ISSUE THREAD

**Issue by chand1012** [bwmarrin/discordgo#745]
I have been developing my discord bot in Go with DiscordGo for the past nine months with no issues whatsoever. All of a sudden the response time on requests has been extremely slow. It takes one to two seconds to reach the bot if it does at all. I tried switching computers, switching networks (went from my home network to a VPS I have in the cloud) and nothing worked. All of the code can be found [here](https://github.com/chand1012/Discord-Quick-Meme/). This has been running flawlessly for months, and it ran fine at the last commit on a test bot. Does anyone have any insight or reasons that this could be happening?

**Comment by chand1012** [comment]
I have also noticed that the bot intermittently restarts itself, where it will go offline and then reconnect, but the logs on the server do not show it.

**Comment by JurrijnP** [comment]
This was probably caused by some high response times from the API.

You can see it had some spikes few hours back:
https://status.discordapp.com

So nothing on your end :)

**Comment by chand1012** [comment]
Well the problem is and has been persisting since Monday afternoon. I have a goroutine that runs in the background and collects all the channel names and caches them, and it is taking well over 20 seconds to execute, when before it took at most five. I am also randomly getting this error:
```
Error attempting to set the status.: no websocket connection existspanic: no websocket connection exists.
```
Which leads me to believe that the bot is having issues connecting to the Discord API. A few latency spikes wouldn't cause this for three days straight, and the code has been running fine for weeks now.

**Comment by chand1012** [comment]
> @chand1012 are you still having this issue?

No, I was able to fix it by cleaning up my code base and improving threading support. #746 mentions the underlying error, and I was able to remedy it.
