### ISSUE TITLE
Add clarifying docs for using an OAuth2 token

### ISSUE THREAD

**Issue by fsufitch** [bwmarrin/discordgo#749]
While the existing docs for the `New(...)` function say that the token is used "blindly", and specify that a `Bot ` prefix is necessary for bot tokens, they are not clear that if a single string argument is passed in, it gets passed through to the HTTP Authorization header untouched. They also do not mention the knock-on effect of that, which is that an OAuth2 access token must be prefixed with `Bearer ` when passed into `New(...)` in order to work.

**Comment by fsufitch** [comment]
PR: https://github.com/bwmarrin/discordgo/pull/748

**Comment by ewohltman** [comment]
The associated PR was merged so this issue might be eligible to be closed.

**Comment by fsufitch** [comment]
Closing since PR was merged.
