### ISSUE TITLE
Missing error handling

### ISSUE THREAD

**Issue by Incisive** [bwmarrin/discordgo#775]
Is there any reason this section is missing proper error handling / returning of errors?

https://github.com/bwmarrin/discordgo/blob/master/restapi.go#L387-L396

**Comment by CarsonHoffman** [comment]
In what way is this missing returning of errors? The library itself doesn't have any sensible way to deal with an application-level error (more HTTP-centric errors like 429s are already handled upstream), so it simply passes it onto the caller.

**Comment by Incisive** [comment]
Disregard, I wasn't aware GO supported named returns.  I've been trying to track down an issue where the library hangs and I get no return value (or return at all for that matter).  I'll make another issue if I'm unable to figure it out.
