### ISSUE TITLE
Cannot add new emoji

### ISSUE THREAD

**Issue by 0xSteeW** [bwmarrin/discordgo#778]
I'm trying to add an image that I saved in my code as a []byte. I base64 encode it using base64.StdEncoding.EncodeToString([]byte), send it with client.GuildEmojiCreate() , and I get a 400 response: HTTP 400 Bad Request, {"image": ["Only data uri strings can be used."]}. Any help would be appreciated.

**Comment by CarsonHoffman** [comment]
The data URI scheme mentioned in the error is described in the [Discord documentation](https://discord.com/developers/docs/reference#image-data). Make sure that your string conforms to this format with the correct name of your image’s encoding scheme.

**Comment by 0xSteeW** [comment]
Thanks a bunch, finally solved it by doing:
```go
var img []byte
fileType := http.DetectContentType(img)
b64 := base64.StdEncoding.EncodeToString(img)
dataURI := fmt.Sprintf(`data:%s;base64,%s`, fileType, b64)
_, err := client.GuildEmojiCreate(message.GuildID, "name", dataURI, nil)
```
