### ISSUE TITLE
Client User property missing?

### ISSUE THREAD

**Issue by nikooo777** [bwmarrin/discordgo#779]
Hello there,
I am using this library to build my own bot and I couldn't but seemingly notice the lack of a property for users:
https://discord.js.org/#/docs/main/stable/class/ClientUser?scrollTo=createdAt

Am I missing something or is this not supported in the current SDK?

Best regards,
Niko

**Comment by CarsonHoffman** [comment]
[This function](https://godoc.org/github.com/bwmarrin/discordgo#SnowflakeTimestamp) is applicable to any snowflake ID within the API, including user IDs.

**Comment by nikooo777** [comment]
Aha that is what I was missing! Thank you so much for your extremely fast reply. Have a great weekend :)
