### ISSUE TITLE
ChannelMessageSendComplex []File Only Sends a Single Image

### ISSUE THREAD

**Issue by adityaxdiwakar** [bwmarrin/discordgo#791]
After making a command to send multiple images through my bot, it appears only a single image is sent, when a [``discordgo.File``](https://godoc.org/github.com/bwmarrin/discordgo#File) slice is fed into [``ChannelMessageSendEdit``](https://godoc.org/github.com/bwmarrin/discordgo#Session.ChannelMessageSendComplex).

I have debugged as much as I could to no result, but to skip some debugging on your part (if this is a library issue, and not a shortcoming on my part), I'll elaborate below:

I have printed out the same slice of files prior to them being sent and the following is outputted as expected:
```
[0xc0001098c0 0xc000394c60 0xc0007a7f50]
``` 
However, the output of this is the bot only sending a single image, rather than the three images expected.

The code I am using to send the files is:
```go
var files []*discordgo.File

/* ---- code that populates the files slice omitted but goes here ----- */

log.Println(files) // prints out the above three addresses
s.ChannelMessageSendComplex(m.ChannelID, &discordgo.MessageSend({
    Files: files,
})
```

**Comment by CarsonHoffman** [comment]
I cannot reproduce:

```go
cat, _ := os.Open("cat.jpg")
dog, _ := os.Open("dog.jpg")
data := &discordgo.MessageSend{Files: []*discordgo.File{{Name: "cat.jpg", ContentType: "image/jpeg", Reader: cat}, {Name: "dog.jpg", ContentType: "image/jpeg", Reader: dog}}}
s.ChannelMessageSendComplex("412041421772685335", data)
```

<img width="413" alt="image" src="https://user-images.githubusercontent.com/19721219/87234352-f2dbe300-c39d-11ea-8b07-058a023ecfff.png">

Are you sure that all of your files have names, valid readers, and matching content-types (or omitted ones)?

**Comment by adityaxdiwakar** [comment]
Nice pictures. I will try again and report back using file names as well, that might be part of the problem. TIA.

**Comment by adityaxdiwakar** [comment]
Resolved, for anyone experiencing the same issue in the future, make sure to have **unique** names for each file in the ``discordgo.File`` struct, anyways. Thank you @CarsonHoffman, I appreciate the help.
