### ISSUE TITLE
[ERROR] - [DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_messag e_id of type string

### ISSUE THREAD

**Issue by coats1337** [bwmarrin/discordgo#792]
I've got this error while running discordgo in a user account, i attempted to ban multiple users (20 threads + 10 users)

I've even modified the user-agent through `Session.UserAgent`, which didn't work at all, it ended up unverifying my account and discord sending me a email to verify my account.

Error: `[DG0] wsapi.go:574:onEvent() error unmarshalling READY event, json: cannot unmarshal number into Go struct field ReadState.read_state.last_messag e_id of type string`

**Comment by CarsonHoffman** [comment]
Discord has made it quite clear that the use of user accounts outside of the official client is not sanctioned, and thus the user API (and more importantly its differences from the bot API) isn't documented; the library therefore does not strive to support this portion of the API that often changes without warning and provides no way to officially determine its interface. Changes that Discord makes to its user-facing API may manifest themselves in errors like the one you're seeing here.

In terms of your account being un-verified, the same line of reasoning applies. Discord deems the external use of user accounts as against its [community guidelines](https://discord.com/new/guidelines), and most likely has more advanced heuristics to detect the use of these accounts than simply checking the user-agent; I don't know what these are, and unfortunately won't be able to provide much help to that end.
