### ISSUE TITLE
MessageDelete event handler lacks BeforeDelete

### ISSUE THREAD

**Issue by Tediferous** [bwmarrin/discordgo#797]
Im trying to use an event handler to watch and log deleted messages in a server but the object comes back with no values (which makes sense since it no longer exists) but it also doesnt have the BeforeDelete attribute. This is my handler method.
```
func messageDelete(s *discordgo.Session, m *discordgo.MessageDelete) {
 
          res,_ := json.MarshalIndent(m, "", "  ")
          logrus.Debug(string(res))
}
```
and results in
```
 {
  "id": "0123456789",
  "channel_id": "0123456789",
  "guild_id": "0123456789",
  "content": "",
  "timestamp": "",
  "edited_timestamp": "",
  "mention_roles": null,
  "tts": false,
  "mention_everyone": false,
  "author": null,
  "attachments": null,
  "embeds": null,
  "mentions": null,
  "reactions": null,
  "pinned": false,
  "type": 0,
  "webhook_id": "",
  "member": null,
  "mention_channels": null,
  "activity": null,
  "application": null,
  "message_reference": null,
  "flags": 0
} 
```

Am I going about trying to get the beforeDelete message the wrong way?

**Comment by CarsonHoffman** [comment]
Are you tracking messages in the state? `BeforeDelete` relies on the data being present in the state; it isn't sent with delete events by the API, and we have no way of presenting that information outside of the state. Message caching is controlled by the [`State.MaxMessageCount`](https://pkg.go.dev/github.com/bwmarrin/discordgo?tab=doc#State.MaxMessageCount) property, which determines how many messages to keep in the state per channel.

**Comment by Tediferous** [comment]
Ah I see, thanks for clarifying. I misunderstood the object.
