### ISSUE TITLE
Add Support for /followers and /crosspost endpoints

### ISSUE THREAD

**Issue by adityaxdiwakar** [bwmarrin/discordgo#799]
As per https://github.com/discord/discord-api-docs/issues/1510, the `/followers` and `/crosspost` endpoints for news channels (now available to all servers, rather than just Verified/Partnered/Dev) is allowed to be accessed by bots. These endpoints are yet to be documented but the issue is labeled "documentation-needed" and there is an open PR for it as well, https://github.com/discord/discord-api-docs/pull/1692.

With that, it would be cool to see support for these endpoints within Discordgo, I would love to add these features myself, but want to open it for conversation beforehand.

Thoughts? Thanks in advance!

**Comment by CarsonHoffman** [comment]
I'd be fine with accepting support for this endpoint, given that it's confirmed to exist and there doesn't seem to be anything *wrong* about the linked PR at the moment. If something changes, we can fix it.

**Comment by adityaxdiwakar** [comment]
Great, I'll go ahead and add support and then open a PR in a few hours.
