### ISSUE TITLE
ChannelEdit RateLimitPerUser, doesn't turn off slow mode if value set to 0

### ISSUE THREAD

**Issue by Jirubizu** [bwmarrin/discordgo#809]
As the title says, if you set the RateLimitPerUser amount to 0 inside a ChannelEdit, it does not actually post correctly or update the channel data. Anything above 0 works fine so I can set the limit to 1 however if I want to turn it off its not possible.

**Comment by dylhack** [comment]
This is fixed by removing `omitempty` from RateLimitPerUser in ChannelEdit
https://github.com/bwmarrin/discordgo/blob/8c5ca3de95d7876ef7f36b4111d6bf4a0cf12ed5/structs.go#L307-L317
