### ISSUE TITLE
How to play sound

### ISSUE THREAD

**Issue by modeckrus** [bwmarrin/discordgo#813]
How to play sound, and please place it in example section

**Comment by zacharyburkett** [comment]
I believe you're looking for the "airhorn" example :)

https://github.com/bwmarrin/discordgo/tree/master/examples/airhorn

**Comment by tsdtsdtsd** [comment]
FYI: the mentioned repo to dca-rs seems to be removed. 
Is there any known working alternative or fork?

**Comment by bwmarrin** [comment]
https://github.com/bwmarrin/dca

That's the link to the dca project. There's a couple implementations listed there that you can use.

We need to update the readme on the airhorn example though to not refer to dca-rs anymore.
