### ISSUE TITLE
GuildMemberUpdate broken?

### ISSUE THREAD

**Issue by razaqq** [bwmarrin/discordgo#815]
It seems `GuildMemberUpdate` does not trigged. It should get triggered on changing nickname and adding/removing roles as far as i understand.

simple use case:
```
session.AddHandler(func(s *discordgo.Session, m *discordgo.GuildMemberUpdate) {
        fmt.Println("event")
    })
```

**Comment by CarsonHoffman** [comment]
Are you requesting the guild members intent, which is necessary to receive information about guild members? See the [FAQ}(https://github.com/bwmarrin/discordgo/wiki/FAQ#gateway-intents) for more information.

**Comment by razaqq** [comment]
omg you are right, i completely forgot about that. thanks alot
