### ISSUE TITLE
For what does targetType stand for?

### ISSUE THREAD

**Issue by adamijak** [bwmarrin/discordgo#821]
Could you please add this to doc?
What values can we store in targetType?
https://github.com/bwmarrin/discordgo/blob/8c5ca3de95d7876ef7f36b4111d6bf4a0cf12ed5/restapi.go#L1790

**Comment by adamijak** [comment]
"0" for Role "1" fo User
I suggest to update documentation

**Comment by CarsonHoffman** [comment]
#824 is introducing a set of constants in the library for the new types; once that gets merged, the signature of this function will change to use them.
