### ISSUE TITLE
Update to discord api version 8

### ISSUE THREAD

**Issue by NickUfer** [bwmarrin/discordgo#822]
DiscordGo currently uses the discord api [v6](https://discord.com/developers/docs/reference) which has now the status of "Deprecated". The project should be updated to support [v8](https://discord.com/developers/docs/reference).

**Comment by xyzst** [comment]
Looks like this should be resolved by https://github.com/bwmarrin/discordgo/pull/824

**Comment by CarsonHoffman** [comment]
Resolved by #866!
