### ISSUE TITLE
Printing current username

### ISSUE THREAD

**Issue by enterv0id** [bwmarrin/discordgo#831]
Hi,

I have a newbie question about printing the current username. 
Whenever I try to print with fmt.Println(dg.User("@me")) the username printed with a `<nil>` on the end 
like: `currentuser#1234 <nil>`
What am I doing wrong? 

Thank you

**Comment by CarsonHoffman** [comment]
[`(*Session).User`](https://pkg.go.dev/github.com/bwmarrin/discordgo#Session.User) returns two values: the user itself, and an `error` that indicates whether the call succeeded or not. Here, you're printing both values, and the `<nil>` represents the second value—the `error`; this value indicates that there was no error.

I'd recommend going through the [Go Tour section on errors](https://tour.golang.org/methods/19); they're extremely fundamental to programming in Go, and you'll see them on just about every method in this package, as well as in countless functions elsewhere.
