### ISSUE TITLE
Feature Request: func (s *Session) GuildBan(guildID string, userID string) (*GuildBan, error) 

### ISSUE THREAD

**Issue by prestonvanloon** [bwmarrin/discordgo#835]
I believe the functionality to get a ban by user ID is missing from this library.

See: https://discord.com/developers/docs/resources/guild#get-guild-ban

**Comment by person-with-a-username** [comment]
This was [added](https://pkg.go.dev/github.com/bwmarrin/discordgo#Session.GuildBan), so I guess this issue can be closed now.
