### ISSUE TITLE
Support the new Reply feature

### ISSUE THREAD

**Issue by ChrisGallardo** [bwmarrin/discordgo#839]
Discord recently added support for inline replies to the client: https://support.discord.com/hc/en-us/articles/360057382374-Replies-FAQ. discordgo should have support for this functionality.

## What it would look like
A message object would have a `Reply` field that is the message that the message replied to. If the message does not reply to any other message, `Reply` would be `nil`.
### Example
```go
func messageCreate(session *discordgo.Session, m *discordgo.MessageCreate) {
    // The message that m is replying to
    reply = m.Reply

    if reply != nil {
        s.ChannelMessageSend(m.ChannelID, reply.Content)
    }
}
```

If possible I would like to be assigned to this issue, thank you.

**Comment by CarsonHoffman** [comment]
This was implemented by #842.
