### ISSUE TITLE
unexpected end of JSON input on ChannelMessageSend()

### ISSUE THREAD

**Issue by Xackery** [bwmarrin/discordgo#85]
Xackery:
Error sending message unexpected end of JSON input
My only json parser on my script is discordgo, so
Lemme see if I can maybe capture the next error more detailed..
the code that spit that out is:
`
_, err := discord.ChannelMessageSend(config.OocChannel, fmt.Sprintf("%s OOC: %s", name, message))
                    if err != nil {
                        fmt.Println("Error sending message", err.Error())
                        os.Exit(1)
                    }
                    `
code was running a good ~3-5 hours, It appears the message DID succeed before it crashde, though, I imagine the return json failed to parse

IOPred:It's another case where we don't handle the network error before attempting JSON parsing. I think I'll go through and fix all those soon.

**Comment by bwmarrin** [comment]
Ah, looking at your example.  It looks like the ChannelMessageSend returned an error.  This error was most likely caused by today's network problems.  Even if what iopred mentions is fixed, it would still have returned an error - just maybe a different error.

**Comment by Xackery** [comment]
On error, I will echo and continue instead of sigterm exit, though a consideration is storing common errors to expect so I can handle them more gracefully.

**Comment by bwmarrin** [comment]
That's what I would recommend as well.  I'm sure at some point we can try to send more detailed errors but right now I just pass along the errors as they are.  But, it is always possible for any of these functions to return a non-fatal error that will need to be handled.

**Comment by iopred** [comment]
I think this is fixed now

**Comment by Xackery** [comment]
Yep, this is fine, thanks.
