### ISSUE TITLE
Slash commands

### ISSUE THREAD

**Issue by FedorLap2006** [bwmarrin/discordgo#850]
I suggest to implement slash commands API in the library. If no one can do it now, I can.

**Comment by FedorLap2006** [comment]
Now they're on official announcement. Should we (or I) work on it?

**Comment by FedorLap2006** [comment]
Okay, as I see, many people wants it, so... I'm working on it :slightly_smiling_face:

**Comment by FedorLap2006** [comment]
Btw, after closing this issue I will move onto #854.

**Comment by FedorLap2006** [comment]
Okay, I've just finished some part of the interactions API, but first of all, as I said, I need testers and feedback. But most important, I'm implementing only gateway and REST part of interactions.
Anyone wants webhooks system (just interactions or the whole system, maybe with server) ?

**Comment by FedorLap2006** [comment]
![image](https://user-images.githubusercontent.com/42876964/102679026-86bba180-41bd-11eb-81a6-bf75f510f355.png)
Btw, take a look.

**Comment by sarisia** [comment]
Can you open the source code by creating draft pull request so that anyone can try it by checking out?

**Comment by FedorLap2006** [comment]
Well, now - no. At least I need to complete basic API (such CRUD).
Until it - no, but responding hasn't yet implemented.

**Comment by FedorLap2006** [comment]
@sarisia Well, they're (almost) ready to go!

**Comment by FedorLap2006** [comment]
Any bugs please report here (maybe I forgot something idk).

**Comment by FedorLap2006** [comment]
Sorry for taking so long time to wait for the changes. I'm just busy. 
And I'm writing this to say, that everything is okay - in near days everything will be deployed.

**Comment by FedorLap2006** [comment]
For anyone wondering what's happening with this feature now - it's ready. We're waiting for approval and merge.

**Comment by incapable** [comment]
Hi, since the last reply is now more than a month ago, has this been merged? And has it been documented how to register slash commands with the library?

**Comment by AllAwesome497** [comment]
@incapable doesn't look like it has been merged - see #856.

**Comment by FedorLap2006** [comment]
Well, now it's finally merged, I think now we can close this.
