### ISSUE TITLE
Rewrite of the library

### ISSUE THREAD

**Issue by FedorLap2006** [bwmarrin/discordgo#854]
When I first time reading and trying to understand how DiscordGo works... I was a bit confused and went into many tutorials, but DiscordGophers mostly helped me. So... now I'm here, to propose rewrite this library with the newest best practices, and also caching, logging and many more features. **I have a [fork](https://github.com/FedorLap2006/discordgo) of this project, the main work on rewriting will be there.**
Here will be showed the progress of rewriting.
And... one more thing: any contributors to this rewrite will be **really welcomed**.

In continuation, I want to discuss and make structure of discordgo better and easier, especially for beginners, but for advanced users too.

Down here will be shown my vision and some already made examples of how DiscordGo might look at the end of the work. 

So, thanks everyone for attention.

**Comment by FedorLap2006** [comment]
My current vision of the... for example project files and folders structure is:

```
discord.go // Common things, including Session
module.go // Base modules interfaces, loaders, etc...
caching/
     provider.go
     gc.go
gateway/
     wsapi.go
     events.go
     eventhandlers.go
     ...
logging/
     logger.go
     ...
webhooks/
     webhook.go
     endpoints.go
     ...
api/
     messages.go
     interactions.go
     guilds.go
     channels.go
     ...
```

**Comment by FedorLap2006** [comment]
The structure of packages and other stuff I think you've already understood from this project structure.

**Comment by FedorLap2006** [comment]
And, the progress of rewriting.

- [ ] Logging
- [ ] Gateway
- [ ] API
- [ ] Webhooks
- [ ] Caching
- [ ] _Common_

**Comment by iopred** [comment]
A restructuring like you propose will break the current api and all users of the library. I think this warrants more discussion on why this is needed before you start work on it.

**Comment by FedorLap2006** [comment]
You don't understand, I've already discussed this with @CarsonHoffman. And we decided to make separated fork which will contain this rewriting, and after everything will be tested and everyone (from maintainers) will approve it, It will be merged and announcement will be made.

**Comment by CarsonHoffman** [comment]
That's not how I understood our conversation. I simply had noted that we would want to merge in any changes gradually rather than keeping a long-running dev branch; we still have the considerations of undue breaking changes in place.

**Comment by FedorLap2006** [comment]
This might be solved by announcement and deprecation of current code. So, nothing will break.

**Comment by FedorLap2006** [comment]
Oh, wait, I understood you.

**Comment by FedorLap2006** [comment]
I think that keeping changes in separated branch in separated fork will be better, than merge everything into master, because as @iopred  said "A restructuring like you propose will break the current api and all users of the library".

**Comment by FedorLap2006** [comment]
But... then we need to rewrite every commit which will be made here... to our structure. Hmmm :thinking:

**Comment by FedorLap2006** [comment]
So, what do we decide?

**Comment by iopred** [comment]
I think you need to spend some time thinking about why this is needed, some thoughts:
a) Why the current codebase isn't satisfactory
b) What developers will gain by you breaking up the codebase into modules, and whether that is worth their code being broken
c) What will this rewrite accomplish? Will it make adding new apis easier? What bugs will it solve? Why is now the right time to rewrite the library when it has been very functional for many years?

**Comment by FedorLap2006** [comment]
> I think you need to spend some time thinking about why this is needed, some thoughts:
> a) Why the current codebase isn't satisfactory
> b) What developers will gain by you breaking up the codebase into modules, and whether that is worth their code being broken
> c) What will this rewrite accomplish? Will it make adding new apis easier? What bugs will it solve? Why is now the right time to rewrite the library when it has been very functional for many years?

Okay. I will think about it, and respond when I will have a complete answer to this.

**Comment by Wouter0100** [comment]
Just adding my 2 cents here: if you really want to get in line with a lot of other Go packages, please have a look into [this repository](https://github.com/golang-standards/project-layout). I've seen (just as described there) that this is a wide used "sample" for designing Go applications and libraries.

**Comment by FedorLap2006** [comment]
> Just adding my 2 cents here: if you really want to get in line with a lot of other Go packages, please have a look into [this repository](https://github.com/golang-standards/project-layout). I've seen (just as described there) that this is a wide used "sample" for structering Go applications and libraries.

Well, yes, first of all, I wanted to refactor structure to structure like there.

**Comment by FedorLap2006** [comment]
Well, as continuation of previous discussion, I want to say, after some period, my opinion about this situation and my issue as whole. 

Yeah, DiscordGo was meant to be more like unsafe and lowlevel wrapper for Discord API, but this doesn't mean It won't be comfortable, easy, supportable and flexible. And yeah, I've seen some custom libraries like Disgord and Arikawa, but why not bring here changes? I don't mean changes which will change concept of library, but I mean the changes which will only improve the library. Like separation into modules, improved caching, logging.

So, after finishing the issue with slash-commands, I think I will try to create interesting layout and will post it here.

Thanks again, for attention.

**Comment by FedorLap2006** [comment]
Also, I want to make this more clear:
> a) Why the current codebase isn't satisfactory
b) What developers will gain by you breaking up the codebase into modules, and whether that is worth their code being broken
c) What will this rewrite accomplish? Will it make adding new apis easier? What bugs will it solve? Why is now the right time to rewrite the library when it has been very functional for many years?

a) Well, there's a lot of names to remember (without autocompletion of course) and they well, looks awful. 
b) Modules is very good way to separate API and make it easier to remember and use. And also, it helps with naming and helps with understanding what's where belongs.
c) As I said, the API will be easier, that's the whole point, also rewriting is often might solve ~~and cause~~ some bugs. And well, after bringing more and more features in this library, in some point it will be really harder to use it, my suggestion will solve this problem.

**Comment by FedorLap2006** [comment]
@iopred And... ^^^

**Comment by svenwiltink** [comment]
a) We have godoc. Finding the correct function is incredibly easy because it directly maps to the functions in the official discord api
b) Separating the gateway, api and webhooks might make it look a bit nicer at first, but they are often used in conjuction so I currently see no major advantages in splitting these into separate packages.
c) Easier is subjective, see a and b. 

I would also like to add that a rewrite on this scale warrants a new major version release. Making breaking changes like this is not acceptable. According to pkg.go.dev this libary is known to be imported by 1680 projects. This would break all of those with the push of a button. 
Releasing a new major version comes with some caveats as well. How long will we support both versions for? Are new features only going to be added to the new version? People also need time to transition to the new version. To give you an example: A new major version of a production API I have worked on was released a year ago. Today only 35% of all API calls are using the new version. The old API will be in maintenance mode for the foreseeable future.

With the only concrete upside of this potential rewrite boiling down to "It will be prettier/easier" I don't think it is a good idea. If however there are some real benefits we are open to that. Examples of such arguments:

- Doing this rewrite allows up to fix issue X Y Z. These have not been fixed yet because they would need breaking changes
- It enables us to add feature X Y Z to the library.
- The codepath of X Y Z, that has been buggy or hard to use since <time> can be cleaned up.

**Comment by FedorLap2006** [comment]
> I would also like to add that a rewrite on this scale warrants a new major version release. Making breaking changes like this is not acceptable. According to pkg.go.dev this libary is known to be imported by 1680 projects. This would break all of those with the push of a button.

Okay, I understood that, but at the some point we actually need to make some breaking changes. 

> Separating the gateway, api and webhooks might make it look a bit nicer at first, but they are often used in conjuction so I currently see no major advantages in splitting these into separate packages.

I think a good idea in such case will be just making them standalone, so they won't depend on each other. Yeah, there will be some breaking changes, but their amount won't be so big.

At least, I think, after finishing the slash commands I will try to improve the caching. Why it need improving? - Well, it has many problems, such as filling memory up to maximum, because no one cares about cleaning of the cache.

**Comment by FedorLap2006** [comment]
Just wanted to say my thoughts about this issue after a while, especially after diving into the library and making a big PR for it. I see that this library is specialized on being "low-level". But this raises question: yeah, that's good, but will we move onto some more comfortable API or will sit at the "low-level"?

**Comment by bwmarrin** [comment]
DiscordGo will remain a low level wrapper around the Discord API forever.  That's the goal of the library and if there's a need for a different type of library, that's more "comfortable" (Not sure what that actually means) then there's room for other libraries to exist :)

The idea of re-writing DiscordGo may have some tiny bits of real merit but the challenge of doing it and the headaches it would cause for the thousands of people using it are not worth it let alone the actual person-hours it would take to do so on a project that already has a limited number of people able to give it the love it deserves :)

It's possible that we'll slowly make small changes here and there to improve various things but a full rewrite is not going to happen outside some far far future where a version 2 is developed.

**Comment by FedorLap2006** [comment]
> It's possible that we'll slowly make small changes here and there to improve various things but a full rewrite is not going to happen outside some far far future where a version 2 is developed.
Looking forward for that. But at least for now I think fixing some bugs would be areally good idea.
