### ISSUE TITLE
Error MessageReactionAdd

### ISSUE THREAD

**Issue by danielbenedi6** [bwmarrin/discordgo#865]
**DESCRIPTION**
When trying to add a reaction to a message gets the following error:
`HTTP 400 Bad Request, {"message": "Unknown Emoji", "code": 10014}`

**HOW TO REPLICATE**
This is a part of my message handler:
```
func msgHandler(s *discordgo.Session, m *discordgo.MessageCreate){
    emojis, err := s.GuildEmojis(m.GuildID)
    if err !=  nill {
        //Do something 
        return   
    }

    if len(emojis) > 0 {
        err = s.MessageReactionAdd(m.ChannelID, m.ID, emojis[0].ID)
        if err != nil{
            fmt.Println("Error on Reaction", err)
        }
    }
}
```

**MORE INFO**
The [official Discords' doc](https://discord.com/developers/docs/resources/channel#create-reaction) say that if a emoji isn't URL Encoded, it will throw the ERROR 400 Unknown Emoji.

**Comment by CarsonHoffman** [comment]
Use `emojis[0].APIName()`. Unicode emojis don't have an ID, and require the emoji itself to be sent; `APIName` does that for you.
