### ISSUE TITLE
Issue creating voice channel

### ISSUE THREAD

**Issue by laurentmathy** [bwmarrin/discordgo#869]
Hi, I used to have voice channel creation working under discordgo v0.22.0. 
The bot last worked ok in mid-december, but was then basically left unused until now.
The creation of voice channel fails with "HTTP 403 Forbidden, {"message": "Missing Permissions", "code": 50013}", so it looks like a permissions issue while nothing was changed in the server config.
Updated to discordgo v0.23.1, "go clean --modcache", and updated the code accordingly to:

`ch, err := s.GuildChannelCreateComplex(
    m.GuildID,
    discordgo.GuildChannelCreateData{
        Name:     memberNick(s, usr, m.GuildID),
        Type:     discordgo.ChannelTypeGuildVoice,
        ParentID: c.category,
        PermissionOverwrites: []*discordgo.PermissionOverwrite{
            {ID: c.roleMap["moderator"], Type: discordgo.PermissionOverwriteTypeRole, Allow:  discordgo.PermissionAllVoice},
            {ID: c.roleMap["@everyone"], Type: discordgo.PermissionOverwriteTypeRole, Deny: 
                                                                                                                                                       discordgo.PermissionVoiceConnect},
        },
    })`

But to no avail: I am still getting the same error.
Anything obvious that I am missing?

Thanks a lot!

**Comment by CarsonHoffman** [comment]
This might be related to https://github.com/discord/discord-api-docs/issues/2522.

**Comment by laurentmathy** [comment]
@CarsonHoffman It is! Thanks, you are a star!
