### ISSUE TITLE
change MentionRoles from []string to []*Role in message

### ISSUE THREAD

**Issue by razaqq** [bwmarrin/discordgo#870]
right now the message struct has the following fields
```go
	Mentions []*User `json:"mentions"`
	MentionChannels []*Channel `json:"mention_channels"`

	MentionRoles []string `json:"mention_roles"`
```

only MentionRoles is inconsistent by using []string and should use []*Role instead

**Comment by CarsonHoffman** [comment]
If we refer to [the Discord documentation](https://discord.com/developers/docs/resources/channel#message-object-message-structure):

> Field | Type | Description
> -- | -- | --
> mentions*** | array of user objects, with an additional partial member field | users specifically mentioned in the message
> mention_roles | array of role object ids | roles specifically mentioned in this message
> mention_channels?**** | array of channel mention objects

Note that `mention_roles` is an "array of **role object ids**".

**Comment by razaqq** [comment]
hmm maybe, its still really invonvenient to work with it
