### ISSUE TITLE
GuildMemberAdd (again)

### ISSUE THREAD

**Issue by kpfaulkner** [bwmarrin/discordgo#871]
Anyone else having issues with GuildMemberAdd/Remove events? (exact same issue as https://github.com/bwmarrin/discordgo/issues/793 )

I've already enable server members intent/presence intent.... but no luck.

Other events work fine, just having issues with these 2.

Cheers

Ken

**Comment by CarsonHoffman** [comment]
Could you show your relevant session creation, intents setup and gateway opening code (including their relative positions), and confirm that the intents are enabled within your developer portal?

**Comment by kpfaulkner** [comment]
Actually, ignore that. Was my bad.

I'd left discordgo.MakeIntent(discordgo.IntentsAllWithoutPrivileged) in the code....   doh!
