### ISSUE TITLE
GuildMemberRemove broken?

### ISSUE THREAD

**Issue by FoksVHox** [bwmarrin/discordgo#879]
Same issue as #793 but just for the remove event. I've enabled intents and I've allowed the code to use intents..
Not sure what is going on

**Comment by Beamer64** [comment]
Any update?

**Comment by FedorLap2006** [comment]
> Same issue as #793 but just for the remove event. I've enabled intents and I've allowed the code to use intents.. Not sure what is going on

Are you sure you enabled intents before `Open`ing the session?

**Comment by Beamer64** [comment]
> > Same issue as #793 but just for the remove event. I've enabled intents and I've allowed the code to use intents.. Not sure what is going on
> 
> Are you sure you enabled intents before calling `Open` on the session?


Just tested this and it worked when I kicked a User. Thanks!

**Comment by FedorLap2006** [comment]
Since issue is resolved. I'm going to close this.

**Comment by FoksVHox** [comment]
@FedorLap2006 I believe that also what fixed my issue, sorry for not closing when I figured it out a long time ago.
