### ISSUE TITLE
dca-rs not found

### ISSUE THREAD

**Issue by Nv7-GitHub** [bwmarrin/discordgo#887]
The airhorn example uses a tool called dca-rs to convert many audio formats to a DCA format, which is easy to send to discord. However, dca-rs doesn't seem to be on GitHub anymore. All the links to it are just a Github 404.

**Comment by bwmarrin** [comment]
Yeah, the dca-rs project doesn't exist anymore. The project owner removed the repository for it.   You can check out https://github.com/bwmarrin/dca for more information on the dca format and there is a simple reference implementation available there.
