### ISSUE TITLE
Associate between `MessageReaction.MessageID` and `Message.ID`

### ISSUE THREAD

**Issue by Hofled** [bwmarrin/discordgo#889]
The value of the `MessageID` in `MessageReaction.MessageID` is the ID of the reaction message event itself as a stand alone event, and it seems that currently there is no straight forward way to get the original message ID on which the reaction was posted on.

My intention is to use the `MessageReactionAdd` event in order to perform actions on the original message on which it was posted on, but this event triggers for any reaction posted on any message, hence the need to be able to associate between the reaction event and the original message ID.

**Comment by CarsonHoffman** [comment]
Reaction events don't have IDs. As the [Discord documentation notes](https://discord.com/developers/docs/topics/gateway#message-reaction-add-message-reaction-add-event-fields), the `message_id` property indicates the ID of the message on which the reaction was added. I'm not quite sure what the confusion is here; if you right click on the reaction in the client and "copy ID", that's actually getting the message's ID (as, again, reactions don't have IDs).

**Comment by Hofled** [comment]
> 
> 
> Reaction events don't have IDs. As the [Discord documentation notes](https://discord.com/developers/docs/topics/gateway#message-reaction-add-message-reaction-add-event-fields), the `message_id` property indicates the ID of the message on which the reaction was added. I'm not quite sure what the confusion is here; if you right click on the reaction in the client and "copy ID", that's actually getting the message's ID (as, again, reactions don't have IDs).

You are absolutely right! It was a very bad mistake on my end, it works just fine - I had a different issue which I managed to resolve, thank you :)

I had multiple locations registering new handlers to the `MessageReactionAdd` which results in some odd behaviors...
