### ISSUE TITLE
Question about Intents

### ISSUE THREAD

**Issue by Aiuzu42** [bwmarrin/discordgo#893]
Hi,
In update v0.23.0 I saw in the release notes that MakeIntent was no longer required, and that the function itself was a no-op, after updating my code to use this version I removed the use of MakeIntent from my code, I was using MakeIntent(discordgo.IntentsAll).
After that my events related to discordgo.GuildMemberRemove and discordgo.GuildMemberAdd are no longer working.
Is there another required way to set member intents? or is this an issue with the version?
Thanks

**Comment by CarsonHoffman** [comment]
v0.23.0 made `MakeIntent` obsolete; it did not remove the intents system entirely. You can simply now directly set your `Intents` field to `discordgo.IntentsAll` rather than `discordgo.MakeIntent(discordgo.IntentsAll)`.

**Comment by Aiuzu42** [comment]
Thanks, I found how to set the intents via `Identify.Intents`
