### ISSUE TITLE
Slash Commands /responses Error

### ISSUE THREAD

**Issue by Treslex** [bwmarrin/discordgo#897]
![image](https://user-images.githubusercontent.com/64252390/112068112-2f80f080-8b61-11eb-9310-0205c326660e.png)

**Comment by Treslex** [comment]
I think it is fixed with this [PR](https://github.com/bwmarrin/discordgo/pull/886) but could be wrong. I don't think the resp-type parameter shouldn't be optional which is what is causing the above errors?

**Comment by Nv7-GitHub** [comment]
Yes, this is fixed in that PR. I didn't make an issue though, so I guess this can just be left open until the PR is merged.

**Comment by Nv7-GitHub** [comment]
The PR has been merged, so I think that this issue can be closed.
