### ISSUE TITLE
Unused flag in slash command example

### ISSUE THREAD

**Issue by jolheiser** [bwmarrin/discordgo#910]
Possibly partially related to #909 

https://github.com/bwmarrin/discordgo/blob/577e7dd4f6ccf1beb10acdb1871300c7638b84c4/examples/slash_commands/main.go#L18

This flag is set, but is never used in the example, meaning the commands are never removed.

I'll try to send in a PR if no one else gets to it. 🙂

**Comment by Treslex** [comment]
![image](https://user-images.githubusercontent.com/64252390/115671621-9ea95a80-a342-11eb-999e-d8ef010e80bc.png)
![image](https://user-images.githubusercontent.com/64252390/115671663-a79a2c00-a342-11eb-97a2-e1c3b6beb46b.png)

**Comment by Treslex** [comment]
Then when shutting down and re-running it adds them again.
![image](https://user-images.githubusercontent.com/64252390/115671832-d31d1680-a342-11eb-8ade-dcd69d7a48d6.png)

**Comment by jolheiser** [comment]
@Treslex I'm not entirely sure, but that looks like you have both a guild _and_ global command registered for that bot.

I'm not sure about the `404`s, perhaps also related to the above? The commands were deleted when I tested the functionality, so I'm not sure how to reproduce right now.

**Comment by Treslex** [comment]
Hmmm thats odd. I was just running the the example without any modifications other than the token and guild id

**Comment by zeeZ** [comment]
Did you add global commands? Changes to them take a while to propagate. From the docs:

> Global commands are cached for **1 hour**. That means that new global commands will fan out slowly across all guilds, and will be guaranteed to be updated in an hour.

**Comment by FedorLap2006** [comment]
In this particular example I used guild commands, not global ones. Also yeah, thanks for finding this thing. I completely forgot about this flag when was trying to finish the PR.

**Comment by jolheiser** [comment]
Closed by #1103
