### ISSUE TITLE
Upgrade the API version and implement threads

### ISSUE THREAD

**Issue by FedorLap2006** [bwmarrin/discordgo#917]
Due https://github.com/discord/discord-api-docs/pull/2855 I think this is the best time to upgrade the API version and implement threads functionality. Probably I will implement them and create a draft PR.

P.S. It's not yet shipped and we can't actually test it, but probably this will be solved soon, and if so, I will start on implementing this great feature.

**Comment by FedorLap2006** [comment]
From Discord API server as I understood, they're planning to have some sort of allowlist for such functionality. Hoping that I can receive the access. But probably for other devs this will cause problems, because they're cannot test the functionality. But, waiting for official decision tomorrow.

**Comment by Strum355** [comment]
Work has begun on threads in discordgo: https://github.com/bwmarrin/discordgo/pull/922

**Comment by FedorLap2006** [comment]
Alright, then I'm going to close this issue.
