### ISSUE TITLE
bot not get user locale!!!

### ISSUE THREAD

**Issue by mark2021blue** [bwmarrin/discordgo#928]
DISCORD_BOT_INVITE_URL:
https://discordapp.com/oauth2/authorize?&client_id=***&scope=identify%20email%20bot&permissions=1007119441
![截屏2021-05-11 下午4 44 35](https://user-images.githubusercontent.com/83812275/117786658-53ff6c00-b278-11eb-8a30-e176f4810fd6.png)
use version: v0.23.2
thanks!!!

**Comment by t-h-o** [comment]
Apologies for responding to an older ticket. The `Locale` field is [supported](https://github.com/bwmarrin/discordgo/blob/e6a8d51c9b6ddb97734d20f6060483a8a932710a/user.go#L43). It's an optional field & seemingly isn't supported by bots. I found a mention of this in discordjs issue [#3988](https://github.com/discordjs/discord.js/issues/3988).

**Comment by CarsonHoffman** [comment]
Correct—the field is only obtainable via performing a full OAuth2 flow and using the user's bearer token. The fact that you included the `identify` scope in your bot's authorization URL doesn't mean that your bot will have access to this information; you still need to go through the typical OAuth2 route. See [Discord's documentation on OAuth2](https://discord.com/developers/docs/topics/oauth2) for more information.
