### ISSUE TITLE
Changing `Session.Client` to be interface type instead of concrete `*http.Client` can help with writing unit tests

### ISSUE THREAD

**Issue by ewohltman** [bwmarrin/discordgo#939]
Changing `Session.Client` to be an interface type instead of a concrete `*http.Client` can help with writing unit tests for projects that depend upon `discordgo`~~, while not breaking existing users by still allowing `*http.Client`.~~ @zacharyburkett brought up a good point that people may be using the existing `Session.Client` fields directly, so this could be a breaking change. It might be hard to find an real-world example where someone is using those fields directly where this change would break them, but the possibility exists.

An example repository I've been working on to help ease unit testing with `discordgo` can be found here: https://github.com/ewohltman/discordgo-mock

(FYI, the repo is still pretty new and no doubt missing API paths for the time being).

In particular, this function below allows us to create a ` discordgo.RESTClient`-satisfying object that will use `discordgo.State` to process API requests (found in https://github.com/ewohltman/discordgo-mock/blob/main/pkg/mockrest/mockrest.go):

```go
type roundTripperFunc func(req *http.Request) (*http.Response, error)

func (rt roundTripperFunc) RoundTrip(req *http.Request) (*http.Response, error) {
	return rt(req)
}

type Client struct {
	*http.Client
	state  *discordgo.State
	router *mux.Router
}

func NewClient(state *discordgo.State) *Client {
	router := mux.NewRouter()

	client := &Client{
		Client: &http.Client{
			Transport: roundTripperFunc(func(r *http.Request) (*http.Response, error) {
				responseRecorder := httptest.NewRecorder()
				router.ServeHTTP(responseRecorder, r)
				return responseRecorder.Result(), nil
			}),
		},
		state:  state,
		router: router,
	}

	apiVersion := "/api/v" + discordgo.APIVersion

	client.addHandlersGuilds(apiVersion)
	client.addHandlersChannels(apiVersion)
	client.addHandlersUsers(apiVersion)

	return client
}
```

Example usage of the `RESTClient` with `Session.Client` change (found in https://github.com/ewohltman/discordgo-mock/blob/main/pkg/mocksession/mocksession_test.go):

```go
func newSession(expectedResources *resources) *discordgo.Session {
	state, err := mockstate.New(
		mockstate.WithUser(mockuser.New(
			mockuser.WithID("Bot"),
			mockuser.WithUsername("Bot"),
			mockuser.IsBot(true),
		)),
		mockstate.WithGuilds(expectedResources.guild),
	)
	if err != nil {
		panic(err)
	}

	session, err := mocksession.New(
		mocksession.WithState(state),
		mocksession.WithRESTClient(mockrest.NewClient(state)),
	)
	if err != nil {
		panic(err)
	}

	return session
}
```

**Comment by zacharyburkett** [comment]
Since this field is exported, changing its type in the struct would be a breaking API change.

**Comment by ewohltman** [comment]
@zacharyburkett Good point. I'll leave this here in case there is appetite to adopt this change. If not, this PR can be closed without merge :+1:

**Comment by ewohltman** [comment]
As discussed, the scope of the proposed change in this issue would result in an API-breaking change and will be closed. Alternative methods for easing unit testing will be investigated.

**Comment by ewohltman** [comment]
For future reference:

I started looking into an alternative approach by replacing the `*http.Client.Transport` with a custom `http.RoundTripper` that seems to do the job:

https://github.com/ewohltman/discordgo-mock

Example usage of this new "helper" library can be found here until I can more fully flesh out the `discordgo-mock` repo with better examples and unit tests:

https://github.com/ewohltman/ephemeral-roles/blob/develop/internal/pkg/mock/session.go

Comments, questions, and improvements are welcome to discordgo-mock!
