### ISSUE TITLE
User/role permissions for using slash commands

### ISSUE THREAD

**Issue by NotUnlikeTheWaves** [bwmarrin/discordgo#942]
Hello, I've implemented slash commands successfully in a bot but haven't found permissions implemented in this library yet, as described in https://discord.com/developers/docs/interactions/slash-commands#permissions and the four subsections describing the API calls for those permissions (get guild permissions for all commands in a guild, get permissions of a single command in a guild, edit a single command in a guild, bulk edit permissions in a guild)

I've already taken steps to add this functionality myself in the following pull request #943. Feedback is welcomed in either location

**Comment by NotUnlikeTheWaves** [comment]
One thing I've noticed in the docs under the permissions part is the default_permissions, which can optionally be sent on creating and editing a command. If set to false, it means the command is disabled until a permissions overwrite exists on that command.

It's a little vague on how best to implement this as the default boolean value is 'false' which could be fatal for many commands made that assume that creating a command without special intervention enables it for everyone. This is also what's implied via the discord API docs since the field is optional.

**Comment by FedorLap2006** [comment]
Merged in d5bacb5401a6652f48edfbf133fd55a159b95b18
