### ISSUE TITLE
Release date for interactions

### ISSUE THREAD

**Issue by cezarmathe** [bwmarrin/discordgo#944]
Hi! 

Do you plan to release a version of the library that supports interactions (and slash commands)? If there is, is there a hint of the duration this may take?

Thanks.

**Comment by CarsonHoffman** [comment]
The interactions API is still undergoing large changes that are (hopefully) culminating to an extent with the release of buttons; once the API becomes more stable and we have support for buttons we'll most likely be ready to go ahead with a release, but at the moment it's just too volatile to put out a release. Unfortunately there's no set timetable at this point, since it largely depends on changes on Discord's end.

**Comment by jolheiser** [comment]
Just to point out for those who find this issue in the meantime, you can still use slash commands by using a commit version or 

`go get github.com/bwmarrin/discordgo@master`

Just keep in mind that things may change prior to the next tag. :slightly_smiling_face:

**Comment by FedorLap2006** [comment]
And one more note: if you want to test out buttons already you can use `github.com/FedorLap2006/discordgo@master`. But hopefully Carson will merge them soon.

**Comment by FerranMarin** [comment]
Any updates?

**Comment by odiferousmint** [comment]
I just tried out their example with the slash commands but it did not work. I left the guild ID empty (meaning global), but it does not seem to be working, there are no new slash commands. That said, it does take longer to start up and shut down. I have no clue why it is not working.

In any case, there seems to be buttons according to https://github.com/bwmarrin/discordgo/blob/4ebe5a08ee6752ac8768cc3ed2f05ff6aad595f5/components.go, but I have no idea how to get it working.

**Comment by Nv7-GitHub** [comment]
v0.25.0 supports interactions

**Comment by Nv7-GitHub** [comment]
> I just tried out their example with the slash commands but it did not work. I left the guild ID empty (meaning global), but it does not seem to be working, there are no new slash commands. That said, it does take longer to start up and shut down. I have no clue why it is not working.
> 
> In any case, there seems to be buttons according to https://github.com/bwmarrin/discordgo/blob/4ebe5a08ee6752ac8768cc3ed2f05ff6aad595f5/components.go, but I have no idea how to get it working.
> 
> I tried https://github.com/bwmarrin/discordgo/blob/4ebe5a08ee6752ac8768cc3ed2f05ff6aad595f5/examples/components/main.go as well, but I see no new slash commands from the bot. I have no idea why.

You probably forgot to give your bot the `application.commands` scope when inviting it to the server

**Comment by odiferousmint** [comment]
Oh, that might be true. I will give this another try when I get the time.

By the way, does `discordgo` support buttons or whatever they call them?

**Comment by FedorLap2006** [comment]
> By the way, does `discordgo` support buttons or whatever they call them?

DiscordGo v0.25.0 supports all currently available components and interactions.

**Comment by FedorLap2006** [comment]
Additionally, as @Nv7-GitHub mentioned, since v0.24.0 and v0.25.0 were released, I think it would be a good idea to close this issue.
