### ISSUE TITLE
Missing application commands functional

### ISSUE THREAD

**Issue by FedorLap2006** [bwmarrin/discordgo#947]
I was recently scrolling through the docs (while making some improvements into #933) and found out that we're missing endpoints related to managing application commands permissions:
- [Get Guild Application Command Permissions](https://discord.com/developers/docs/interactions/slash-commands#get-guild-application-command-permissions)
- [Get Application Command Permissions](https://discord.com/developers/docs/interactions/slash-commands#get-application-command-permissions)
- [Edit Application Command Permissions](https://discord.com/developers/docs/interactions/slash-commands#edit-application-command-permissions)
- [Batch Edit Application Command Permissions](https://discord.com/developers/docs/interactions/slash-commands#batch-edit-application-command-permissions)

I think we should implement them.

**Comment by CarsonHoffman** [comment]
It looks like these are covered by #943.

**Comment by CarsonHoffman** [comment]
Additionally, this is a duplicate of #942.
