### ISSUE TITLE
Support guild ownership transfership change

### ISSUE THREAD

**Issue by bwmarrin** [bwmarrin/discordgo#95]
So, this is going to be a thing.

https://github.com/Rapptz/discord.py/commit/178d43e24ff1fe6009fd39eac5cc3efda336ac66

**Comment by iopred** [comment]
I think we support this, our state update will set all properties, including the owner id.

**Comment by bwmarrin** [comment]
Well then, I like it when it already works.  I didn't even check much on this just wanted to write it down before I forgot it :)

**Comment by bwmarrin** [comment]
I am guessing there will be a endpoint or something to change the ownership too.  Maybe just a PATCH/POST on the Guild endpoint.  Might need to add support for that.

**Comment by robbix1206** [comment]
![image](https://cloud.githubusercontent.com/assets/1793523/19001163/518e01c8-8746-11e6-8503-5a6fb119fa17.png)
It's a PATCH request we will need to add it to GuildParams structure if we want to support that.

**Comment by CarsonHoffman** [comment]
I know this issue is quite old, but as far as I can tell this is supported by the library at this time. If this isn't the case, feel free to re-open!
