### ISSUE TITLE
Webhooks API isn't complete.

### ISSUE THREAD

**Issue by FedorLap2006** [bwmarrin/discordgo#951]
When I was reading the Discord API docs as usual... while making #933 I found that our current API is missing the [one](https://discord.com/developers/docs/resources/webhook#get-webhook-message) endpoint. And these endpoints: [webhook execute](https://discord.com/developers/docs/resources/webhook#execute-webhook), [webhook message edit](https://discord.com/developers/docs/resources/webhook#edit-webhook-message) and [message delete](https://discord.com/developers/docs/resources/webhook#delete-webhook-message) lack support of attachments. And in case of [webhook message edit](https://discord.com/developers/docs/resources/webhook#edit-webhook-message) endpoint - it's also missing returned by the endpoint message object (updated message).

P.S. Basically I have the code to fix these issue, but would like to know, open another PR on that, or include it straight into #933?

**Comment by FedorLap2006** [comment]
Since no one wants to respond, I will probably include them in the next PR.

**Comment by jolheiser** [comment]
I would argue that webhook changes should go in a separate PR unless they are added specifically for the interactions. 

e.g. attachment support could probably go in another PR

**Comment by FedorLap2006** [comment]
Well, late. Already pushed this to #954.

**Comment by FedorLap2006** [comment]
Can remove the code from there tho
