### ISSUE TITLE
Support for ETF

### ISSUE THREAD

**Issue by bwmarrin** [bwmarrin/discordgo#96]
Discord is going to add ETF support, supposedly. 

Will need more details before we can jump on this.

https://github.com/goerlang/etf
https://github.com/hammerandchisel/erlpack

**Comment by bwmarrin** [comment]
```
Jake - Today at 1:05 PM
u just send
the IDENTIFY packet
as ETF
and it will talk ETF
back at u
meew0 - Today at 1:05 PM
identify is op 2 right?
Jake - Today at 1:05 PM
idk off the top of my head
meew0 - Today at 1:05 PM
the one that also has the token and large_threshold and version
Danny - Today at 1:05 PM
yes
Jake - Today at 1:05 PM
yea
```

**Comment by bwmarrin** [comment]
```
Jake - Today at 1:05 PM
first packet u send should be in ETF
we tested some of ur bots using ETF locally
was like a 5-10 line change
to get it working
Skippy - Today at 1:06 PM
Yeah it should be easy
I assume Discord would prefer we use ETF?
meew0 - Today at 1:06 PM
why didn't you make PRs 😛
Skippy - Today at 1:06 PM
^^
```

**Comment by nhooyr** [comment]
Is this important for performance? I think we should just stick with JSON.

**Comment by zet4** [comment]
Performance benefit as of now, discord sends a mighty ton of updates over the ws, all of them in json right now, here is a benchmark from 2 months ago by @jonas747, json in that benchmark wins in bandwidth because it has compression support which etf doesn't, but decompression also takes cpu cycles
```
-- ETF --

2017/05/14 17:02:38 [DG2] wsapi.go:405:onEvent() Took 45.738µs to decode 43 bytes
2017/05/14 17:02:38 [DG2] wsapi.go:405:onEvent() Took 122.472µs to decode 454 bytes
2017/05/14 17:02:38 [DG2] wsapi.go:479:onEvent() Took 20.751µs to assign 454 bytes second pass etf
2017/05/14 17:02:38 [DG2] wsapi.go:405:onEvent() Took 650.781µs to decode 9137 bytes
2017/05/14 17:02:38 [DG2] wsapi.go:479:onEvent() Took 5.504µs to assign 9137 bytes second pass etf

-- JSON --
2017/05/14 17:04:07 [DG2] wsapi.go:382:onEvent() Took 39.324µs to decode 36 bytes
2017/05/14 17:04:07 [DG1] wsapi.go:435:onEvent() unknown Op: 11, Seq: 0, Type: , Data: null, message: {"t":null,"s":null,"op":11,"d":null}
2017/05/14 17:04:07 [DG2] wsapi.go:382:onEvent() Took 137.505µs to decode 290 bytes
2017/05/14 17:04:07 [DG2] wsapi.go:451:onEvent() Took 169.457µs to decode 290 bytes second pass
2017/05/14 17:04:07 [DG2] wsapi.go:382:onEvent() Took 528.268µs to decode 2397 bytes
2017/05/14 17:04:07 [DG2] wsapi.go:451:onEvent() Took 963.654µs to decode 2397 bytes second pass

655us vs 1231us
```

ps. most libraries provide an easy toggle for this on creation, so I see no reason not to do this here as well

**Comment by nhooyr** [comment]
Extra complexity and more code to maintain is a reason. I cannot find a maintained library to do this so we'd have to write a etf library ourselves. Though it looks like @jonas747 forked the one by goerlang and updated it. I still don't think that's worth it, especially given that 600us is negligible.

If we want more performance we can use one of the alternative JSON libraries like https://github.com/pquerna/ffjson

We'd get better performance and wouldn't have to maintain a second library ourselves.

**Comment by jonas747** [comment]
The fastest json lib out there for go is json-iter, https://github.com/json-iterator/go 
I benched it a while ago and from memory the result was that it was 300% faster when used in discordgo, it achieves the result by not using reflection and instead bypasses the go typing using unsafe, it's not entirely a drop in replacement either for discordgo, i remember i ran into some issues with differering behaviour for things such as json.Number and whatnot.

Also this is a very hot code path so doubling the performance here does have a noticeable impact i would say.

**Comment by bwmarrin** [comment]
This is so old and making no progress.  I'm going to close it.  If someday someone has the time to dig into and making a ETF library work - then it can be reopened at that time.
