### ISSUE TITLE
MessageCreate.Content is empty

### ISSUE THREAD

**Issue by Vadmeme** [bwmarrin/discordgo#961]
```go
dg, err := discordgo.New("redacted")
if err != nil {
    fmt.Println("error creating Discord session,", err)
    return
}

dg.AddHandler(func(s *discordgo.Session, m *discordgo.MessageCreate) {
    log.Printf("what: %s", m.Content)
})

err = dg.Open()
if err != nil {
    fmt.Println("error opening connection,", err)
    return
}

// Wait here until CTRL-C or other term signal is received.
fmt.Println("Bot is now running.  Press CTRL-C to exit.")
sc := make(chan os.Signal, 1)
signal.Notify(sc, syscall.SIGINT, syscall.SIGTERM, os.Interrupt, os.Kill)
<-sc
```

on a discord user token (not a bot, and yes i know this is against discord TOS)
discordgo has the events .content be empty, everything else appears to be there (author, guild, channelid, etc) but the message content is missing

it however is NOT missing if the author is from your active account

**EXPECTED BEHAVIOR:** outputs `what: [message content]`
**ACTUAL BEHAVIOR:** 
![image](https://user-images.githubusercontent.com/32437728/123634659-943a8f80-d7cf-11eb-8999-19664ccc0f3e.png)

**Comment by justindh** [comment]
able to confirm the same on both 22.0 and 23.2

**Comment by justindh** [comment]
according to [Discord Api Docs](https://github.com/discord/discord-api-docs/commit/bfea93e1bfd20c79e888f53f0186fed27ccf592d) they removed message contents from the V8 end point and its now only available on the v9 end point with a new format

**Comment by justindh** [comment]
This is a change on Discords side, not entirely sure what it is, but it only impacts Self bots (fixed by adding bot to your token) an example work around is to use the ChannelMessages to lookup the message like so..

`func MessageCreate(s *discordgo.Session, m *discordgo.MessageCreate) {

	if m.Content == "" {
		chanMsgs, err := s.ChannelMessages(m.ChannelID, 1, "", "", m.ID)
		if err != nil {
			log.Errorf("unable to get messages: %s", err)
			return
		}
		m.Content = chanMsgs[0].Content
		m.Attachments = chanMsgs[0].Attachments
	}
}`

**Comment by git-shochann** [comment]
Has this problem been resolved?

**Comment by justindh** [comment]
Not that I know of, because it is a problem with an unsupported mode, I doubt it will ever get traction

**Comment by Tumbler** [comment]
I'm having the same issue, but I'm not running a selfbot. And the workaround also doesn't have the content. I'm at a bit of a loss here...

**Comment by Nv7-GitHub** [comment]
Make sure to enable the message intent in the developer dashboard

**Comment by Tumbler** [comment]
You are correct, that was my issue. I should have updated this. Thank you for responding!

**Comment by syntaqx** [comment]
For those that run into this, be sure to visit the "Bot" tab under your Application, and
![image](https://github.com/bwmarrin/discordgo/assets/6037730/5fe8af1c-8619-48ac-ab25-9c890924a89e)

**Comment by dev-diver** [comment]
> For those that run into this, be sure to visit the "Bot" tab under your Application, and ![image](https://private-user-images.githubusercontent.com/6037730/241335533-5fe8af1c-8619-48ac-ab25-9c890924a89e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNzU4OTgsIm5iZiI6MTcyMzI3NTU5OCwicGF0aCI6Ii82MDM3NzMwLzI0MTMzNTUzMy01ZmU4YWYxYy04NjE5LTQ4YWMtYWIyNS05Yzg5MDkyNGE4OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTBUMDczOTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2I2MmI5YjUyMjk2OWVmNTlmMThmMDgwZjJkMDVmYWNmZDdkM2VlNmM0MTBhNWFlZGNiMzBlNzQ1YTM4ZGI5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wob9qrCc-v7riadk41C2FS6RYnj4CPigIiScr2VI5rk)

solved!

**Comment by dev-diver** [comment]
@syntaqx solved! thx

**Comment by egin10** [comment]
> For those that run into this, be sure to visit the "Bot" tab under your Application, and ![image](https://github.com/bwmarrin/discordgo/assets/6037730/5fe8af1c-8619-48ac-ab25-9c890924a89e)

Thank you, you're save my life.
