### ISSUE TITLE
Add support for per-guild avatars.

### ISSUE THREAD

**Issue by FedorLap2006** [bwmarrin/discordgo#965]
Suggest to add support of per-guild avatars. Yes, this feature is restricted for usage only of some group of people but it's already on the API, so I guess we can implement it.

**Comment by andresperezl** [comment]
I just saw this is a duplicate of https://github.com/bwmarrin/discordgo/pull/985, but the original author seems to be inactive after being asked for some change

w.r.t https://github.com/bwmarrin/discordgo/pull/985#discussion_r769135345

I saw other string fields which are also nullable to be left as just `string` (like `Nick`) so I followed the same, but I can change `Avatar` to `*string` is that is what is desired.

cc @CarsonHoffman  @FedorLap2006
