### ISSUE TITLE
github page is not aavaliable

### ISSUE THREAD

**Issue by victorfernandesraton** [bwmarrin/discordgo#971]
when access http://bwmarrin.github.io/discordgo/ i see Not Found github page message

**Comment by pablodz** [comment]
Still down 
![image](https://user-images.githubusercontent.com/28235457/128717378-b05b1959-7882-4422-87a3-fcf150e05cf4.png)

**Comment by bwmarrin** [comment]
There is no longer a website associated with this library.     I've removed the link to it from the about section.  Sorry for misleading :)

**Comment by pablodz** [comment]
Thanks for updating urls!
