### ISSUE TITLE
Any plans for a new release version?

### ISSUE THREAD

**Issue by afk11** [bwmarrin/discordgo#986]
I realized the docs in master mention stuff that isn't published yet, is there any plan for a release soon?

**Comment by jolheiser** [comment]
I believe https://github.com/bwmarrin/discordgo/issues/944#issuecomment-847232482 still applies for the time being, until Discord finishes solidifying interactions.

**Comment by afk11** [comment]
Thanks for the update, I'll subscribe to that issue instead :+1:
