### ISSUE TITLE
Are examples outdated?

### ISSUE THREAD

**Issue by JonathanGzzBen** [bwmarrin/discordgo#988]
I copied code from [components example](https://github.com/bwmarrin/discordgo/blob/master/examples/components/main.go) and get:
- InteractionCreate not declared by package discordgo
- s.InteractionRespond undefined (type *discordgo.Session has no field or method InteractionRespond)
- InteractionApplicationCommand not declared by package discordgo
- InteractionResponse not declared by package discordgo
- ...

**Comment by jolheiser** [comment]
Please see https://github.com/bwmarrin/discordgo/issues/944#issuecomment-848394667

It's in reference to slash commands, but also applies to components as they're in master but not tagged yet. 🙂

**Comment by FedorLap2006** [comment]
Issue should be resolved. Slash commands were tagged in `v0.24.0`, please run `go get -u github.com/bwmarrin/discordgo` to update.
