### ISSUE TITLE
Should we change the default branch to Master?

### ISSUE THREAD

**Issue by bwmarrin** [bwmarrin/discordgo#99]
Originally I set develop as the main branch because PR's default against the main branch.  Also when you make a commit and reference an issue like closes #?? then they will only close the issue if that commit applies to the main branch.  This makes tracking open issues easier for me.

On the flip side, go get defaults to pulling from the master branch and this has caused some confusion for people who look at the examples or code here (which default to the dev branch) and try to use them on their code that has the master branch installed.

Thoughts?

**Comment by bwmarrin** [comment]
Another option is to just add some notes about this in the README to help avoid confusing new users.

**Comment by iopred** [comment]
I think the dev/master split is much more important once we hit 1.0.

Currently it's bit me a few times, and not being able to `go get` the develop branch is a pain.

Perhaps we set up http://labix.org/gopkg.in so that we can just tag the master branch and continue to develop on it. At the very least we should push master a little more often.

**Comment by bwmarrin** [comment]
hmnn, I was asking about which repo to display when you first open the github page :)

On the dev/master split, I donno.  With a handful of people using the lib now I hate to constantly be dumping breaking changes into the master - since we're changing a lot still.  The gopkg.in is something I'll check out though.

**Comment by iopred** [comment]
Changing the default branch is essentially changing the release process :P

**Comment by bwmarrin** [comment]
Added more detailed information to the README about master vs develop and an example how to update to develop after installing via `go get`.  

Due to the sometimes not-so-stable nature of develop I want to keep these separated and release stable versions with documented changes on an approx 3-6 week schedule for now.
