### ISSUE TITLE
Guild Names Missing in Ready Object

### ISSUE THREAD

**Issue by TannerKvarfordt** [bwmarrin/discordgo#999]
First off, I am new to this library so I apologize if I just missed something obvious.

For debugging purposes, I want to print the guilds that my bot is a member of on the Ready event. Based on what I see in the Ready struct, something like this should work, but does not produce any results.
```go
fooSession.AddHandler(func(s *discordgo.Session, r *discordgo.Ready) {
	msg := "Guilds:\n"
	for _, g := range r.Guilds {
		msg += g.Name + "\n"
	}
	log.Print(msg)
})
```
However, I am able to retrieve the guild names from the session using the ID provided in the Ready object.
```go
fooSession.AddHandler(func(s *discordgo.Session, r *discordgo.Ready) {
	msg := "Guilds:\n"
	for _, g := range r.Guilds {
		sGuild, _ := s.Guild(g.ID)
		msg += sGuild.Name + "\n"
	}
	log.Print(msg)
})
```
Am I missing something and this behavior is intentional, or is this a bug?

**Comment by CarsonHoffman** [comment]
This is expected behavior. On the ready event, only the IDs of guilds are available to the bot. Guilds' full information is loaded lazily via guild create events at a later point; if you want to do something for each guild, you should be handling that event.

**Comment by TannerKvarfordt** [comment]
Good to know. I appreciate the help!
